# Global Applicability

People who defy cultural boundaries of sex and
gender have existed in cultures worldwide since
ancient times, sometimes acknowledged in local
language terms (Feinberg, 1996). In contrast to
the more recent pathologization of gender diversity
as an illness, some cultures traditionally celebrated
and welcomed this diversity (e.g., Nanda, 2014;
Peletz, 2009). Today, the English language umbrella
term transgender and gender diverse (TGD)
describes a huge variety of gender identities and
expressions, and therefore a population with
diverse health care experiences and needs. Together,
TGD people represent important aspects of human
diversity the World Professional Association for
Transgender Health (WPATH) asserts should be
valued and celebrated. TGD people continue to
make vital contributions to the societies in which
they live, although often these are unrecognized.

Disturbingly, many TGD people in the modern
world experience stigma, prejudice, discrimination, harassment, abuse and violence, resulting
in social, economic and legal marginalization,
poor mental and physical health, and even
death—a process that has been characterized as
a stigma-sickness slope (Winter, Diamond et  al.,
2016). Experiences such as these (and the anticipation or fear of encountering such experiences)
leads to what Meyer has described as minority
stress (Meyer, 2003; see also Bockting et  al., 2013
writing specifically about TGD people), and are
associated with poor physical (e.g. Rich et al,
2020) and psychological (e.g., Bränström et  al.,
2022; Scandurra et al., 2017; Shipherd et al., 2019,
Tan et  al., 2021) health outcomes.

Violence against TGD people is a particular
problem. Seen from a global perspective, it is
widespread, diverse in nature (emotional, sexual
and physical, e.g., see Mujugira et  al., 2021), and
involves a range of perpetrators (including State
actors). Statistics on murder, the form of violence
most extreme in its consequences, are alarming.
Worldwide, there were over 4,000 documented
killings between January 2008 and September
2021; a statistic widely regarded as flawed by
under-reporting (TGEU, 2020).

Since the publication of the Standards of Care
Version 7 (SOC-7), there have been dramatic
changes in perspectives on TGD people and their
health care. Mainstream global medicine no longer classifies TGD identities as a mental disorder.
In the Diagnostic and Statistical Manual Version
5 (DSM-5) from the American Psychiatric
Association (APA, 2013), the diagnosis of Gender
Dysphoria focuses on any distress and discomfort
that accompanies being TGD, rather than on the
gender identity itself. A text revision (DSM-5-TR)
was published in 2022. In the International
Classification of Diseases, Version 11 (ICD-11),
the diagnostic manual of the World Health
Organization (WHO, 2019b), the Gender
Incongruence diagnosis is placed in a chapter on
sexual health and focuses on the person’s experienced identity and any need for gender-affirming
treatment that might stem from that identity.
Such developments, involving a depathologization
(or more precisely a de-psychopathologization)
of transgender identities, are fundamentally
important on a number of grounds. In the field
of health care, they may have helped support a
care model that emphasizes patients’ active participation in decision-making about their own
health care, supported by primary health care
professionals (HCPs) (Baleige et  al., 2021). It is
reasonable to suppose these developments may
also promote more socially inclusive policies such
as legislative reform regarding gender recognition
that facilitates a rights-based approach, without
imposing requirements for diagnosis, hormone
therapy and/or surgery. TGD people who have
changed gender markers on key documents enjoy
better mental health (e.g., Bauer et  al., 2015;
Scheim et  al., 2020). A more rights-based
approach in this area may contribute greatly to
the overall health and well-being of TGD people
(Arístegui et  al., 2017).

Previous editions of the SOC have revealed
much of the recorded clinical experience and
knowledge in this area is derived from North
American and Western European sources. They
have focused on gender-affirming health care in
high income countries that enjoy relatively
well-resourced health care systems (including
those with trained mental health providers,
endocrinologists, surgeons and other specialists)
and where services are often funded publicly or
(at least for some patients) through private
insurance.

For many countries, health care provision for
TGD people is aspirational; with resourcing in this
area limited or non-existent, and services often
unavailable, inappropriate, difficult to access and/
or unaffordable. Few if any HCPs (primary or
specialist) may exist. Funding for gender-affirming
health care may be absent, with patients often
bearing the full costs of whatever health care they
access. Health care providers often lack clinical
and/or cultural competence in this area. Training
for work with these patients may be limited (e.g.,
Martins et  al., 2020). For all these reasons and
because of mainstream “Western” medicine’s historical view of TGD people as mentally disordered
(a perspective that has only recently changed),
TGD people have commonly found themselves
disempowered as health care consumers.

Health care providers have found the relevant
literature is largely North American and European,
which present particular challenges for persons
working in health care systems that are especially
poorly resourced. Recent initiatives that often
involve TGD stakeholders as partners are changing this situation somewhat by providing a body
of knowledge about good practice in other
regions, including how to provide effective,
culturally-competent TGD health care in low- and
middle-income countries outside the global north.

Within the field, a wide range of valuable
health care resources have been developed in
recent years. Dahlen et  al (2021) review twelve
international clinical practice guidelines; over half
those reviewed originate from professional bodies
based in North America (e.g., Hembree et  al.,
2017) or Europe (e.g., T’Sjoen et  al., 2020). Three
are from WHO (the most recent being WHO,
2016). Nowadays, there are numerous other
resources, not on Dahlen et al.’s list, that explicitly
draw on expertise from regions outside North
America and Europe. Examples can be found in
Asia and the Pacific (APTN, 2022; Health Policy
Project et al., 2015), the Caribbean (PAHO, 2014),
Thailand, Australia (Telfer et  al., 2020), Aotearoa
New Zealand (Oliphant et  al., 2018), and South
Africa (Tomson et  al., 2021) (see also TRANSIT
(UNDP et  al., 2016)). These resources have commonly been created through the initiatives of or
in partnership with TGD communities locally or
internationally. This partnership approach,
focused on meeting local needs in culturally safe
and competent ways, can also have broad international relevance. Some of these publications
may be of particular value to those planning,
organizing and delivering services in low-income,
low-resource countries. There are likely to be
other resources published in languages other than
English of which we are unaware.

Globally, TGD identities may be associated
with differing conceptual frameworks of sex,
gender, and sexuality and exist in widely diverse
cultural (and sometimes spiritual) contexts and
histories. Considering the complex relationships
between social and cultural factors, the law, and
the demand for and provisions of gender-affirming
health care, the SOC-8 should be interpreted
through a lens that is appropriate for and within
the context of each HCP’s individual practice
while maintaining alignment to the core principles that underscore it (APTN and UNDP,
2012; Health Policy Project et  al., 2015;
PAHO, 2014).

It is within this context and by drawing broadly
on the experiences of TGD people and health
care providers internationally that we consider
the global applicability of SOC-8 within this
chapter. We set out key considerations for HCPs
and conclude by recommending core principles
and practices fundamental to contemporary
health care for TGD people, regardless of where
they live or whether there are resources available
to those who seek to provide such health care.

## Statement 2.1: We recommend health care systems should provide medically necessary gender-affirming health care for transgender and gender diverse people.

Medical necessity is a term common to health
care coverage and insurance policies globally. A
common definition of medical necessity as used
by insurers or insurance companies is “Health
care services that a physician and/or health care
professional, exercising prudent clinical judgment,
would provide to a patient for the purpose of
preventing, evaluating, diagnosing or treating an
illness, injury, disease or its symptoms, and that
are: (a) in accordance with generally accepted
standards of medical practice; (b) clinically
appropriate, in terms of type, frequency, extent,
site and duration, and considered effective for
the patient’s illness, injury, or disease; and (c)
not primarily for the convenience of the patient,
physician, or other health care provider, and not
more costly than an alternative service or
sequence of services at least as likely to produce
equivalent therapeutic or diagnostic results as to
the diagnosis or treatment of that patient’s illness,
injury or disease.” The treating HCP asserts and
documents that a proposed treatment is medically
necessary for treatment of the condition
(American Medical Association, 2016).

Generally, “accepted standards of medical practice” means standards that are based on credible
scientific evidence published in peer-reviewed medical literature generally recognized by the relevant
medical community, designated Medical Specialty
Societies and/or legitimate Medical Colleges’ recommendations, and the views of physicians and/
or HCPs practicing in relevant clinical areas.

Medical necessity is central to payment, subsidy, and/or reimbursement for health care in
parts of the world. The treating HCP may assert
and document that a given treatment is medically
necessary for the prevention or treatment of the
condition. If health policies and practices challenge the medical necessity of a treatment, there
may be an opportunity to appeal to a governmental agency or other entity for an independent
medical review.

It should be recognized gender diversity is
common to all human beings and is not pathological. However, gender incongruence that causes
clinically significant distress and impairment
often requires medically necessary clinical 
interventions. In many countries, medically necessary gender-affirming care is documented by
the treating health professional as treatment for
Gender Incongruence (HA60 in ICD-11; WHO,
2019b) and/or as treatment for Gender Dysphoria
(F64.0 in DSM-5-TR; APA, 2022).

There is strong evidence demonstrating the benefits in quality of life and well-being of
gender-affirming treatments, including endocrine
and surgical procedures, properly indicated and
performed as outlined by the Standards of Care
(Version 8), in TGD people in need of these treatments (e.g., Ainsworth & Spiegel, 2010; Aires
et  al., 2020; Aldridge et  al., 2020; Almazan &
Keuroghlian, 2021; Al-Tamimi et  al., 2019;
Balakrishnan et  al., 2020; Baker et  al., 2021;
Buncamper et  al., 2016; Cardoso da Silva et  al.,
2016; Eftekhar Ardebili, 2020; Javier et  al., 2022;
Lindqvist et  al., 2017; Mullins et  al., 2021; Nobili
et al., 2018; Owen-Smith et al., 2018; Özkan et al.,
2018; T’Sjoen et  al., 2019; van de Grift, Elaut
et al., 2018; White Hughto & Reisner, Poteat et al.,
2016; Wierckx, van Caenegem et  al., 2014; Yang,
Zhao et  al., 2016). Gender-affirming interventions
may also include hair removal/transplant procedures, voice therapy/surgery, counseling, and other
medical procedures required to effectively affirm
an individual’s gender identity and reduce gender
incongruence and dysphoria. Additionally, legal
name and sex or gender change on identity documents can also be beneficial and, in some jurisdictions, are contingent on medical documentation
that patients may call on practitioners to produce.

Gender-affirming interventions are based on
decades of clinical experience and research; therefore, they are not considered experimental, cosmetic, or for the mere convenience of a patient.
They are safe and effective at reducing gender
incongruence and gender dysphoria (e.g., Aires
et  al., 2020; Aldridge et  al., 2020; Al-Tamimi et  al.,
2019; Balakrishnan et  al., 2020; Baker et  al., 2021;
Bertrand et al., 2017; Buncamper et al., 2016; Claes
et al., 2018; Eftekhar Ardebili, 2020; Esmonde et al.,
2019; Javier et  al., 2022; Lindqvist et  al., 2017; Lo
Russo et  al., 2017; Marinkovic & Newfield, 2017;
Mullins et  al., 2021; Nobili et  al., 2018;
Olson-Kennedy, Rosenthal et al., 2018; Özkan et al.,
2018; Poudrier et al., 2019; T’Sjoen et al., 2019; van
de Grift, Elaut et al., 2018; White Hughto & Reisner,
Poteat et  al., 2016; Wierckx, van Caenegem et  al.,
2014; Wolter et  al., 2015; Wolter et  al., 2018).
Consequently, WPATH urges health care systems
to provide these medically necessary treatments and
eliminate any exclusions from their policy documents and medical guidelines that preclude coverage
for any medically necessary procedures or treatments for the health and well-being of TGD individuals. In other words, governments should ensure
health care services for TGD people are established,
extended or enhanced (as appropriate) as elements
in any Universal Health Care, public health, governmentsubsidized systems, or government-regulated private
systems that may exist. Health care systems should
ensure ongoing health care, both routine and specialized, is readily accessible and affordable to all
citizens on an equitable basis.

Medically necessary gender-affirming interventions are discussed in SOC-8. These include but
are not limited to hysterectomy +/- bilateral
salpingo-oophorectomy; bilateral mastectomy,
chest reconstruction or feminizing mammoplasty,
nipple resizing or placement of breast prostheses;
genital reconstruction, for example, phalloplasty
and metoidioplasty, scrotoplasty, and penile and
testicular prostheses, penectomy, orchiectomy,
vaginoplasty, and vulvoplasty; hair removal from
the face, body, and genital areas for gender affirmation or as part of a preoperative preparation
process; gender-affirming facial surgery and body
contouring; voice therapy and/or surgery; as well
as puberty blocking medication and
gender-affirming hormones; counseling or psychotherapeutic treatment as appropriate for the
patient and based on a review of the patient’s
individual circumstances and needs.

Statement 2.2
We recommend health care professionals and
other users of the Standards of Care, Version
8 (SOC-8) apply the recommendations in ways
that meet the needs of local transgender and
gender diverse communities, by providing culturally sensitive care that recognizes the realities of the countries they are practicing in.

TGD people identify in many different ways
worldwide, and those identities exist within a
cultural context. In English speaking countries,
TGD people variously identify as *transsexual*, 
*trans*, *gender nonconforming*, *gender queer* or
*diverse*, *nonbinary*, or indeed *transgender* and/or
*gender diverse*, as well as by other identities;
including (for many identifying inside the gender
binary) *male* or *female*. (e.g., James et  al., 2016;
Strauss et  al., 2017; Veale et  al., 2019).
Elsewhere, identities include but are not limited
to *travesti* (across much of Latin America), *hijra*
(across much of South Asia), *khwaja sira* (in
Pakistan), *achout* (in Myanmar), *maknyah*, *paknyah* (in Malaysia), *waria* (Indonesia) *kathoey*,
*phuying kham phet*, *sao praphet song* (Thailand),
*bakla*, *transpinay*, *transpinoy* (Philippines), *fa’afafine*
(Samoa), *mahu* (French Polynesia, Hawai’i), *leiti*
(Tonga), *fakafifine* (Niue), *pinapinaaine* (Tuvalu
and Kiribati), *vakasalewalewa* (Fiji), *palopa* (Papua
Niugini), *brotherboys* and *sistergirls* (Aboriginal
and Torres Strait Islander people in Australia), and
*akava’ine* (Cook Islands) (e.g., APTN and UNDP,
2012; Health Policy Project et  al., 2015; Kerry,
2014). There are also a large number of two spirit
identities across North America (e.g., nadleehi in
Navajo (Diné) culture) (Sheppard & Mayo, 2013).
The identities to which each of these terms refer
are often culturally complex and may exist in a
spiritual or religious context. Depending on the
cultures and the identities concerned, some may
be regarded as so-called “third genders” lying
beyond the gender binary (e.g., Graham, 2010;
Nanda, 2014; Peletz, 2009). Some TGD identities
are less firmly established than others. In many
places worldwide, the visibility of transgender men
and nonbinary trans masculine identities is relatively recent, with few or no applicable traditional
terms in local languages (Health Policy Project
et  al., 2015). Regardless of where or with whom
HCPs work (including those working with ethnic
minority persons, migrants and refugees), they
need to be aware of the cultural context in which
people have grown up and live as well as the
consequences for health care.

Worldwide the availability, accessibility, acceptability and quality of health care vary greatly,
with resulting inequities within and across countries (OECD, 2019). In some countries, formal
health care systems exist alongside established
traditional and folk health care systems, with
indigenous models of health underpinning the
importance of holistic health care (WHO, 2019a).
HCPs should be aware of the traditions and realities within which health care is available and
provide support that is sensitive to the local
needs and identities of TGD people and provide
them with culturally competent and safe care.

## Statement 2.3: We recommend health care providers understand the impact of social attitudes, laws, economic circumstances, and health systems on the lived experiences of transgender and gender diverse people worldwide.

TGD people’s lived experiences vary greatly,
depending on a range of factors, including social,
cultural (including spiritual), legal, economic and
geographic. When TGD people live in environments that affirm their gender and/or cultural
identities, then these experiences can be very
positive. Families are particularly important in
this regard (e.g., Pariseau et  al., 2019; Yadegarfard
et  al., 2014; Zhou et  al., 2021). However, when
viewed from a global perspective, the circumstances in which TGD people live are often challenging. They are commonly denied widely
accepted rights in international human rights law.
These include rights to education, health and
protection from medical abuses, work and an
adequate standard of living, housing, freedom of
movement and expression, privacy, security, life,
family, freedom from arbitrary deprivation of liberty, fair trial, treatment with humanity while in
detention, and freedom from torture, inhuman
or degrading treatment or punishment
(International Commission of Jurists, 2007, 2017).

It is widely accepted that denial of rights can
impact sexual and gender minority health and
well-being (e.g., OHCHR et  al., 2016; WHO,
2015). We therefore reaffirm here the importance
of the rights listed above for TGD people and
note WPATH’s previous rights advocacy, including through numerous policy documents (e.g.,
WPATH, 2016, 2017, 2019). HCPs can play an
important role in rights advocacy, including the
right to quality gender-affirming health care that
is appropriate, affordable, and accessible.

Across the world, a large number of studies
detail the challenges TGD people face in their
lives, and the impact on their health and
well-being (e.g., Aurat Foundation, 2016; 
Bhattacharya & Ghosh, 2020; Chumakov et  al.,
2021; Coleman et  al., 2018; Heylens, Elaut et  al.,
2014; Human Rights Watch, 2014; James et al,
2016; Lee, Operario et  al., 2020; Luz et  al., 2022;
McNeil et  al., 2012, 2013; Motmans et  al., 2017;
Muller et  al., 2019; Scandurra et  al., 2017; Strauss
et  al., 2019; Suen et  al., 2017; Valashany &
Janghorbani, 2019; Veale et  al., 2019; Wu et  al.,
2017). The research shows TGD people often
experience stigma and prejudice as well as discrimination and harassment, abuse and violence,
or they live in anticipation and fear of such
actions. Social values and attitudes hostile to
TGD people, often communicated to young people in school curricula (e.g., Olivier &
Thurasukam, 2018), are also expressed in family
rejection (e.g., Yadegarfard et  al., 2014), and perpetuated in laws, policies and practices that limit
freedom to express one’s gender identity and sexuality and hinder access to housing, public spaces,
education, employment and services (including
health care). The end result is TGD people are
commonly deprived of a wide range of opportunities available to their cisgender counterparts
and are pushed to the margins of society, without
family supports. To make matters worse, across
much of the world TGD people’s access to legal
gender recognition is restricted or non-existent
(e.g., ILGA World, 2020a; TGEU, 2021; UNDP
and APTN, 2017). In some countries, such barriers nowadays draw on support from
“gender-critical theorists” (as critiqued by e.g.,
Madrigal-Borloz, 2021; Zanghellini, 2020).

Inequities arise from a range of factors, including economic considerations and values underpinning the provision of health care systems,
particularly with regard to the emphasis placed on
public-, private- and self-funding of health care.
Lack of access to appropriate and affordable health
care can lead to a greater reliance on informal
knowledge systems. This includes information
about self-administration of hormones, which, in
many cases, is undertaken without necessary medical monitoring or supervision (e.g., Do et  al.,
2018; Liu et  al., 2020; Rashid et  al., 2022; Reisner
et  al., 2021; Winter & Doussantousse, 2009).

In some parts of the world, large numbers of
transgender women employ silicone as a means
of modifying their bodies, drawing on the services
of silicone “pumpers” and/or attending pumping
“parties”, often within their communities. The
immediate results of silicone pumping contrast
with significant downstream health risks (e.g.,
Aguayo-Romero et  al., 2015; Bertin et  al., 2019;
Regmi et  al., 2021), particularly where industrial
silicone or other injectable substances have been
used and where surgical removal may be difficult.

Finally, sexual health outcomes for TGD people
are poor. HIV prevalence for transgender women
reporting to clinical organizations in metropolitan
areas is approximately 19% worldwide, which is
49 times higher than the background prevalence
rate in the general population (Baral et  al., 2013).
Sexual health outcomes for transgender men are
also problematic (e.g., Mujugira et  al., 2021).

## Statement 2.4: We recommend translations of the SOC focus on cross-cultural, conceptual and literal equivalence to ensure alignment with the core principles that underpin the SOC-8.

Much of the research literature on TGD people
is produced in high-income and English-speaking
countries. Global northern perspectives about
TGD people (including those related to health
care needs and provision) dominate this literature. A May 2021 Scopus database search undertaken by the current authors shows 99% of the
literature on transgender health care comes out
of Europe, North America, Australia, or New
Zealand. Overall, 96% of the literature is in the
English language. TGD people of the Global
South have received relatively little attention in
the English language literature, and the work of
those HCPs who interact with them has often
gone unrecognized and unpublished or has not
been translated into English. Applying resources
produced in the global north risks overlooking
the relevance and nuance of local knowledge,
cultural frameworks and practices, and missed
opportunities to learn from the work of others.

When translating the principles set out in the
SOC, we recommend following best practice
guidelines for language translation to ensure high
quality written resources are produced that are
culturally and linguistically appropriate to the local
situation. It is important translators have knowledge about TGD identities and cultures to check
that literal translations are culturally competent
and safe for local TGD people. It is also important
translation should follow established processes for
quality assurance (Centers for Medicare & Medicaid
Services, 2010; Sprager & Martinez, 2015)

## Statement 2.5: We recommend health care professionals and policymakers always apply the SOC-8 core principles to their work with transgender and gender diverse people to ensure respect for human rights and access to appropriate and competent health care, including:

### General principles {-}

- Be empowering and inclusive. Work to
reduce stigma and facilitate access to
appropriate health care, for all who seek it;
- Respect diversity. Respect all clients and
all gender identities. Do not pathologize
differences in gender identity or expression;
- Respect universal human rights, including
the right to bodily and mental integrity,
autonomy, and self-determination; freedom
from discrimination and the right to the
highest attainable standard of health.

### Principles around developing and implementing appropriate services and accessible health care {-}

- Involve TGD people in the development
and implementation of services;
- Become aware of social, cultural, economic,
and legal factors that might impact the
health (and health care needs) of transgender and gender diverse people, as well as
the willingness and capacity of the person
to access services;
- Provide health care (or refer to knowledgeable colleagues) that affirms gender identities and expressions, including health care
that reduces the distress associated with
gender dysphoria (if this is present);
- Reject approaches that have the goal or
effect of conversion, and avoid providing
any direct or indirect support for such
approaches or services


### Principles around delivering competent services {-}

- Become knowledgeable (get training, where
possible) about the health care needs of
transgender and gender diverse people, including the benefits and risks of
gender-affirming care;
- Match the treatment approach to the specific needs of clients, particularly their
goals for gender identity and expression;
- Focus on promoting health and well-being
rather than solely the reduction of gender dysphoria, which may or may not be
present;
- Commit to harm reduction approaches
where appropriate;
- Enable the full and ongoing informed participation of transgender and gender diverse
people in decisions about their health and
well-being;
- Improve experiences of health services,
including those associated with administrative systems and continuity of care.

### Principles around working towards improved health through wider community approaches {-}

- Put people in touch with communities and
peer support networks;
- Support and advocate for clients within
their families and communities (schools,
workplaces, and other settings) where
appropriate.

We have already cited research detailing the broad
range of challenges TGD people may face; social
economic and legal obstacles, as well those related
to health care access. While overall health care services are diverse across the world (in terms of availability, accessibility, and quality), those services
available to TGD people are often inadequate.
Numerous reports from diverse regions worldwide
show, while TGD people may report positive health
care experiences, many others do not (e.g., Callander
et  al., 2019; Costa, da Rosa Filho et  al., 2018; Do
et  al., 2018; Gourab et  al., 2019; Health Policy
Project et al., 2015; Liu et al., 2020; Motmans et al.,
2017; Muller et al., 2019; PAHO, 2014; Reisner et al.,
2021; Strauss et al., 2017; TGEU, 2017). Mainstream
health care options often do not meet their needs
for general, sexual, or gender-affirming health care.
Standard patient management procedures at clinics
and hospitals often fail to recognize the gender identities of their TGD patients (including where outside
of the binary their patients identify). Patients may
be housed in wards that are gender inappropriate
for them, putting them at risk of sexual harassment.
TGD patients often encounter unsupportive or hostile attitudes from HCPs and ancillary staff and may
even be refused service. Of great concern, HCPs in
some parts of the world are involved in gender identity change efforts of the sort described earlier in
this chapter.

Throughout the world, there are many other
barriers to the provision of gender-affirming
health care. Health care professionals may often
be unwilling to provide the services TGD people
seek. In some countries, there may be laws or
regulations inhibiting or preventing them from
doing so. When general practitioners and other
health care providers do not have access to clear
guidelines in their own language, they may be
deterred from providing services. Even in situations where health care is available, patients may
find it is difficult to access because of distance,
gatekeeping practices, supply and demand issues
that result in long wait lists or cost increases.
Indeed, gender-affirming procedures may not be
incorporated into a universal health care provision or be covered by private insurance, even
though similar procedures may be covered for
cisgender patients.

For all these reasons, many TGD people avoid
formal health care services whenever they can.
Their own communities commonly fill the void,
acting as important resources for their members.
They provide social and emotional support, often
in an otherwise hostile environment. In addition,
they often act as reservoirs of shared information
about available options for health care, including
parallel and informal health care options outside
of (and more accessible and affordable than)
mainstream medicine. As we saw earlier in this
chapter, this often includes sharing of information
about silicone and other injectable substances for
bodily transformation and about hormones that
are self-administered without necessary medical
monitoring or supervision. WHO notes TGD
individuals who self-administer gender-affirming
hormones would benefit from access to
evidence-based information, quality products, and
sterile injection equipment (WHO, 2021). Access
to such information can form part of a broader
harm reduction approach (e.g., Idrus &
Hyman, 2014).

Putting the important core principles outlined
above into practice can improve health care experiences and promote respect for TGD people in
all local contexts. This can occur regardless of
the realities of a health care system (including
the cultural, social, legal, economic context in
which health care is provided), the level of provision available, or the TGD people seeking such
services.
