# Education

This chapter will provide a general review of the
literature related to education in transgender and
gender diverse (TGD) health care.
Recommendations are offered at governmental,
nongovernmental, institutional, and provider levels with the goal of increasing access to competent, compassionate health care. In turn, this
increased access should improve health outcomes
in TGD populations. As this is a novel chapter
in the World Professional Association for
Transgender Health (WPATH) Standards of Care,
the intent is to lay the groundwork for the education area and invite a broader and deeper discussion among educators and health
professionals.

Health professionals involved in transgender
care encompass a broad range of disciplines.
Health professional education varies considerably
by country or region in terms of structure,
licensure, and policy. Published literature on
education in TGD health care is predominantly
from North America, Europe, Australia and New
Zealand. This chapter does not provide a review
of the education literature for each discipline,
the needs specific to each discipline (which can
be found in the relevant chapters), or the needs
specific to each country/region’s health education system. Greater understanding and research
are needed on the intersection of health education systems, licensure, and transgender health
across the world.

On a global level, TGD health education is
imperative if national and international health disparities are to be addressed. Cultural competency
related to TGD communities continues to be lacking. The World Bank Group (2018) reports widespread discrimination, harassment, violence, and
abuse affecting TGD people. They also report
TGD people face the highest rates of violence and
discrimination (World Bank Group, 2018).
Although many higher income countries have
national antidiscrimination laws with gender identity as a protected characteristic, discrimination in
the workplace, in education, and in health care
remains problematic (World Bank Group, 2018).

Across disciplines, curricula at all levels—
undergraduate, graduate, residency, or continuing education—historically have ignored TGD
cultural or clinical education. The Joint
Commission (US) has recommended health care
organizations “provide educational programs and
forums that support the unique needs of the
LGBT community” and “offer educational opportunities that address LGBT health issues” (The
Joint Commission, 2011). However, this is not
enforced.

On an individual level, several questions need
answers. What type of education interventions
can most effectively address transphobia and
lead to long-standing changes in attitudes? What
interventions translate into increasing the number of care providers in this area as well as the
number of TGD people receiving care? Does
clinical exposure increase the confidence of providers over time? What educational interventions
lead to improved health outcomes in the TGD
population and, if so, when and how did these
interventions accomplish this? Although health
professions have begun to incorporate TGD
health into education using a variety of modalities and at varying levels of training, efforts
differ by health profession and are neither systemic nor systematic in nature (e.g., Brennan
et  al., 2012; Chinn, 2013; Eliason et  al., 2010;
Lim et  al., 2015; Obedin-Maliver et  al., 2011;
Rondahl, 2009).

Attaining cultural humility with the full appreciation of the intersectionality of humanity is an
ultimate educational goal. That said, this initial
call for education is focused on building the
foundation in cultural awareness and cultural
competency that is currently weak or non-existent
in much of the world.

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In
some cases, we recognize evidence is limited
and/or services may not be accessible or
desirable.

## Recommendation 4.1: We recommend all personnel working in governmental, nongovernmental, and private agencies receive cultural-knowledge training focused on treating transgender and gender diverse individuals with dignity and respect.

Article 1 of the United Nations Universal
Declaration of Human Rights states, “All human
beings are born free and equal in dignity and
rights” (United Nations, 1948). Only recently has
this fundamental statement included the recognition that TGD rights are human rights (UNOCHR,
2018). Globally, training at all levels about TGD
communities continues to be lacking. As recently
as 2002, only 3% of Fortune 500 companies had
antidiscrimination protection for TGD employees,
and none offered insurance coverage for
gender-affirming health care.
 (Human Rights
Campaign Foundation, 2017). By 2022, 91% of
Fortune 500 companies included gender identity
in US non-discrimination policies, and 66% offered
TGD-inclusive insurance coverage. However, only
72% provide any form of lesbian, gay, bisexual,
transgender and queer/questioning (LGBTQ) cultural knowledge training for their workforce
(Human Rights Campaign Foundation, 2022). This
lack of understanding fosters discrimination across
the board. Taken together, these inconsistencies
negatively affect the health of individuals and communities and exacerbate the health disparities and
inequities they face. In Britain, only 28% of TGD
workers felt the senior leadership were committed
to TGD equality; only 21% of TGD employees
would consider reporting transphobic harassment
in the workplace (Stonewall, 2018). For those who
are openly TGD, 34% were excluded by their
co-workers, 35% were abused by customers, 24%
were denied promotion due to their gender identity, and 11% were fired (Stonewall, 2018). In
southeastern Europe, the World Bank stated there
is widespread discrimination, harassment, violence,
and abuse, and TGD people in that region faced
the highest rates of violence and discrimination
(World Bank Group, 2018). Often the discrimination went unreported with 60% of individuals not
filing a report because of a lack of faith the complaint would be addressed, a fear of further discrimination or ridicule, and a reluctance to be
outed (World Bank Group, 2018). Although many
countries in the region have national antidiscrimination laws with gender identity as a protected
characteristic, discrimination in the workplace, in
education, and in health care remains problematic
(World Bank Group, 2018). It is the responsibility
of the governmental, nongovernmental, and private
agencies in these countries with anti-discrimination
laws to ensure the rights of the TGD population.
They are, therefore, obligated to find ways in
which discrimination and stigma can be decreased.
One of these is through education. Local cultures
that foster anti-TGD attitudes are often a barrier
to this needed education. Although cultural competency trainings have led to equivocal results,
Shepherd (2019) recommends that providing cultural knowledge training that prioritizes local cultural issues and focuses on the values of openness,
non-judgment, and responsiveness may lead to the
desired results. Implementing cultural knowledge
training requires a leadership willing to prioritize
the training and to dedicate the time, money, and
human capital to delivering initial and ongoing
training.

## Recommendation 4.2: We recommend all members of the health care workforce receive cultural-knowledge training focused on treating transgender and gender diverse individuals with dignity during orientation and as part of annual or continuing education.

Across disciplines, curricula at all levels—
undergraduate, graduate, residency, or continuing 
education—historically have ignored TGD cultural or clinical education. Factors contributing
to this lack of inclusion include lack of faculty
knowledge, experience, comfort with the subject
matter, faculty bias, limited space within the
existing curriculum, and lack of guidance on how
to integrate the topics (McDowell & Bower, 2016).
Research into the lack of and the need for such
education does not specifically address TGD
health concerns. Rather, the existing literature
subsumes TGD health education within the
broader discussion of the lack of LGBTQ-focused
cultural and clinical-competency training. As an
example, nursing baccalaureate programs included
only an average of 2.12 hours of instruction on
LGBTQ health (Lim et  al., 2015). A fair assumption is that the amount of time devoted to
TGD-specific health issues constituted only a
fraction of this time.

Within the broader context of LGBTQ competency, the lack of TGD cultural- and
clinical-competency training is a long-known
shortfall of health care education (Aldridge et  al.,
2021). In the US, the Department of Health and
Human Services’ Healthy People 2020, (United
States Department of Health and Human Services
(2013, April 10)), the National Academy of
Medicine (The Institute of Medicine, 2011), and
the Joint Commission (The Joint Commission,
2011) all recognized lack of education negatively
impacts the ability of LGBTQ people, including
TGD individuals, to obtain appropriate, medically
necessary care. The UK’s House of Commons
Women and Equalities Committee found lack of
education contributed to TGD health disparities
in the National Health Service (House of
Commons Women and Equalities Committee,
2015, December 8). The lack of TGD health care
education has been identified in the US
(Obedin-Maliver et  al., 2011), UK (Tollemache
et  al., 2021), South Africa (de Vries et  al., 2020;
Taylor et  al., 2018; Wilson et  al., 2014), Canada
(Bauer et  al., 2014), Australia (Riggs &
Bartholomaeus, 2016), Sweden, Spain, Serbia,
Poland (Burgwal et  al., 2021), and Pakistan
(Martins et  al., 2020) among other countries.

In addition to developing curriculum, Shepherd
(2022) states both clinical and organizational
components are necessary to improve clinical
encounters and consumer satisfaction. On an
organizational level, it must be feasible as well
as locally and practically oriented (Shepherd,
2022). On an individual level, in addition to
knowledge training, health care professionals are
better served employing generic traits that focus
on the values of openness, non-judgment, and
responsiveness (Shepherd, 2018).

## Recommendation 4.3: We recommend institutions involved in the training of health professionals develop competencies and learning objectives for transgender and gender diverse health within each of the competency areas for their specialty.

Each health profession has its own educational
institutions, administrative, and licensing bodies,
which vary by country and specialization within
the profession. No major health professional organizations, educational institutions, or licensing
bodies appear to require training in TGD health.
While these organizations increasingly recommend including LGBTQ intersex health, rarely
do they specify competencies, skills, or learning
objectives for working with TGD people within
their specialty. Published material on health professional education in TGD health is focused
primarily on nursing, medicine, and mental
health and is predominantly from North America,
Europe, Australia, and New Zealand. An increased
understanding of transgender health and medical/
health professional education systems and requirements globally is essential.

Despite the increasing visibility of TGD people,
access to knowledgeable and culturally- competent health professionals remain an overwhelming
need around the world (James et  al., 2016; Lerner
et  al., 2020; Müller, 2017). Lack of knowledgeable
providers is a major barrier to gender-affirming
care for transgender persons (Puckett et  al., 2018;
Safer et  al., 2016) and contributes to large health
disparities (Giffort & Underman, 2016; Reisman
et  al., 2019). The lack of adequate professional
education in TGD health is a global problem (Do
& Nguyen, 2020; Martins et  al., 2020;
Parameshwaran et  al., 2017) that occurs at all
levels of training (Dubin et  al., 2018) and traverses health disciplines (Glick et  al., 2020;
Gunjawate et  al., 2020; Johnson & Federman,
2014) and medical specialties (Fung et  al., 2020;
Korpaisarn and Safer, 2018).

Challenges remain as studies to date have
small sample sizes, involve one-time training,
include multiple disciplines at multiple career
levels, focus on short-term outcomes, and often
cover all LGBTQI topics rather than
TGD-specific ones that are usually acquired
post-licensure and are not the focus of most
currently studied educational interventions
(Dubin et  al., 2018).

To successfully implement the recommendations, institutions may need to consider
developing 1) systemic and systematic approaches
to developing and implementing competencies
for each health discipline across the professional
lifespan; 2) standardized assessments for learners,
with input from the TGD community; and 3)
allotment of curricular resources, including
trained faculty, as well as time in accordance with
clear, consensual learning objectives (Dubin et  al.,
2018; Pratt-Chapman, 2020). In addition, evaluations of these interventions should not only
focus on outcomes but also strive to understand
how, when, and why these outcomes are occurring (Allen et  al., 2021).

