# Nonbinary
Nonbinary is used as an umbrella term referring
to individuals who experience their gender as
outside of the gender binary. The term nonbinary
is predominantly but not exclusively associated
with global north contexts and may sometimes
be used to describe indigenous and non-Western
genders. The term nonbinary includes people
whose genders are comprised of more than one
gender identity simultaneously or at different
times (e.g., bigender), who do not have a gender
identity or have a neutral gender identity (e.g.,
agender or neutrois), have gender identities that
encompass or blend elements of other genders
(e.g., polygender, demiboy, demigirl), and/or who
have a gender that changes over time (e.g., genderfluid) (Kuper et al., 2014; Richards et al., 2016;
Richards et  al., 2017; Vincent, 2019). Nonbinary
people may identify to varying degrees with
binary-associated genders, e.g., nonbinary man/
woman, or with multiple gender terms, e.g., nonbinary and genderfluid (James et  al., 2016; Kuper
et  al., 2012). Nonbinary also functions as a gender identity in its own right (Vincent, 2020). It
is important to acknowledge this is not an
exhaustive list, the same identities can have different meanings for different people, and the use
of terms can vary over time and by location.

Genderqueer, first used in the 1990s, is an identity category somewhat older than nonbinary—
which first emerged in approximately the late 2000s
(Nestle et  al., 2002; Wilchins, 1995). Genderqueer
may sometimes be used synonymously with nonbinary or may communicate a specific consciously
politicized dimension to a person’s gender. While
transgender is used in many cultural contexts as
an umbrella term inclusive of nonbinary people,
not all nonbinary people consider themselves to
be transgender for a range of reasons, including
because they consider being transgender to be
exclusively within the gender binary or because
they do not feel “trans enough” to describe themselves as transgender (Garrison, 2018). Some nonbinary people are unsure or ambivalent about
whether they would describe themselves as transgender (Darwin, 2020; Vincent, 2019).

In the context of the English language, nonbinary people may use the pronouns they/them/
theirs, or neopronouns which include e/em/eir,
ze/zir/hir, er/ers/erself among others (Moser &
Devereux, 2019; Vincent, 2018). Some nonbinary
people use a combination of pronouns (either
deliberately mixing usage, allowing free choice,
or changing with social context), or prefer to
avoid gendered pronouns entirely, instead using
their name. Additionally, some nonbinary people
use she/her/hers, or he/him/his, sometimes or
exclusively, whilst in some regions in the world
descriptive language for nonbinary people does
not (yet) exist. In contexts outside of English, a
wide range of culturally specific linguistic adaptations and evolutions can be observed (Attig,
2022; Kirey-Sitnikova, 2021; Zimman, 2020). Also
of note, some languages use one pronoun that is
not associated with sex or gender while others
gender all nouns. These variations in language
are likely to influence nonbinary people’s experience of gender and how they interact with others.

Recent studies suggest nonbinary people comprise roughly 25% to over 50% of the larger
transgender population, with samples of youth
reporting the highest percentage of nonbinary
people (Burgwal et  al., 2019; James et  al., 2016;
Watson, 2020). In recent studies of transgender
adults, nonbinary people tend to be younger than
transgender men and transgender women and in
studies of both youth and adults, nonbinary people are more likely to have been assigned female
at birth (AFAB). However, these findings should
be interpreted with caution as there are likely a
number of complex, sociocultural factors influencing the quality, representativeness, and accuracy of this data (Burgwal et  al., 2019; James
et al., 2016; Watson, 2020; Wilson & Meyer, 2021)
(see also Chapter 3—Population Estimates).

## Understanding gender identities and gender expressions as a non-linear spectrum {-}

Nonbinary genders have long been recognized
historically and cross-culturally (Herdt, 1994;
McNabb, 2017; Vincent & Manzano, 2017). Many
gender identity categories are culturally specific
and cannot be easily translated from their context, either linguistically or in relation to the
Western paradigm of gender. Historical settler
colonial interactions with indigenous people with 
non-Western genders remain highly relevant as
cultural erasure and the intersections of racism
and cisnormativity may detrimentally inform the
social determinants of health of indigenous gender diverse people. From the 1950s, gender was
used to reference the socially constructed categorization of behaviors, activities, appearance, etc.
in relation to a binary model of male/man/masculine, and female/woman/feminine within contemporary Western contexts. However, gender
now has a wider range of possible meanings,
appreciating interrelated yet distinguishable concepts, including gendered biology (sex), gender
roles, gender expression, and gender identity
(Vincent, 2020). Aspects of gender expression
that might traditionally be understood culturally
as “masculine”, “feminine”, or “androgynous” may
be legitimately expressed among people of any
and all gender identities, whether nonbinary or
not. For example, a nonbinary individual presenting in a feminine manner cannot be taken
to imply they will necessarily later identify as a
woman or access interventions associated with
transgender women, such as vaginoplasty. A person’s gender nonconformity in relation to cultural
expectations should neither be viewed as a cause
for concern nor assumed to be indicative of clinical complexity—for example, a nonbinary person
assigned male at birth (AMAB) wearing
feminine-coded clothing, using she/her pronouns,
but keeping a masculine-coded first name.

Modeling gender as a spectrum offers greater
nuance than a binary model. However, there
remain significant limitations in a linear spectrum
model that can lead to uncritical generalizations
about gender. For example, while it is intuitive
to position the “binary options” (man/male,
woman/female) at either end of such a continuum, doing so situates masculinity as oppositional
to femininity, failing to accommodate gender neutrality, the expression of masculinity and femininity simultaneously, and genderqueer or
non-Western concepts of gender. It is essential
HCPs do not view nonbinary genders as “partial”
articulations of transgender manhood (in nonbinary people AFAB) or transgender womanhood
(in nonbinary people AMAB), or definitively as
“somewhere along the spectrum of masculinity/
femininity”; some nonbinary individuals consider
themselves outside male/female dichotomization
altogether. A non-linear spectrum indicates differences of gender expression, identity, or needs
around gender affirmation between clients should
not be compared for the purposes of situating
them along a linear spectrum. Additionally, the
interpretation of gender expression is subjective
and culturally defined, and what may be experienced or viewed as highly feminine by one person
may not be viewed as such by another (Vincent,
2020). HCPs benefit from avoiding assumptions
about how each client conceptualizes their gender
and by being prepared to be led by a given client’s
personal understanding of gender as it relates to
the client’s gender identity, expression, and any
need for medical care.

The gender development process experienced
by all transgender and gender diverse (TGD)
people regardless of their relationship to a gender
binary appear to share similar themes (e.g.,
awareness, exploration, meaning making, integration), but the timing, progression, and personal
experiences associated with each of these processes vary both within and across groups of
transgender and nonbinary people (Kuper, Wright
et al., 2018; Kuper, Lindley et  al., 2019; Tatum
et al., 2020). Sociocultural and intersectional perspectives can be helpful at contextualizing gender
development and social transition, including how
individual experiences are shaped by the social
and cultural context and how they interact with
additional domains of identity and personal
experience.

## The need for access to gender-affirming care {-}

Some nonbinary people seek gender-affirming
care to alleviate gender dysphoria or incongruence and increase body satisfaction through medically necessary interventions (see medically
necessary statement in Chapter 2—Global
Applicability, Statement 2.1). Some nonbinary
people may feel a certain treatment is necessary
for them—see also Chapter 5—Assessment of
Adults (Beek et  al., 2015; Jones et  al., 2019;
Köhler et al., 2018), whilst others do not (Burgwal
& Motmans, 2021; Nieder, Eyssel et  al., 2020),
and the proportion of nonbinary people who seek
gender-affirming care and the specific goals of 
that care, remains unclear. It is the role of the
health care professional to provide information
about existing medical options (and their availability) that might help alleviate gender dysphoria
or incongruence and increase body satisfaction
without making assumptions about which treatment options may best fit each individual person.

Motivations for accessing (or not accessing)
gender-affirming medical interventions, including
hormone treatment, surgeries, or both are heterogeneous and potentially complex (Burgwal &
Motmans, 2021; Vincent, 2019, 2020) and should
be explored collaboratively before making decisions about physical interventions. The need of
an individual to access gender-affirming medical
procedures cannot be predicted by their gender
role, expression, or identity. For example, some
transgender women have no need of vaginoplasty,
while some nonbinary individuals AMAB may
need and benefit from that same intervention.
Further, nonbinary people seeking gender-affirming
care associated closely with a transition pathway
from their assigned sex/gender to the other
binarily-recognized category (i.e., estrogen therapy
and vaginoplasty for someone AMAB) does not
undermine the validity of their nonbinary identity.

While barriers to care remain widespread for
many transgender people, nonbinary people
appear to experience particularly high rates of
difficulty accessing both mental health and
gender-affirming medical care (Clark et  al., 2018;
James, 2016). Many nonbinary people report having experiences with health care professionals
who were not affirming of their nonbinary gender, including experiences where health care professionals convey beliefs that their gender is not
valid, or they are fundamentally more difficult
to provide care for (Valentine, 2016; Vincent,
2020). Nonbinary people may face provider
assumptions that they do not need or want
gender-affirming treatment (Kcomt et  al., 2020;
Vincent, 2020) and have described experiencing
pressure to present themselves as transgender
men or transgender women (within a binary
framework of gender) in order to access treatment (Bradford et  al., 2019; Taylor et  al., 2019).
At times, nonbinary people find themselves educating the provider from whom they are seeking
services despite the inappropriateness of providers
relying primarily on their patients for education
(Kcomt et  al., 2020). In comparison to transgender men and transgender women, Burgwal and
Motmans (2021) found that nonbinary people
experienced more fear of prejudice from health
care providers, less confidence in the services
provided, and greater difficulty knowing where
to go to for care. Studies in both Europe and US
have shown that nonbinary individuals tend to
delay care more often than binary transgender
men or transgender women, with fear of insensitive or incompetent treatment being the most
cited reason (Burgwal & Motmans, 2021; Grant
et  al., 2011). Nonbinary people also appear less
likely to disclose their gender identity to their
health care providers than other transgender people (Kcomt et  al., 2020).

## The need for an appropriate level of support {-}

Providing gender-affirming care to nonbinary people goes beyond the provision of specific genderaffirming interventions such as hormone therapy
or surgery and involves supporting the overall
health and development of nonbinary people.
Minority stress models have been adapted to conceptualize how the gender-related stressors experienced by transgender people are associated with
physical and mental health disparities (Delozier
et  al., 2020; Testa et  al., 2017). Nonbinary people
appear to experience minority stressors that are
both similar to and unique from those experienced
by transgender men and transgender women.
Johnson (2020) reported that experiences of invalidation are particularly high among nonbinary
people, e.g., statements or actions conveying a
belief that nonbinary identities are not “real” or
are the result of a “fad” or “phase,” and nonbinary
people appear less likely than transgender men
and transgender women to have their correct pronouns used by others. Similarly, nonbinary people
have described feeling “invisible” to others (Conlin,
2019; Taylor, 2018) and one study found that nonbinary youth reported lower levels of self-esteem
in comparison to young transgender men and
transgender women (Thorne, Witcomb et al., 2019).

While many TGD people report experiences
of discrimination, victimization, and interpersonal
rejection (James, 2016) including bullying within 
samples of youth (Human Rights Campaign,
2018; Witcomb et  al., 2019), the prevalence of
these experiences may vary across groups and
appears influenced by additional intersecting
characteristics. For example, Newcomb (2020)
found transgender women and nonbinary youth
AMAB experienced higher levels of victimization
than transgender men and nonbinary youth
AFAB, with nonbinary youth AMAB reporting
the highest levels of traumatic stress. In a second
study, Poquiz (2021) found transgender men and
transgender women experienced higher levels of
discrimination than nonbinary people. This intersectional complexity is also likely contributing to
the variability in findings from studies comparing
the physical and mental health of nonbinary and
transgender men and transgender women, with
some studies indicating more physical and mental
health concerns among nonbinary people, some
reporting less concerns, and some reporting no
difference between groups (Scandurra, 2019).

Given nonbinary identity narratives may be less
widely available than more binary-oriented identity narratives, nonbinary people may have less
resources available to explore and articulate their
gender-related sense of self. For example, this
might include access to community spaces and
interpersonal relationships where nonbinary identity can be explored, or access to language and
concepts that allow more nuanced consideration
of nonbinary experiences (Bradford et  al., 2018;
Fiani & Han, 2019; Galupo et  al., 2019). Clinical
guidance is now developing to assist providers in
adapting gender-affirming therapeutic care to
meet these unique experiences of nonbinary people (Matsuno, 2019; Rider, Vencill et  al., 2019).

## Gender-affirming medical interventions for nonbinary people {-}

In contexts where a particular medical intervention does not have established precedent, it is
important that before the intervention is considered, the individual is provided with an overview
of the available information, including recognition
of potential knowledge limits. It is equally important to undertake and document a comprehensive
discussion of the physical changes needed and
the potential limitations in achieving those
attributes, as well as the implication that any
given intervention may or may not enhance an
individual’s ability to express their gender.

With regards to estrogen therapy for nonbinary
people AMAB, it is important to note the possibility of breast growth cannot be avoided (Seal,
2017). Although the extent of growth is highly
variable, this should be made clear if a nonbinary
person seeks some of the other changes associated
with estrogen therapy (such as softening of skin
and reduction in facial hair growth) but does not
want or is ambivalent about breast growth.
Likewise, for nonbinary people AFAB who may
wish to access testosterone to acquire some changes
but not others, it should be recognized that if
facial hair development is needed, genital growth
is inevitable (Seal, 2017). The time frame for taking testosterone means these changes are likely
also to be accompanied by an irreversible vocal
pitch drop, although the extent of each is individual (Vincent, 2019; Ziegler et  al., 2018). A vocal
pitch drop without the development of body hair
is another such challenge. For some nonbinary
people, hair removal is a very important part of
their gender affirmation (Cocchetti, Ristori,
Romani et  al., 2020).

If hormonal therapy is discontinued and gonads
are retained, many physical changes will revert
to pre-hormone therapy status as gonadal hormones once again take effect, including reversal
of amenorrhea and body hair development in
nonbinary people AFAB and reduction in muscular definition and erectile dysfunction in nonbinary people AMAB. Other changes will be
permanent such as “male-pattern” baldness, genital growth, and facial hair growth in nonbinary
people AFAB or breast development in nonbinary
people AMAB (Hembree et  al., 2017). These will
require further interventions to reverse, such as
electrolysis or mastectomy and are sometimes
described as “partially reversible” (Coleman et  al.,
2012). As the implications of using low-dose hormone therapy are not documented in this patient
population, it is important to consider monitoring
for cardiovascular risk and bone health if low-dose
hormone therapy is used. For more detailed
information see Chapter 12—Hormone Therapy.

If neither testosterone nor estrogen expression is
needed, inhibition of estrogen and/or testosterone 
production is possible. The implications of this with
regards to increased cardiovascular risk, reduced
bone mineralization, and risk of depression should
be discussed and measures taken to mitigate risk
(Brett et  al., 2007; Vale et  al., 2010; Wassersug &
Johnson, 2007). For more information see also
Chapter 9—Eunuchs and Chapter 12—Hormone
Therapy. Exploration of medical and/or social transition independently of each other and options to
explore hormones, surgery, or both independently
of each other should be available to everyone,
whether the person is a transgender man, transgender woman, or a nonbinary person.
All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable.

## Statement 8.1 We recommend health care professionals provide nonbinary people with individualized assessment and treatment that affirms their nonbinary experiences of gender. {-}

An individualized assessment with a nonbinary
person starts with an understanding of how they
experience their own gender and how this impacts
their goals for the care they are seeking. How
individuals conceptualize their gender-related
experiences are likely to vary across groups and
cultures and may incorporate experiences associated with other intersecting aspects of identity
(e.g., age, sexuality, race, ethnicity, socioeconomic
status, disability status) (Kuper et  al., 2014;
Subramanian et  al., 2016).

HCPs should avoid making a priori assumptions
about any client’s gender identity, expression, or
needs for care. They should also be mindful that
a client’s nonbinary experience of gender may or
may not be relevant to the assessment and
treatment-related goals. The extent to which the
client’s gender is relevant to their treatment goals
should determine the level of detail at which their
gender identity is explored. For example, when
seeking care for a presenting concern wholly unrelated to gender, simply determining the correct
name and pronouns may be sufficient (Knutson
et al., 2019). When addressing a concern for which
current or past hormonal or surgical status is relevant, more detail may be needed, even if the
concern is not specifically gender-related.

Clinical settings need to be welcoming, reflective of the diversity of genders, and affirm the
experiences of gender of nonbinary people to be
culturally competent. Ensuring clinic and provider information (e.g., websites), forms (e.g.,
intake surveys), and other materials are inclusive
of nonbinary identities and experiences conveys
that nonbinary people are welcome and recognized (Hagen & Galupo, 2014). Using free text
fields for gender identity and pronouns is more
inclusive than using a list of response options.
Ensuring privacy at the reception desk, setting
up alternatives for listing legal names in digital
databases (in cultural contexts where this is necessary), installing gender-neutral toilets, and setting up alternatives to calling out the legal name
in the waiting room are additional examples of
transgender and gender diverse (TGD) cultural
competency (Burgwal et  al., 2021). In care settings, it is important preferences for names, pronouns, and other gender-related terms are asked
and used both initially and on a regular basis as
they may vary over time and circumstance.

HCPs are encouraged to adopt an approach
that focuses on strengths and resilience.
Increasingly, critiques are emerging regarding
HCPs over-focus on gender-related distress as it
is also important to consider experiences of
increased comfort, joy, and self-fulfilment that
can result from self-affirmation and access to care
(Ashley, 2019a; Benestad, 2010). In addition to
utilizing diagnoses when/where required to facilitate access to care, HCPs are encouraged to collaboratively explore with clients this broader
range of potential gender-related experiences and
how they may fit with treatment options
(Motmans et  al., 2019). For all TGD people, resiliency factors such as supportive relationships,
participation in communities that include similar
others, and identity pride are essential to consider
as they are associated with a range of positive
health outcomes (Bowling et  al., 2019; Budge,
2015; Johns et  al., 2018).

Awareness of the limitations that exist in the
tools providers have historically used to assess
transgender people’s experience of dysphoria is
important as they may be particularly pronounced
for many nonbinary people. Most gender-related
measures assume clients experience their gender
in a binary way, among other concerns (e.g.,
Recalled Gender Identity Scale, Utrecht Gender
Dysphoria Scale). While several newer measures
have been developed in an attempt to better capture the experiences of nonbinary people (McGuire
et  al., 2018; McGuire et  al., 2020), open-ended
discussion is likely to provide a deeper and more
accurate understanding of each individual’s unique
experiences of dysphoria and their associated care
needs. Similarly, while more recent iterations of
diagnostic categories (i.e., “gender dysphoria” in
the DSM 5 and “gender incongruence” in ICD-11)
were intended to be inclusive of people with nonbinary experiences of gender, they may not adequately capture the full diversity and scope of
experiences of gender-related distress, particularly
for nonbinary people. In addition to distress associated with aspects of one’s physical body and
presentation (including features that may be existing or absent), distress may arise from how one
experiences their own gender, how one’s gender
is perceived within social situations, and from
experiences of minority stress associated with one’s
gender (Winters & Ehrbar, 2010). Nonbinary peoples’ experiences in each of these areas may or
may not be similar to those of transgender men
or women.

A person-centered approach for affirming care
includes specific discussion of how different
interventions may or may not shift the client’s
comfort with their own experience of gender, and
how their gender is perceived by others.
Nonbinary people can face challenges in reconciling their personal identities with the limits of
the medical treatments available and can also
encounter confusion and intolerance from society
regarding their gender presentations (Taylor et al.,
2019). Emerging research suggests the medical
treatment needs of nonbinary people are particularly diverse, with some reporting needs for
treatments that have typically been associated
with transition trajectories historically associated
with transgender men and women and some
reporting alternative approaches (e.g., low dose
hormone therapy, surgery without hormone therapy), some reporting a lack of interest in medical
treatment, and some reporting feeling unsure
about their needs (Burgwal & Motmans, 2021;
James et  al., 2016). Conceptualizing assessment
as an ongoing process is particularly important
given gender-related experiences and associated
needs may shift throughout the lifespan. Given
the ongoing evolution in treatment options and
knowledge of treatment effects, particularly for
nonbinary people, clients will benefit from providers who regularly seek up-to-date knowledge
and convey these updates to their clients.

## Statement 8.2: We recommend health care professionals consider medical interventions (hormonal treatment or surgery) for nonbinary people in the absence of “social gender transition.” {-}

Previous requirements for accessing hormonal
treatment and surgery, such as “living in a gender
role that is congruent with one’s gender identity,”
do not reflect the lived experiences of many TGD
people (Coleman et al., 2012). Due to the entrenched
nature of the gender binary in most contemporary
Western cultures, one can typically only be understood by others as a man or woman within most
settings (Butler, 1993). Hence, the visibility and
understanding of nonbinary embodiments and
expressions is limited. This is due to gendered cues 
being almost always understood in reference to a
gender binary (Butler, 1993). Presently, it can be
difficult for nonbinary people to be reliably recognized as their gender via visual cues associated with
their gender expression (e.g., clothing, hair).
However, androgyny or gender nonconformity may
be communicated by the mixing or combining of
cultural markers with traditionally masculine or
feminine connotations. Because there is no commonly recognized “nonbinary category” within most
contemporary Western, global north cultural contexts, nonbinary visibility often necessitates explicit
sharing of one’s gender with others or the use of
cues that may be interpreted as gender nonconformity (but not necessarily nonbinary).

For these reasons, framing access to medical
care in the context of someone experiencing a
“social gender transition” where they are “living
in a gender role that is congruent with one’s gender identity” is not in line with the way many
TGD people understand themselves and their
personal transition process. For some, “living in
a gender role that is congruent with one’s gender
identity” does not involve changes in name, pronouns, or gender expression even as medical
intervention may be necessary. Even if a person
is able to live in ways that are congruent with
their gender identity, it may be difficult for an
outside observer to assess this without learning
directly from that person how they understand
their own experience in this regard. Expectation
of “social gender transition” may be unhelpful
when considering eligibility for gender- affirming
care, such as hormones and surgery, and rigid
expectations of what a “social gender role transition” “should” look like can be a barrier to care
for nonbinary people. There is no logical requirement gender-affirming medical interventions can
only be done once a person legally changes their
name, changes the gender marker on their identity documents, or wears or refrains from wearing
particular items of clothing. Nonbinary people
may struggle to access recognition of their genders on formal documentation, which may negatively affect their mental health or well-being
(Goetz & Arcomano, 2021). TGD people may
benefit from specific support in accessing (or
retaining) their gender marker of preference. A
requirement that someone disclose their gender
identity in all circles of their lives (family, work,
school, etc.) in order to access medical care may
not be consistent with their goals and can place
them at risk if it is not safe to do so.

## Statement 8.3: We recommend health care professionals consider gender-affirming surgical interventions in the absence of hormonal treatment unless hormone therapy is required to achieve the desired surgical result. {-}

The trajectory of “hormones before surgery” is
an option across a range of surgical interventions.
Some nonbinary people will seek gender-affirming
surgical treatment to alleviate gender incongruence
and increase body satisfaction (Beek et  al., 2015;
Burgwal & Motmans, 2021; Jones et  al., 2019;
Koehler et  al., 2018), but do not want hormonal
treatment or are unable to undergo hormonal therapy due to other medical reasons (Nieder, Eyssel
et  al., 2020). Currently, it is unknown for which
proportion of nonbinary people these options apply.
Perhaps the surgery which has some specific
association with nonbinary people (rather than
sought by transgender men or undergone by
some cisgender women) is mastectomy in nonbinary people AFAB who have not taken testosterone—although testosterone is not a requirement
for this type of surgery—and some nonbinary
people AFAB may need breast reduction
(McTernan et  al., 2020). An example of a surgery
for which at least a period of hormone therapy
may be necessary is metoidioplasty that enhances
the enlarged clitoris produced by testosterone
therapy. See Chapter 13—Surgery and
Postoperative Care for more detail on whether
hormone therapy is necessary for various surgeries. Procedures addressing the internal reproductive system include hysterectomy, unilateral or
bilateral salpingo-oophorectomy, and vaginectomy.
Hormone therapy is not required for any of these
procedures, but hormone replacement therapy
(either with estrogens, testosterone, or both) is
advisable in those individuals undergoing a total
gonadectomy to prevent adverse effects on their
cardiovascular and musculoskeletal systems
(Hembree et  al., 2017; Seal, 2017). For phalloplasty, while there is no surgical requirement
per se for a minimum period of testosterone 
treatment, virilization (or the absence of virilization) of the clitoris and labia minora may impact
the choice of surgical technique and influence
surgical options. For more information see
Chapter 13—Surgery and Postoperative Care.

Nonbinary AMAB clients should be informed
commencing estrogen therapy post-surgically with
no prior history of estrogen therapy may influence
(perhaps adversely) the surgical result (Kanhai, Hage,
Asscheman et  al., 1999; Kanhai, Hage, Karim et  al.,
1999). Nonbinary people AMAB requesting a bilateral orchiedectomy do not require estrogen therapy
to achieve a better outcome (Hembree et  al., 2017).
In these contexts, it is good practice to inform clients of the risks and benefits of hormone replacement therapy (estrogens, testosterone, or both) in
preventing adverse effects on the cardiovascular and
musculoskeletal system as well as alternative treatment options, such as calcium plus vitamin D supplementation to prevent osteoporosis (Hembree
et  al., 2017; Seal, 2017; Weaver et  al., 2016). See
also Chapter 9—Eunuchs for those who choose to
forgo hormone replacement therapy. In the case of
vaginoplasty, individuals should be advised lack of
testosterone-blocking therapy may cause postoperative hair growth in the vagina when hair-bearing
skin graft and flaps have been used (Giltay &
Gooren, 2000).

Additional surgical requests for nonbinary people AMAB include penile-preserving vaginoplasty,
vaginoplasty with preservation of the testicle(s),
and procedures resulting in an absence of external primary sexual characteristics (i.e., penectomy, scrotectomy, orchiectomy, etc.). The surgeon
and individual seeking treatment are advised to
engage in discussions so as to understand the
individual’s goals and expectations as well as the
benefits and limitations of the intended (or
requested) procedure, to make decisions on an
individualized basis and collaborate with other
health care providers who are involved (if any).

## Statement 8.4: We recommend health care professionals provide information to nonbinary people about the effects of hormonal therapies/surgery on future fertility and discuss the options for fertility preservation prior to starting hormonal treatment or undergoing surgery. {-}

All nonbinary individuals who seek
gender-affirming hormonal therapies should be
offered information and guidance about fertility
options (Hembree et  al., 2017; De Roo et  al.,
2016; Defreyne, Elaut et  al., 2020; Defreyne, van
Schuvlenbergh et  al., 2020; Nahata et  al., 2017;
Quinn et  al., 2021). It is important to discuss
the potential impact of hormone therapy on fertility prior to initiation. This discussion should
include fertility preservation options, the extent
to which fertility may or may not be regained
if hormone therapy is ceased, and the fact that
hormone therapy per se is not birth control. For
more information see Chapter 16—
Reproductive Health.

Recent studies suggest that nonbinary individuals are less likely to access care and make their
needs for potential interventions heard (Beek
et  al., 2015; Taylor et  al., 2019). As such, it stands
to reason that any gender diverse individual
should be offered information on current options
and techniques for fertility preservation, ideally
prior to commencing hormonal treatment as the
quality of the sperm or eggs may be impacted
by exposure to hormones (Hamada et  al., 2015;
Payer et  al., 1979). However, this should in no
way preclude making inquiries and seeking more
information at a later time, as there is evidence
that fertility is still possible for individuals taking
estrogen and testosterone (Light et  al., 2014). A
decision by a nonbinary or gender diverse person
that fertility preservation or counseling is not
needed should not be used as a basis for denying
or delaying access to hormonal treatment.

