# Eunuchs

Among the many people who benefit from
gender-affirming medical care, those who identify
as eunuchs are among the least visible. The 8th
version of the Standards of Care (SOC) includes
a discussion of eunuch individuals because of
their unique presentation and their need for medically necessary gender-affirming care (see
Chapter 2—Global Applicability, Statement 2.1).

Eunuch individuals are those assigned male at
birth (AMAB) and wish to eliminate masculine
physical features, masculine genitals, or genital
functioning. They also include those whose testicles have been surgically removed or rendered
nonfunctional by chemical or physical means and
who identify as eunuch. This identity-based definition for those who embrace the term eunuch
does not include others, such as men who have
been treated for advanced prostate cancer and
reject the designation of eunuch. We focus here
on those who identify as eunuchs as part of the
gender diverse umbrella.

As with other gender diverse individuals,
eunuchs may also seek castration to better align
their bodies with their gender identity. As such,
eunuch individuals are gender nonconforming
individuals who have needs requiring medically
necessary gender-affirming care (Brett et  al.,
2007; Johnson et  al., 2007; Roberts et  al., 2008).

Eunuch individuals identify their gender identities in various ways. Many eunuch individuals
see their status as eunuch as their distinct gender
identity with no other gender or transgender
affiliation. The focus of this chapter is on the
treatment and care for those who identify as
eunuchs. Health care professionals (HCPs) will
encounter eunuchs requesting hormonal interventions, castration, or both to become eunuchs.
These individuals may also benefit from a eunuch
community because of the identification—with
or without actual castration.

While there is a 4000-year history of eunuchs
in society, the greatest wealth of information
about contemporary eunuch-identified people is
found within the large online peer-support community that congregates on sites such as the
Eunuch Archive (www.eunuch.org), which was
established in 1998. The moderators of this site
attempt to maintain both medical and historical
accuracy in its discussion forums, although there
is certainly misinformation as well. According to
the website, as of January 2022, there have been
over 130,000 registered members from various
parts of the world and frequently over 90% of
those reading the site are “guests” rather than
members. The website lists over 23,000 threads
and nearly 220,000 posts. For example, two threads
giving instructions for self-castration by injection
of different toxins directly into the testicles have
about 2,500 posts each, and each has been read
well over one million times. Beginning in 2001,
there have been 20 annual international gatherings
of the Eunuch Archive community in Minneapolis
in addition to many regional gatherings elsewhere.
While the topic of castration is of interest to the
great majority of people who participate in the
discussions, it is a minority of the membership
who seriously seek or have undergone castration.
Many former Eunuch Archive members have
achieved their goals and no longer participate.

Because of misconceptions and prejudice about
historic eunuchs, the invisibility of contemporary
eunuchs, and the social stigma that affects all
gender and sexual minorities, few eunuch individuals come out publicly as eunuch and many
will tell no one and will share only with
like-minded people in an online community or
are known as such only to close family and
friends (Wassersug & Lieberman, 2010). The stereotypes of eunuchs are often highly negative
(Lieberman 2018), and eunuchs may suffer the
same minority stress as other stigmatized groups
(Wassersug & Lieberman, 2010). Research into
minority stress affecting gender diverse people
should therefore include eunuchs.

The current set of recommendations is directed
at professionals working with individuals who
identify as eunuchs (Johnson & Wassersug, 2016;
Vale et  al., 2010) requesting medically necessary
gender-affirming medical and/or surgical treatments (GAMSTs). Although not a specific diagnostic category in the ICD or DSM, eunuch is a
useful construct as it speaks to the specifics of
eunuch experience while also connecting it to
the experience of gender incongruence more
broadly. Eunuch individuals will present themselves clinically in various ways. They wish for 
a body that is compatible with their eunuch identity—a body that does not have fully functional
male genitalia. Some other eunuch individuals
feel acute discomfort with their male genitals and
need to have them removed to feel comfortable
in their bodies (Johnson et  al., 2007; Roberts
et  al., 2008). Others are indifferent to having
male external genitalia as long as they are only
physically present and do not function to produce
androgens and male secondary sexual features
(Brett et al., 2007). Hormonal means may be used
to suppress the production of androgens, although
orchiectomy provides a permanent solution for
those not wishing genital functioning (Wibowo
et  al., 2016). Some eunuch individuals desire
lower testosterone levels achieved with orchiectomy, but many will elect some form of hormone
replacement to prevent adverse effects associated
with hypogonadism. Most who elect hormone
therapy choose either a full or partial replacement
dose of testosterone. A smaller number elect
estrogen.

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable.

## Statement 9.1: We recommend health care professionals and other users of the Standards of Care, Version 8 guidelines should apply the recommendations in ways that meet the needs of eunuch individuals. {-}

Eunuch individuals are part of the population
of gender diverse people who experience gender
incongruence and may also seek gender-affirming
care. Like other transgender and gender diverse
(TGD) individuals, eunuchs require access to
affirming care to gain comfort with their gendered self. Each section of the SOC addresses
the needs of diverse individuals, and eunuchs
can be included within that group. They may
have commonality with some nonbinary individuals in that social transition may not be a
desired option, and hormone therapy may not
play the same role as it might in a social transition or transition within the binary (Wassersug
& Lieberman, 2010).

Like other gender diverse individuals, eunuch
individuals may be aware of their identity in
childhood or adolescence. Due to the lack of
research into the treatment of children who may
identify as eunuchs, we refrain from making specific suggestions.

Eunuch individuals may seek medical or surgical care (hormone suppression, orchiectomy,
and, in some cases, penectomy) to achieve physical, psychological, or sexual changes (Wassersug
& Johnson, 2007). It is important all patients,
including both eunuchs and those seeking castration, establish and maintain a relationship with
an HCP that is built upon trust and mutual
understanding. Given a lack of awareness of
eunuchs within the general medical community
and the fear among many individuals seeking
castration they will not be accepted, many do
not receive appropriate primary care and screening tests (Jäggi et  al., 2018). Increased awareness
and education among medical providers will help
address the need to be informed about the need
to include eunuchs in discussions of gender
diversity (Deutsch, 2016a). It goes without saying
that eunuchs require and deserve the same primary care services as the general population. The
topic of screening tests for cancers, such as prostate and breast, is an important area for
discussion as the risks of hormone-related cancers
are likely different among male-assigned people
whose testosterone and estrogen levels are not in
the male range. Due to a lack of studies looking
at the prevalence and incidence of hormone-related
cancers in the eunuch population, there is no
evidence to guide how often to screen for
hormone-related cancers with prostate exams,
PSA measurements, mammograms, etcetera.

The large literature on prostate cancer patients
who have been medically or surgically castrated
provides information about some of the effects
of post-pubertal castration (such as potential
osteoporosis, depression, or metabolic syndrome),
but voluntary eunuchs may interpret the results
very differently from those castrated for medical
reasons. Chemical or surgical castration may be
experienced as a source of distress to cis men
with prostate cancer, while the same treatment
may be affirming and a source of comfort for
eunuch individuals. Similarly, transmasculine people who have a mastectomy to gain comfort with
their bodies experience that surgery differently
from ciswomen who undergo mastectomy to treat
breast cancer (Koçan & Gürsoy, 2016; van de
Grift et  al., 2016). The prostate cancer information is well summarized by Wassersug et  al.
(2021) who provide references that explore the
large literature on the subject. Such information
on the effects of castration should be made available to those seeking castration.
Following an assessment as per the SOC-8,
medical options requested by the patient can be
considered and prescribed, if appropriate. These
options can be tailored to the individual to create
a plan that reflects their specific needs and preferences. The number and type of interventions
applied and the order in which these take place
may differ from person to person. These options
are consistent with both the assessment and surgery chapters of the SOC-8. Treatment options
for eunuchs to consider include:

- Hormone suppression to explore the effects of androgen deficiency for eunuch individuals wishing to become asexual, nonsexual, or androgynous;
- Orchiectomy to stop testicular production of testosterone;
- Orchiectomy with or without penectomy to alter their body to match their self-image;
- Orchiectomy followed by hormone replacement with testosterone or estrogen.

Per statement 5.6 in Chapter 5—Assessment
of Adults, eunuch individuals seeking gonadectomy consider a minimum of 6 months of hormone therapy as appropriate to the TGD person’s
gender goals before the TGD person undergoes
irreversible surgical intervention (unless hormones are not clinically indicated for the
individual).

## Statement 9.2: We recommend health care professionals consider medical intervention, surgical intervention, or both for eunuch individuals when there is a high risk that withholding treatment will cause individuals harm through self-surgery, surgery by unqualified practitioners, or unsupervised use of medications that affect hormones. {-}

The same assessment process recommended in
the SOC-8 ought to apply to eunuchs (see Chapter
5—Assessment of Adults). The Eunuch Archive
has a large number of posts from individuals
finding great difficulty in seeking medical providers who will perform castration surgery. There
are a large number of eunuch individuals who
have performed self-surgery or have had surgery
performed by people who are not credentialed
medical providers (Johnson & Irwig, 2014). There
are also clinical reports of eunuch individuals
who have self-castrated and accounts of patients
who have misled medical providers to obtain castration (Hermann & Thorstenson, 2015;
Mukhopadhyay & Chowdhury, 2009). There is
no doubt when members of this population are
denied access to quality medical treatment, they
will take actions that may cause them great harm,
such as bleeding and infection that may require
hospital admission (Hay, 2021; Jackowich et  al.,
2014; Johnson & Irwig, 2014). Because of these
serious problems and harm caused through
self-surgery, surgery by unqualified practitioners
or the unsupervised use of medications that affect
hormones, it is important health care providers
create a welcoming environment and consider
various treatment options after careful assessment 
to avoid the problems that lack of access to treatment and withholding treatment will cause.

When desired, castration can be achieved
either chemically or surgically. For some, chemical castration can be an appropriate trial prior
to undergoing surgical castration to determine
how the individual feels when hypogonadal (Vale
et  al., 2010). Chemical castration is usually
reversible if the medications are discontinued
(Wassersug et  al., 2021). The most common types
of medications used to lower testosterone levels
are antiandrogens and estrogen.

The two most commonly used antiandrogens,
cyproterone acetate and spironolactone, are oral.
Estrogen is sometimes prescribed for prostate
cancer patients to lower serum testosterone levels
via negative feedback at the hypothalamus and
pituitary gland. Estrogens and antiandrogens may
not fully suppress testosterone levels into the
female or castrate range, and oral estrogens
increase the risk of venous thromboembolism.
Although not commonly used due to cost, gonadotropin releasing hormone (GnRH) agonists are
a very effective method for suppressing the production of sex steroids and fertility (Hembree
et  al., 2017). When selecting a medication, we
advise using those which have been studied in
multiple transgender populations (i.e., estrogen,
cyproterone acetate, GnRH agonists) rather than
medications with little to no peer-reviewed scientific studies (i.e., bicalutamide, rectal progesterone, etc.) (Angus et  al., 2021; Butler et  al.,
2017; Efstathiou et  al., 2019; Tosun et  al., 2019).

Many eunuch individuals pursue hormone
replacement therapy following castration as they
do not desire the complete suppression of hormone levels and consequent problems, such as
the increased risk of osteoporosis. The two main
options for replacement of sex steroids are testosterone and estrogen that may be used in full
or partial replacement doses. The majority elect
testosterone as they present as male and are not
interested in feminization. A minority elect estrogen at a high enough dose to prevent osteoporosis, but low enough avoid most feminization.
They may identify as nonbinary, agender, or other
(Johnson et al., 2007; Johnson & Wassersug, 2016).

Although studies on hormone replacement
therapy in eunuchs are lacking, findings from
cisgender men treated for prostate cancer can be
informative regarding the effects of hormone
therapy. In a randomized controlled trial of 1,694
cisgender men treated for locally advanced or
metastatic prostate cancer, one group received a
GnRH agonist and the other received transdermal
estrogen (Langley et  al., 2021). Cisgender men
who received the GnRH agonist developed signs
and symptoms of both androgen and estrogen
deficiency, whereas men who received the estrogen patch only developed androgen-depleting
symptoms. Both groups had high rates of sexual
side effects (91%), and weight gain was similar
among the groups. Compared with cisgender men
receiving the GnRH agonist, cisgender men
treated with estrogen patches had a higher
self-reported quality of life, lower rates of hot
flushes (35% vs. 86%), and higher rates of gynecomastia (86% vs. 38%). Metabolically, cisgender
men receiving estrogen patches had favorable
changes with a lower mean fasting glucose, fasting total cholesterol, systolic and diastolic blood
pressure. Conversely, cisgender men receiving the
GnRH agonist experienced the opposite effects.
Based on this study, eunuchs may consider a low
dose of transdermal estrogen therapy to avoid
adverse estrogen-depleting effects, which include
hot flashes, fatigue, metabolic effects, and loss of
bone mineral density (Hembree et  al., 2017;
Langley et  al., 2021). For further information see
Chapter 12—Hormone Therapy.

## Statement 9.3:  We recommend health care professionals who are assessing eunuch individuals for treatment have demonstrated competency in assessing them. {-}

A frequent topic on the discussion boards of
the Eunuch Archive is the difficulty of finding
practitioners who are able to understand their
needs. Eunuchs and those seeking castration usually are less visible than other gender minorities
(Wassersug & Lieberman, 2010). Due to stigma
and fear of rejection by the medical community,
they may not voluntarily disclose their identity
and desires to their medical or mental health
providers. In some environments, medical providers may not be aware eunuchs exist and may
not even know they have treated eunuch-identified
patients.

The SOC section on assessment is applicable to
eunuch individuals. Like other gender diverse individuals, those seeking castration can engage in an
informed consent process in which qualified providers conduct assessments to ensure individuals are
capable of providing informed consent prior to medical interventions and to ensure a mental health
problem is not the etiology of the desire. As with
other sexual and gender minorities, working with
eunuchs requires an understanding that they are a
diverse population, and that each person is eunuch
in their own way (Johnson et al., 2007). The person
seeking services benefits from the professional’s
accepting stance, open inquiry, suspension of judgment, and flexible expectations, combined with professional competency and expertise.

To provide appropriate treatment, providers
must establish trust and respect by creating an
inclusive environment for eunuch-identified people. For eunuch-identified individuals, the ideal
intake form would ask the assigned sex and identified gender and offer multiple gender options,
including “eunuch” and “other.” Individuals may
identify with more than one option and should
be able to select more than one.

HCPs may be involved in the assessment, psychotherapy (if desired), preparation, and follow-up
for medical and surgical gender-affirming interventions. They may also provide support for partners and families. Eunuch-identified individuals
who want the support of a qualified mental
health provider will benefit from a therapist who
meets the experience and criteria set out in
Chapter 4—Education.

While some individuals seeking or considering
castration come to counseling or therapy because
they want emotional support or help with
decision-making, many come to providers for an
assessment in preparation for specific medical
interventions (Vale et  al., 2010).

## Statement 9.4: We suggest health care professionals providing care to eunuch individuals include sexuality education and counseling. {-}

Several research studies have contributed to
our knowledge of contemporary eunuch-identified
people and have explored demographic characteristics and sexuality (Handy et  al., 2015; Vale
et  al., 2013; Wibowo et  al., 2012, 2016). Medical
and MHPs should assume eunuchs are sexual
people capable of sexual activity, pleasure, and
relationships, unless they report otherwise
(Wibowo et  al., 2021). Research has shown there
is great diversity among eunuchs regarding the
level of desire, type of preferred physical or sexual contact, and nature of preferred relationships
(Brett et  al., 2007; Johnson et  al., 2007; Roberts
et  al., 2008). While some enjoy active sex lives
with or without romantic relationships, others
identify as asexual or aromantic and are relieved
by the loss of libido achieved through surgical
or chemical castration (Brett et  al., 2007). Each
person is different, and one’s genital status does
not determine sexual or romantic attraction
(Walton et  al., 2016; Yule et  al., 2015).

Regardless of the type of chemical suppression
or surgery a person has undergone, they may be
capable of sexual pleasure and sexual activity.
Contrary to popular belief, eunuchs are not necessarily asexual or nonsexual (Aucoin & Wassersug,
2006). Safe sex education is necessary for all people
who engage in sexual activity that could involve an
exchange of body fluids. See Chapter 17—Sexual
Health for information regarding sex education and
safe sex options for people with diverse genders and
sexualities. In addition, fertility preservation should
be discussed when considering medical interventions
that might impact the possibilities for future parenthood. For more considerations see Chapter 16—
Reproductive Health.
