# Institutional Environments

This chapter addresses care for transgender and
gender diverse (TGD) individuals who reside in
institutions. By definition, institutions are facilities or establishments in which people live and
receive care in a congregate or large group setting, where individuals may or may not have
freedom of movement, individual consent, or
agency. Carceral facilities (correctional facilities,
immigration detention centers, jails, juvenile
detention centers) and noncarceral facilities
(long-term care facilities, in-patient psychiatric
facilities, domiciliaries, hospice/palliative care,
assisted living facilities) are residential institutions
where health care access for transgender persons
may be provided. Much of the evidence in support of proper care of TGD persons comes from
carceral settings. However, the recommendations
put forth here apply to all institutions that house
TGD individuals, both carceral and noncarceral
(Porter et  al., 2016). All of the recommendations
of the Standards of Care apply equally to people
living in both types of institutions. People should
have access to these medically necessary treatments irrespective of their housing situation
within an institution (Brown, 2009). Care for an
institutionalized person must consider the individual does not have the access that
non-institutionalized persons have to securing
care on their own. For that reason,
institutionalized persons must be supported in
being able to receive the Standards of Care established by the World Professional Association for
Transgender Health (WPATH).

TGD residents in carceral facilities report the
lack of access to medically necessary
transgender-specific health care (see Chapter 2—
Global Applicability, Statement 2.1), which is
ranked as their number one concern while incarcerated (Brown, 2014; Emmer et  al., 2011). The
systemic racial inequities inherent in many
carceral environments (Sawyer, 2020), racial disparities in health outcomes (Nowotny et  al.,
2017), and the overrepresentation of TGD people
of color in some facilities (Reisner et  al., 2014)
punctuate a need for facility leadership to attend
to transitional care access issues. Controlled studies show clinically significant health and mental
health disparities for justice-involved transgender
people compared to matched groups of transgender people who have not been incarcerated or
jailed (Brown and Jones, 2015). Too often the
agencies, structures, and personnel that provide
care are lacking in knowledge, training, and
capacity to care for gender diverse people (Clark
et  al., 2017). Discrimination against TGD residents in palliative care settings, including hospice,
is common, and the needs of TGD patients or
their surrogates have been ignored in these settings (Stein et  al., 2020). This is one reason why
lesbian, gay, bisexual and transgender (LGBT)
patients may choose to hide their sexual and/or
gender identity when they enter a nursing home,
despite the fact that prior to their admission to
the facility they had been living publicly as a
LGBT-identified person (Carroll, 2017; Serafin
et  al., 2013).

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable. The
majority of the available literature related to institutions focuses on those who are incarcerated in
jails, prisons, or other carceral environments.
Literature about other institutional types were
also considered and referenced where available.
We hope future investigations will address this
relative lack of data from noncarceral institutions.
The recommendations summarized above are
generalizable to a variety of institutional settings
that have characteristics in common, including
extended periods of stay, loss of or limited agency,
and reliance on institutional staff for some or all
of the basic necessities of life.

## Statement 11.1: We recommend health care professionals responsible for providing gender-affirming care to individuals residing in institutions (or associated with institutions or agencies) recognize the entire list of recommendations of the SOC-8, apply equally to TGD people living in institutions. {-}

Just as people living in institutions require and
deserve mental and medical health care in general
and in specialty areas, we recognize TGD people
are in these institutions and thus need care specific to TGD concerns. We recommend the application of the Standards of Care (SOC) to people
living in institutions as basic principles of health
care and ethics (Beauchamp & Childress, 2019;
Pope & Vasquez, 2016). Additionally, numerous
courts have long upheld the need to provide
TGD-informed care based in the WPATH SOC
to people living in institutions as well (e.g.,
Koselik v. Massachusetts, 2002; Edmo v. Idaho
Department of Corrections, 2020). Agencies that
provide staffing for long-term, in-home services
should also be aware of the applicability of the
Standards of Care.

## Statement 11.2: We suggest institutions provide all staff with training on gender diversity. {-}

Because TGD care affects a small percentage
of the population, it requires specialized training
as outlined in this SOC Version 8. While the
level of training will vary based on the staff
member’s role within the institutional setting, all
staff will need training in addressing residents
appropriately while other clinical staff may need
more intensive training and/or consultation.
These training recommendations also apply to
agencies that supply staffing for in-home,
long-term care. Misgendering institutionalized
residents, not allowing for gender appropriate
clothing, shower facilities, or housing, and not
using chosen names communicates a lack of
respect for TGD residents who may experience
repeated indignities as emotionally traumatic,
depressing, and anxiety-producing. By providing
all institutional staff with training on gender
diversity and b asic comp etence in
transgender-related health care issues, these
harms can be prevented (Hafford-Letchfield
et al., 2017). Surveys indicate individuals working
with incarcerated individuals as well as in workers in noncarceral settings like palliative care
have significant knowledge gaps (Stein et  al.,
2020; White et  al., 2016). Hafford-Letchfied et  al.
(2017) showed benefit to training residential
long-term care staff when such training began
with “recognizing LBGT issues” and existed in
“care homes”. If the assigned health care providers lack the expertise to assess and/or treat gender diverse persons under their charge, outside
consultation should be sought from professionals
with expertise in the provision of gender-affirming
health care (Brömdal et  al., 2019; Sevelius and
Jenness, 2017).

## Statement 11.3: We recommend medical professionals charged with prescribing and monitoring hormones for TGD individuals living in institutions who need gender-affirming hormone therapy do so  without undue delay and in accordance with the SOC-8. {-}

TGD persons may be admitted to institutions
in need of evaluation for gender-affirming hormonal care or may develop this need after they
have resided in an institutional setting for varying
degrees of time. It is not uncommon for TGD
persons to be denied access to hormonal care for
months or years after making such needs known
or to be undertreated and poorly monitored,
delaying the necessary titration of medications
for safety and efficacy (Keohane, 2018; Kosilek v.
Massachusetts, 2002; Monroe v. Baldwin et  al.,
2019). This can result in significant negative mental health outcomes to include depression, anxiety,
suicidality, and surgical self-treatment risks
(Brown, 2010). As with all medically necessary
health care, access to gender-affirming hormone
therapies should be provided in a timely fashion
when indicated for a TGD resident, in both
carceral and noncarceral institutional environments. Medical professionals shall appropriately
titrate hormones based on laboratory results and
clinical outcomes to ensure results are within the
range of recommended standards within the field
of endocrinology. Such labs shall be taken at a
frequency so as not to delay appropriate titration.
TGD elderly people living in long-term care
facilities have unique needs (Boyd, 2019; Caroll,
2017; Porter, 2016). When elderly individuals
request hormonal treatment, while physicians
should assess pre-existing conditions, rarely do
such conditions absolutely contraindicate administering hormones in this population (Ettner,
2013). People with gender incongruence in institutions may also have coexisting mental health
conditions (Brown and Jones, 2015; Cole et  al.,
1997). These conditions should be evaluated and
treated appropriately as part of the overall assessment. Persons receiving hormones must be closely
medically monitored to avoid potential drug
interactions and polypharmacy (Hembree
et  al., 2017).

TGD persons who enter an institution on an
appropriate regimen of gender-affirming hormone
therapy should be continued on the same or similar therapies and monitored according to the
SOC Version 8. A “freeze frame” approach is
inappropriate and dangerous (Kosilek v.
Massachusetts, 2002). A “freeze frame” approach
is the outmoded practice of denying hormones
to people who are not already on them or keeping TGD persons on the same dose of hormones
throughout their institutionalization that they
were receiving upon admission, even if that dose
was an initiation (low) dose. TGD persons who
are deemed appropriate for de novo
gender-affirming hormone therapy should be
started on such therapy just as they would be
outside of an institution (Adams v. Federal Bureau
of Prisons, No. 09-10272 [D. MO June 7, 2010];
Brown 2009). The consequences of abrupt withdrawal of hormones or lack of initiation of hormone therapy when medically necessary include
a significant likelihood of negative outcomes
(Brown, 2010; Sundstrom and Fields v. Frank,
2011), such as surgical self-treatment by autocastration, depressed mood, increased gender dysphoria, and/or suicidality (Brown, 2010;
Maruri, 2011).

If an individual in an institution does receive
gender-affirming hormones and/or surgeries,
decisions regarding housing in sex-segregated
facilities may need to be reassessed for the safety
and well-being of the TGD person (Ministry of
Justice [UK], 2016).

## Statement 11.4: We recommend staff and professionals charged with providing health care to TGD individuals living in institutions recommend and support gender-affirming surgical treatments in accordance with SOC-8, when sought by the individual, without undue delay. {-}

TGD people with gender dysphoria should
have an appropriate treatment plan to provide
medically necessary surgical treatments that contain similar elements provided to persons who
reside outside institutions (Adams v. Federal
Bureau of Prisons, No. 09-10272 [D. MO June 7,
2010]; Brown 2009; Edmo v. Idaho Department
of Corrections, 2020). The consequences of denial
or lack of access to gender- affirming surgeries
for residents of institutions who cannot access
such care outside of their institutions may be
serious, including substantial worsening of gender
dysphoria symptoms, depression, anxiety, suicidality, and the possibility of surgical self-treatment 
(e.g., autocastration or autopenectomy; Brown,
2010; Edmo v. Idaho Department of Corrections,
2020; Maruri, 2011). It is not uncommon for
residents of institutions to be denied access to
evaluation for gender-affirming surgery as well
as denial of the treatment itself, even when medically necessary (Kosilek v. Massachusetts/
Dennehy, 2012; Edmo v. Idaho Department of
Corrections, 2020). The denial of medically necessary evaluations for and the provision of
gender-affirming surgical treatments and necessary aftercare is inappropriate and inconsistent
with these Standards of Care.

## Statement 11.5: We recommend administrators, health care professionals, and all others working in institutions charged with the responsibility of caring for TGD individuals allow those individuals who request appropriate clothing and grooming items to obtain such items concordant with their gender expression. {-}

Gender expression refers to people having
hairstyles, grooming products, clothing, names,
and pronouns associated with their gender identity in their culture and/or community (American
Psychological Association, 2015; Hembree et  al.,
2017). Gender expression is the norm among
most people within a culture or a community.
Social transition is the process of TGD persons
beginning and continuing to express their gender identity in ways that are authentic and
socially perceptible. Often, social transition
involves behavior and public presentation differing from what is usually expected for people
assigned a given legal gender marker at birth.
A gender marker is the legal label for a person’s
sex that is typically assigned or designated at
birth on official documents (American
Psychological Association, 2015). This is most
commonly recorded as male or female but also
intersex or “X” in some nations and jurisdictions. TGD individuals need the same rights to
gender expression afforded cisgender people
living both outside and inside institutional settings. Staff acceptance of social transition also
sets a tone of respect and affirmation that may
enhance respect and affirmation with others
residing in the institution, thereby increasing
safety and reducing some aspects of gender
incongruence.

Research indicates social transition and congruent gender expression have a significant beneficial effect on the mental health of TGD people
(Bockting & Coleman, 2007; Boedecker, 2018;
Devor, 2004; Glynn et  al., 2016; Russell et  al.,
2018). To allow for expressing gender identity,
these recommendations include being allowed to
wear gender congruent clothing and hairstyles,
to obtain and use gender-appropriate hygiene and
grooming products, to be addressed by a chosen
name or legal last name (even if unable to change
the assigned name legally yet), and to be
addressed by a pronoun consistent with one’s
identity. These elements of gender expression and
social transition, individually or collectively as
indicated by the individual’s needs, reduce gender
dysphoria/incongruence, depression, anxiety,
self-harm ideation and behavior, suicidal ideation
and attempts (Russell et  al., 2018). Furthermore,
these elements of congruent gender expression
enhance well-being and functioning (Glynn
et  al., 2016).

## Statement 11.6: We recommend all institutional staff address TGD individuals by their chosen names and pronouns at all times {-}

Given that an increasing percentage of people
openly identify as gender diverse, there is a need
to develop and implement practices and policies
that meet the needs of these people irrespective
of where they live (McCauley et  al., 2017). For
example, institutions should utilize medical and
administrative records systems for their residents
that track gender markers consistent with gender
identity and not solely sex assigned at birth. In
developing these recommendations, there was
recognition that gender expansiveness can challenge some institutional norms where TGD people live. However, all institutions have the
responsibility to provide for the safety and
well-being of all persons living therein (Australia,
2015; Corrective Services New South Wales, 2015;
Edmo v. Idaho Department of Corrections, 2020;
Kosilek v. Massachusetts, 2002; NCCHC, 2015).
Sevelius and colleagues (2020) demonstrated correct pronoun usage is gender-affirming for 
transgender women and correlates with positive
mental health and HIV-related health outcomes.
If a resident of an institution has legally changed
names, the institutional records should be changed
to reflect those changes.

## Statement 11.7: We recommend institutional administrators, health care professionals, and other officials responsible for making housing decisions for TGD residents consider the individual’s housing preference, gender identity and expression, and safety considerations, rather than solely their anatomy or sex assignment at birth. {-}

The separation of people based on sex assigned
at birth, a policy almost universally implemented
in institutional settings (Brown and McDuffie,
2009; Routh et  al., 2017), can create an inherently
dangerous environment (Ledesma & Ford, 2020).
Gender diverse people are extremely vulnerable to
stigmatization, victimization, neglect, violence, and
sexual abuse (Banbury, 2004; Beck, 2014; Jenness
and Fenstermaker, 2016; Malkin & DeJong, 2018;
Oparah, 2012; Stein et  al., 2020). This systemic
sex-segregated rigidity often fails to keep TGD
people safe and may impede access to
gender-affirming health care (Stohr, 2015). As a
result, institutions should follow procedures that
routinely evaluate the housing needs and preferences of TGD inmates (e.g., Federal Bureau of
Prisons, 2016). Likewise, the Prison Rape
Elimination Act specifically cites TGD individuals
as a vulnerable population and directs prisons
nationwide in the US to consider the housing preferences of these inmates (Bureau of Justice
Assistance, 2017).

## Statement 11.8: We recommend institutional personnel establish housing policies that ensure the safety of transgender and gender diverse residents without segregating or isolating these individuals. {-}

Assigning placement for a TGD resident solely
on the basis of their genital anatomy or sex
assigned at birth is misguided and places people
at risk for physical and/or psychological harm
(Scott, 2013; Simopoulos & Khin, 2014; Yona &
Katri, 2020). It is well established within carceral
settings, transgender individuals are far more
likely than other prisoners to be sexually harassed,
assaulted, or both (James et  al., 2016; Jenness &
Fenstermaker, 2016; Malkin & DeJong, 2019).
While placement decisions need to address security concerns, shared decision-making that
includes the input of the individual should be
made on a case-by-case basis (Federal Bureau of
Prisons, 2016; Jenness and Smyth, 2011). Some
transgender women prefer to reside in a male
facility while others feel safer in a female facility.
Given the range of gender identities, expression
and transition status is so heterogeneous among
gender diverse people, keeping residents safe
requires flexible decision-making processes (Yona
& Katri, 2020). One of the fears older LBGT
individuals have living in long-term care is mistreatment by roommates (Jablonski et  al., 2013).
Consequently, housing in nursing homes and
assisted living facilities should consider assigning
rooms to elders based on their self-identified
gender without regard to birth assignment or
surgical history and in collaboration with the
TGD patient.

Solitary confinement, sometimes referred to as
administrative segregation in carceral facilities,
refers to physical isolation of individuals during
which they are confined in their cells for approximately twenty-three hours each day. The use of
isolation is employed in some carceral facilities
as a disciplinary measure as well as a means of
protecting prisoners who are considered a risk
to themselves or others or who are at risk of
sexual assault by other inmates. However, isolating prisoners for safety concerns, if necessary,
should be brief, as isolation can cause severe
psychological harm and gross disturbances of
functioning (Ahalt et  al., 2017; Scharff Smith,
2006). National prison standards organizations as
well as The United Nations consider isolation
longer than 15 days to be torture (NCCHC, 2016;
United Nations, 2015).

## Statement 11.9: We recommend institutional personnel allow transgender and gender diverse residents the private use of shower and toilet facilities, upon request. {-}

The necessity and importance of privacy is
universal irrespective of gender identity. TGD 
individuals report avoiding public restrooms,
limiting the amount they eat and drink so as
not to have to use a public facility, often leading to urinary tract infections and kidney-related
problems (James et  al., 2016). TGD individuals
in institutions are often deprived of privacy in
bathroom and shower use, which can result in
psychological harm and/or physical and sexual
abuse (Bartels and Lynch, 2017; Brown, 2014;
Cook-Daniels, 2016; Mann, 2006). Similarly, in
carceral environments, pat downs, strip searches
and body cavity searches should be conducted
by staff members of the same sex with the
understanding this may not be possible in
extreme emergencies. The incidental viewing
of searches by other employees should be
avoided (Bureau of Justice Assistance, 2017).
Private use of shower and toilet facilities for
incarcerated transgender people is also required
by some laws, including for instance the United
States’ federal Prison Rape Elimination Act
in the US.

The population of aging/older TGD persons
who need to be served by institutions is increasing (Carroll, 2017; Witten & Eyler, 2016). Many
long-term care and other facilities catering to the
needs of the aging need to take into consideration the needs of their non-cisgender residents
(Ettner, 2016; Ettner & Wiley, 2016). Surveys of
HCPs working with elders in hospice and palliative care settings as well as other long-term care
facilities report patients who identify as TGD
often do not get their basic needs met, are discriminated against in their medical care access,
or are physically and/or emotionally abused (Stein
et  al., 2020) A survey of retirement and residential care providers in Australia found little experience with or understanding of the issues facing
this population. Indeed, many elderly TGD residents admitted to concealing their gender identity, bowing to the fear of insensitive treatment
or frank discrimination (Cartwright et  al., 2012;
Cook-Daniels, 2016; Grant et  al., 2012; Horner
et  al., 2012; Orel & Fruhauf, 2015).
