# Surgery and Postoperative Care

Medically necessary gender-affirmation surgery
(GAS) refers to a constellation of procedures
designed to align a person’s body with their gender
identity (see Chapter 2—Global Applicability for
medical necessity, Statement 2.1). This chapter
describes surgery and postoperative care recommendations for TGD adults and adolescents. Please
refer to Chapter 5—Assessment of Adults and
Chapter 6—Adolescents for the assessment criteria
related to surgery for adults and adolescents,
respectively. A summary of the recommendations
and assessment criteria can be found in Appendix D.

Recognizing the diverse and heterogeneous community of individuals who identify as transgender
and gender diverse (TGD), gender-affirming surgical
interventions may be categorized along a spectrum
of procedures for individuals assigned male at birth
(AMAB) and assigned female at birth (AFAB).

In appropriately selected TGD individuals, the
current literature supports the benefits of GAS.
While complications following GAS occur, many
are either minor or can be treated with local care
on an outpatient basis (Canner et  al., 2018;
Gaither et  al., 2018; Morrison et  al., 2016). In
addition, complication rates are consistent with
those of similar procedures performed for different diagnoses (i.e., non-gender-affirming
procedures).

In individuals AFAB, gender-affirming chest
surgery or “top surgery” (i.e. “subcutaneous mastectomy”) has been studied in prospective
(Agarwal et  al., 2018; Frederick et  al., 2017; Top
& Balta, 2017; van de Grift, Elaut et  al., 2017;
van de Grift et  al., 2016), retrospective (Bertrand
et  al., 2017; Claes et  al., 2018; Esmonde et  al.,
2019; Lo Russo et  al., 2017; Marinkovic &
Newfield, 2017; Poudrier et  al., 2019; Wolter
et al., 2015; Wolter et al., 2018), and cross-sectional
cohort studies (Olson-Kennedy, Warus et  al.,
2018; Owen-Smith et al., 2018; van de Grift, Elaut
et  al., 2018; van de Grift, Elfering et  al., 2018).
The efficacy of top surgery has been demonstrated in multiple domains, including a consistent and direct increase in health-related quality
of life, a significant decrease in gender dysphoria,
and a consistent increase in satisfaction with
body and appearance. Additionally, rates of regret
remain very low, varying from 0 to 4%. While
the effect of top surgery on additional outcome
measures such as depression, anxiety, and sexual
function also demonstrated a benefit, the studies
were of insufficient strength to draw definitive
conclusions. Although further investigation is
needed to draw more robust conclusions, the evidence demonstrates top surgery to be a safe and
effective intervention.

In individuals AMAB, fewer studies have been
published regarding gender-affirming breast surgery (“breast augmentation”) and include 2 prospective (Weigert et  al., 2013; Zavlin et  al., 2018),
1 retrospective cohort (Fakin et  al., 2019), and 3
cross-sectional cohort studies (Kanhai et  al., 2000;
Owen-Smith et  al., 2018; van de Grift, Elaut
et  al., 2018). All the studies reported a consistent
and direct improvement in patient satisfaction,
including general satisfaction, body image satisfaction, and body image following surgery.
Owen-Smith et  al. (2018) demonstrated a positive
trend toward improvement in both depression
and anxiety scores with increasing levels of
gender-affirming interventions. However, there
was no statistical comparison between individuals
who underwent top surgery and any other group.

Gender-affirming vaginoplasty is one of the
most frequently reported gender-affirming surgical
interventions; 8 prospective (Buncamper et  al.,
2017; Cardoso da Silva et  al., 2016; Kanhai, 2016;
Manero Vazquez et  al., 2018; Papadopulos, Zavlin
et  al., 2017; Tavakkoli Tabassi et  al., 2015; Wei
et  al., 2018; Zavlin et  al., 2018), 15 retrospective
cohort (Bouman, van der Sluis et  al., 2016;
Buncamper et  al., 2015; Hess et  al., 2016; Jiang
et  al., 2018; LeBreton et  al., 2017; Manrique et  al.,
2018; Massie et  al., 2018; Morrison et  al., 2015;
Papadopulos, Lelle et al., 2017; Raigosa et al., 2015;
Salgado et  al., 2018; Seyed-Forootan et  al., 2018;
Sigurjonsson et  al., 2017; Simonsen et  al., 2016;
Thalaivirithan et  al., 2018), and 3 cross-sectional
cohort studies have recently been reported
(Castellano et  al., 2015; Owen-Smith et  al., 2018;
van de Grift, Elaut et  al., 2018).

Although different assessment measurements
were used, the results from all studies consistently
reported both a high level of patient satisfaction
(78–100%) as well as satisfaction with sexual
function (75–100%). This was especially evident 
when using more recent surgical techniques.
Gender-affirming vaginoplasty was also associated
with a low rate of complications and a low incidence of regret (0–8%).

Recent literature reflects the increased clinical
interest in metoidioplasty and phalloplasty as
reflected by 3 prospective cohort (Garaffa et  al.,
2010; Stojanovic et  al., 2017; Vukadinovic et  al.,
2014), 6 retrospective cohort (Cohanzad, 2016;
Garcia et  al., 2014; Simonsen et  al., 2016; van de
Grift, Pigot et  al., 2017; van der Sluis et  al., 2017;
Zhang et  al., 2015), and 4 cross-sectional studies
(Castellano et  al., 2015; Owen-Smith et  al., 2018;
van de Grift, Elaut et  al., 2018; Wierckx, Van
Caenegem et  al., 2011), which reviewed the risks
and benefits of these procedures.

In terms of urinary function, between 75 and
100% of study participants were able to void
while standing. In terms of sexual function,
between 77 and 95% of study participants
reported satisfaction with their sexual function.
Most of these studies report high overall levels
of postoperative satisfaction (range 83–100%),
with higher rates of satisfaction in studies involving newer surgical techniques. Two prospective
and two retrospective cohort studies specifically
assessed regret following surgery and found no
transgender men experienced regret. While study
limitations were identified, the reported results
were consistent and direct.

In recent years, facial GAS (FGAS) has received
increased attention, and current literature supports
its benefits. Eight recent publications include 1 prospective cohort (Morrison et al., 2020), 5 retrospective cohort (Bellinga et  al., 2017; Capitán et  al.,
2014; Noureai et  al., 2007; Raffaini et  al., 2016;
Simon et  al., 2022), and 2 cross-sectional studies
(Ainsworth & Spiegel, 2010; van de Grift, Elaut
et  al., 2018). All 8 studies clearly demonstrated
individuals were very satisfied with their surgical
results (between 72% and 100% of individuals).
Additionally, individuals were significantly more
satisfied with the appearance of their face compared
with individuals who had not undergone surgery.
One prospective, international, multicenter, cohort
study found facial GAS significantly improves both
mid- and long-term quality of life (Morrison et al.,
2020). The results were direct and consistent, but
somewhat imprecise because of certain study limitations. While gender-affirming facial surgery for
AFAB individuals is an emerging field, current limited data points toward equal benefits in select
patients. Future studies are recommended.

Additional procedures and/or interventions
such as hair removal (prior to facial and/or genital surgery) may be required as part of the preoperative process. See Chapter 15—Primary Care.
Furthermore, consultation with pelvic floor physical therapy may be important (or required) both
before and after surgery.

**Representative surgical interventions include
(for complete list, see appendix E and the end
of this chapter):**

AMAB: facial feminization surgery (including
chondrolaryngoplasty/vocal cord surgery),
gender-affirming breast surgery, body contouring
procedures, orchiectomy, vagino/vulvoplasty
(with/without depth), aesthetic procedures, and
procedures designed to prepare individuals for
surgery (i.e., hair removal).

AFAB: facial masculinization surgery,
gender-affirming chest surgery, hysterectomy/
oophorectomy, metoidioplasty (including placement of testicular prosthesis), phalloplasty
(including placement of testicular/penile prostheses), body contouring procedures, aesthetic procedures, and procedures designed to prepare
individuals for surgery (i.e., hair removal).

It is important surgeons understand the indication(s) and the timing for GAS. This is especially important when caring for adolescents (see
Chapter 6—Adolescents).

It is important the surgeon and the patient participate in a shared decision-making approach that
includes 1) a multidisciplinary approach; 2) an
understanding of the patient’s goals and
expectations; 3) a discussion regarding the surgical
options and associated risks and benefits; and 4)
an informed plan for aftercare (see Chapter 5—
Assessment for Adults). These recommendations are
designed to facilitate an individualized approach
to care.

Appropriate aftercare is essential for optimizing
outcomes (Buncamper et  al., 2015; Lawrence,
2003), and it is important patients are informed
about postoperative needs (including local wound
care, activity restrictions, time off from work or
school, etc.). In addition, it is important the surgeon is available to provide and facilitate postoperative care, refer to specialty services, or both
as needed. This may include the need for ongoing
support (i.e., both from the caregiver as well as
the primary care provider, mental health professionals (MHPs), or both), as well as the need for
routine primary care (i.e., breast/chest cancer
screening, urologic/gynecologic care, etc.).

With the increase both in public interest and
in the number of gender-affirming surgical procedures (Canner et  al., 2018; Ross, 2017; Shen
et  al., 2019), additional training, tracking of
outcomes, and continuing medical education
for surgeons are necessar y (Schechter
et  al., 2017).

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable.

## Statement 13.1: We recommend surgeons who perform gender-affirming surgical procedures have the following credentials: {-}

**a. Training and documented supervision in gender-affirming procedures;
b. Maintenance of an active practice in gender-affirming surgical procedures;
c. Knowledge about gender diverse identities and expressions;
d. Continuing education in the field of gender-affirmation surgery;
e. Tracking of surgical outcomes.**

Surgeons offering GAS may have a variety of
surgical specialty training and backgrounds. The
most common surgical specialties include plastic
surgery, urology, gynecology, otolaryngology and
oro-maxillofacial surgery (Jazayeri et  al., 2021).
Consistent with other surgical domains, we recommend only surgeons who are certified or eligible
to be certified by their respective national professional boards offer GAS. Furthermore, it is recommended surgeons offering care for TGD people
have received documented training in
gender-affirming procedures and principles of
gender-affirming care (Schechter et  al., 2017;
Schechter & Schechter, 2019). The latter includes,
but is not limited, to knowledge about gender
diverse identities and expressions, and how those
affect patient goals, expectations, and outcomes. It
is important surgeons offering GAS be familiar with
the available procedures and can provide informed
consent. If surgeons do not offer a requested procedure, they may offer a referral for a second opinion. Surgeons offering GAS are expected to
participate in continuing education activities in the
field of GAS (i.e., meetings, conferences, seminars,
etc.) to maintain current knowledge. We further
recommend surgical outcomes be tracked and communicated to the patients as part of the informed
consent (Schechter et  al., 2017).

In addition, hospitals, institutions, and physician offices that offer GAS need to be knowledgeable regarding cultural competencies (i.e.,
language, terminology, etc.). This may require
ongoing and regular staff education.

## Statement 13.2: We recommend surgeons assess transgender and gender diverse people for risk factors associated with breast cancer prior to breast augmentation or mastectomy. {-}

Prior to breast augmentation or mastectomy,
individuals need to be informed about and
assessed for breast cancer risk factors, including
genetic mutations (i.e., BRCA1, BRCA2), family
history, age, radiation, exposure to estrogen, and
the amount of breast tissue anticipated to remain
after surgery (Brown, Lourenco et  al., 2021;
Brown & Jones, 2015; Colebunders et  al., 2014;
Gooren et  al., 2013; Salibian et  al., 2021; Weyers
et  al., 2010). Breast cancer screening balances the
identification of cancer with the selection of
appropriate imaging, tests, and procedures.
Currently, evidence-based screening guidelines
specific for TGD individuals do not exist (Salibian
et  al., 2021), however, recent guidelines have been
proposed by the American College of Radiology
(Brown, Lourenco et  al., 2021). Because the risk
of cancer in individuals seeking gender-affirming
breast augmentation or mastectomy is similar to
that in the general population (even in the setting
of hormone use), existing cancer screening guidelines need to be followed (Brown & Jones, 2015;
Gooren et  al., 2013; Salibian et  al., 2021; Weyers
et  al., 2010). Professionals need to be familiar
with updates to these guidelines as they are subject to change. Individuals who undergo
gender-affirming surgery of the chest should have
ongoing breast cancer surveillance, which should
be overseen by their primary care providers.

## Statement 13.3: We recommend surgeons inform transgender and gender diverse people undergoing gender-affirming surgical procedures about aftercare requirements, travel and accommodations, and the importance of postoperative follow-up during the preoperative process. {-}

Details about the timing, technique, and duration of the aftercare requirements are shared with
patients in the preoperative period such that
appropriate planning may be undertaken. This
includes a discussion regarding the anticipated
staging of surgical procedures (and associated
travel requirements). Given the small number of
surgeons who specialize in GAS, it is common
for patients to travel for their procedures. Prior
to surgery, surgeons should provide patients with
a postoperative follow-up schedule. The surgeon
should discuss the duration of the patient’s travel
dates, the anticipated inpatient versus outpatient
stay, and the potential need for flexibility in travel
arrangements (especially if complications occur).
Given the complexity and cost of travel and lodging, changes in the care plan should be shared
with the patient as early as possible. Surgeons
should facilitate continuity of care with a local
provider upon returning home.

Aftercare and postsurgical follow-up are
important. Gender-affirming surgical procedures 
often have specific aftercare requirements, such
as postsurgery resources (stable, safe housing;
resources for travel and follow-up care), instructions in health-positive habits (e.g., personal
hygiene, healthy living, prevention of urinary
tract infections (UTIs) and sexually-transmitted
infections (STIs) (Wierckx, Van Caenegem et  al.,
2011)), postsurgery precautions or limitations
on activities of daily life (e.g., bathing, physical
activity, exercise, nutritional guidance, resumption of sexual activity) (Capitán et  al., 2020),
postsurgery resumption of medications (i.e.,
anticoagulants, hormones, etc.), and detailed
postsurgery self-care activities (e.g., postvaginoplasty dilation and douching regimens, activation of a penile prosthesis, strategies to optimize
postphalloplasty urination, recommendations for
hair transplant care) (Capitán et  al., 2017;
Falcone et  al., 2018; Garcia, 2018; Hoebeke
et  al., 2005). Some aspects of postsurgery
self-care activities may be introduced prior to
surgery and are reinforced after surgery (Falcone
et  al., 2018). As issues such as wound disruptions, difficulty with dilation, and UTIs may
occur (Dy et  al., 2019), the follow-up period
provides an opportunity to intervene, mitigate,
and prevent complications (Buncamper et  al.,
2016; Garcia, 2021).

## Statement 13.4: We recommend surgeons confirm reproductive options have been discussed prior to gonadectomy in transgender and gender diverse people. {-}

Infertility is often a consequence of both
gender-affirming hormone therapy (temporary)
and GAS (permanent), and fertility preservation
is discussed prior to medical interventions, surgical interventions, or both (Defreyne, van
Schuylenbergh et  al., 2020; Jahromi et  al., 2021;
Jones et  al., 2021). Surgical interventions that
alter reproductive anatomy or function may limit
future reproductive options to varying degrees
(Nahata et  al., 2019). It is thus critical to discuss
infertility risk and fertility preservation (FP)
options with transgender individuals and their
families prior to initiating any of these interventions and on an ongoing basis thereafter (Hembree
et  al., 2017).

For specific recommendations regarding reproductive options, see Chapter 16—Reproductive Health.

## Statement 13.5: We suggest surgeons consider offering gonadectomy to eligible\* transgender and gender diverse adults when there is evidence they have tolerated a minimum of 6 months of hormone therapy (unless hormone replacement therapy or gonadal suppression is not clinically indicated or the procedure is inconsistent with the patient's desires, goals, or expressions of individual gender identity). For supporting text, see Statement 13.6. {-}

## Statement 13.6: We suggest health care professionals consider gender-affirming genital procedures in eligible\* transgender and gender diverse adults seeking these interventions when there is evidence the individual has been stable on their current treatment regime (which may include at least 6 months of hormone treatment or a longer period if required to achieve the desired surgical result unless hormone therapy is either not desired or is medic ally contraindicated). {-}

GAHT leads to anatomical, physiological, and
psychological changes. The onset of the anatomic effects (e.g., clitoral growth, vaginal mucosal atrophy) may begin early after the initiation
of therapy, and the peak effect is expected at
1–2 years (T'Sjoen et  al., 2019). Depending upon
the surgical result required, a period of hormone
treatment may be required (e.g., sufficient clitoral virilization prior to metoidioplasty/phalloplasty) or preferred for psychological reasons,
anatomical reasons, or both (breast growth and
skin expansion prior to breast augmentation,
softening of skin and changes in facial fat distribution prior to facial GAS) (de Blok
et  al., 2021).

For individuals who are not taking hormones
prior to surgical interventions, it is important
surgeons review the impact of this on the proposed surgery.

For individuals undergoing gonadectomy who
are not taking hormones, a plan for hormone
replacement can be developed with their prescribing professional prior to surgery.

## Statement 13.7: We recommend surgeons consider genderaffirming surgical interventions for eligible\* transgender and gender diverse adolescents when there is evidence a multidisciplinary approach that includes mental health and medical professionals has been involved in the decision-making process. {-}

Substantial evidence (i.e., observational studies
(Monstrey et  al., 2001; Stojanovic et  al., 2017),
literature reviews and expert opinions (Esteva
de Antonio et  al., 2013; Frey et  al., 2017;
Hadj-Moussa et  al., 2019; Pan & Honig, 2018),
established guidelines (Byne et  al., 2018; Chen,
Fuqua et  al., 2016; Hembree et  al., 2017; Karasic
& Fraser, 2018; Klein, Paradise et  al., 2018;
Weissler et  al., 2018), and a thematic content
analysis (Gerritse et  al., 2018), support the
importance of a multidisciplinary (i.e., medical,
mental health, and surgery) approach to transgender health care.

A multidisciplinary approach is especially
important in managing mental health issues if
these are experienced by a TGD person undergoing GAS (de Freitas et  al., 2020; Dhejne et  al.,
2016; van der Miesen et  al., 2016). In addition,
primary care providers and medical specialists
can help support decisions regarding the timing
of surgery, surgical outcomes and expectations,
perioperative hormone management, and optimization of medical conditions (Elamin et  al., 2010;
Hembree et  al., 2017).

For specific recommendations regarding presurgical assessment in adolescents, see Chapter
6—Adolescents.

## Statement 13.8: We recommend surgeons consult a comprehensive, multidisciplinary team of professionals in the field of transgender health when eligible\* transgender and gender diverse people request individually customized (previously termed “non-standard”) surgeries as part of a gender-affirming surgical intervention. {-}

Gender identities may present along a spectrum, and the expression of a person’s identity
may vary quite widely amongst individuals (Beek
et  al., 2015; Koehler et  al., 2018). While the overall goal of a particular procedure usually includes
reduction of gender dysphoria (van de Grift,
Elaut et  al., 2017) or achieving gender congruence, gender diverse presentations may lead to
individually customized surgical requests some
may consider “non-standard” (Beek et  al., 2015;
Bizic et  al., 2018). Individually customized surgical requests can be defined as 1) a procedure
that alters an individual’s gender expression without necessarily aiming to express an alternative,
binary gender; 2) the “non-standard” combination
of well-established procedures; or 3) both.

This is designed to help counsel and inform
the patient as well as to ensure their goals can
be achieved. The patient and their surgeon need
to work together to ensure the patient’s expectations are realistic and achievable, and the proposed interventions are safe and technically
feasible. The patient and their surgical team need
to engage in a shared decision-making process
(Cavanaugh et  al., 2016). This informed consent
process needs to address the irreversibility of
some procedures, the newer nature of some procedures, and the limited information available
about the long-term outcomes of some
procedures.

## Statement 13.9: We suggest surgeons caring for transgender men and gender diverse people who have undergone metoidioplasty/phalloplasty encourage lifelong urological follow-up. {-}

Postoperative complications following metoidioplasty/phalloplasty comprise the urinary tract
and sexual function (Kang et  al., 2019; Monstrey
et  al., 2009; Santucci, 2018; Schardein et  al.,
2019). Reported urethral complications (related
to urethral lengthening) include urethral strictures 35–58%, urethral fistulae 15–70% (Monstrey
et  al., 2009; Santucci, 2018; Schardein et  al.,
2019), diverticulae, mucocele due to vaginal
remnant, and hair growth within the neourethra
(Berli et  al., 2021; Veerman et  al., 2020).
Complications related to sexual function include
limited to absent tactile and/or erogenous sensation, difficulties with orgasm function, and
complications with penile prosthetics (Kang
et  al., 2019; Santucci, 2018). Penile
prosthesis-related complications are estimated to
involve infection (incidence 8–12%), 
malfunction, urethral erosion, skin extrusion,
and dislocation of its bone fixation (Falcone
et  al., 2018; Kang et  al., 2019; Morrison et  al.,
2016). Although most urethral and prosthetic
complications occur in the immediate and intermediate postoperative period, complications can
occur at any time. Early detection may reduce
morbidity (e.g., urethral strictures resulting in
fistulae, pending erosion of a penile prosthetic
leading to infection and requiring total explant)
(Blecher et  al., 2019).

Routine follow-up to assess for early evidence
of urethral stricture (or other urinary issues)
includes bladder ultrasound measurement of postvoid residual volume (to screen for and stage neourethral stricture), fluoroscopic urethrography (to
identify and stage neourethral strictures, fistulae,
and diverticulae), and cystourethroscopy to examine the urethra and bladder. TGD men may also
have routine urologic issues that need not be
related to gender transition (urinary calculi, hematuria, and genitourinary malignancies; fertility
preservation) (Sterling & Garcia, 2020a, 2020b).

## Statement 13.10: We recommend surgeons caring for transgender women and gender diverse people who have undergone vaginoplasty encourage follow-up with their primary surgeon, primary care physician, or gynecologist. {-}

Vaginoplasty is a safe procedure (Hontscharuk,
Alba, Hamidian Jahromi et  al., 2021). While
complications may occur, most are self-limited
or can be treated with minor interventions
(Hontscharuk, Alba, Hamidian Jahromi et  al.,
2021). Minor complications include issues such
as the formation of granulation tissue, intravaginal hair growth, delayed wound healing or
wound disruption (or both), aesthetic concerns,
and introital stenosis (Ferrando, 2020; Kloer
et  al., 2021). While these complications are usually self-limited, they may impact patient
well-being after surgery. Additionally, these issues
may go either undiagnosed or may be misdiagnosed if patients are not able to access care provided by professionals with expertise in the field
of transgender health. We recommend patients
be followed by their primary surgeon in person
and at regular intervals—for example at two
weeks, three months, six months, and one year
after surgery—although more follow-up may be
indicated for some individuals.

Additional gynecologic care is conducted
throughout the TGD person’s lifetime and can be
managed in many settings. A speculum exam to
check for granulation tissue, hair, and lesions can
be performed by the primary care provider, gynecologist, or GAS surgeon and may be necessary
outside of the immediate postoperative period
(Grimstad, McLaren et  al., 2021; Suchak et  al.,
2015; van der Sluis et  al., 2020). After confirmation by laboratory testing, UTIs, STIs, and other
fluctuations in the vaginal microbiome may be
treated following relevant guidelines formulated
for cisgender populations (Hooton, 2012; Sherrard
et  al., 2018). Manual prostate checks are performed based on relevant guidelines formulated
for cisgender populations via the vaginal canal,
as the prostate is located on the anterior wall of
the vagina (Carter et  al., 2013).

Other complications include issues such as stenosis of the neovaginal canal, rectovaginal fistulae, and inflammation (intestinal vaginoplasty)
(Bustos et  al., 2021). These require a combination
of nonsurgical and surgical treatment with consultation and possible referral back to the primary surgeon with other surgical consultants (i.e.,
colorectal surgeon), if required. In addition, as
pelvic floor dysfunction may affect 30–40% of
patients both prior to and following vaginoplasty,
the availability of pelvic floor physical therapists
is an important adjunct in the postoperative
period (Jiang et  al., 2019).

## Statement 13.11: We recommend patients who regret their gender-related surgical intervention be managed by an expert multidisciplinary team. {-}

The percentage of individuals who regret their
GAS is very low (between 0.3% and 3.8%) (De
Cuypere & Vercruysse, 2009; Defreyne, Motmans
et  al., 2017; Hadj-Moussa et  al., 2019;
Hadj-Moussa, Agarwal et  al., 2018; Hadj-Moussa,
Ohl et  al., 2018; Landén et  al., 1998; Narayan
et  al., 2021; van de Grift, Elaut et  al., 2018;
Wiepjes et  al., 2018). The highest incidence of 
regret was reported at a time when surgical techniques were less refined, the role of multidisciplinary care was less established, and the
Standards of Care did not exist or were not
widely known (Landén et  al., 1998). Regret can
be temporarily or permanent and may be classified as (Narayan et  al., 2021) social regret (caused
by difficulties in familial, religious, social, or professional life), medical regret (due to long-term
medical complications, disappointment in surgical
results or inadequate preoperative
decision-making), and true gender-related regret
(mostly based on patient experienced misdiagnosis, insufficient exploration of gender identity, or
both). This classification is in accordance with
previously discussed positive and negative
predictive factors (De Cuypere & Vercruysse,
2009; Gils & Brewaeys, 2007; Pfäfflin &
Junge, 1998).

A multidisciplinary team can help identify the
etiology of regret as well as the temporal stability
of the surgical request (Narayan et  al., 2021).
Following this evaluation and in consideration of
the individual’s circumstances, medical and/or surgical interventions with the intent of either continuing transition or performing surgical procedures to
return anatomy to that of the sex assigned at birth
may be indicated. For further information see
Chapter 5—Assessment of Adults.

*For eligibility criteria for adolescents and
adults, please refer to the Assessment for Adults
and Adolescent chapters and Appendix D.*

## GENDER-AFFIRMING SURGICAL PROCEDURES {-}

As the field’s understanding of the many facets
of gender incongruence expands, and as technology develops which allows for additional treatments, it is imperative to understand this list is
not intended to be exhaustive. This is particularly
important given the often lengthy time periods
between updates to the SOC, during which evolutions in understanding and treatment modalities
may occur.

FACIAL SURGERY
Brow • Brow reduction
• Brow augmentation
• Brow lift
Hair line advancement and/or hair transplant
Facelift/mid-face lift (following alteration of the underlying skeletal
structures)
Facelift/mid-face lift (following alteration of the underlying skeletal
structures)
• Platysmaplasty
Blepharoplasty • Lipofilling
Rhinoplasty (+/- fillers)
Cheek • Implant
• Lipofilling
Lip • Upper lip shortening
• Lip augmentation (includes autologous and non-autologous)
Lower jaw • Reduction of mandibular angle
• Augmentation
Chin reshaping • Osteoplastic
• Alloplastic (implant-based)
Chondrolaryngoplasty • Vocal cord surgery (see voice chapter)
BREAST/CHEST SURGERY
Mastectomy • Mastectomy with nipple-areola preservation/reconstruction as determined
medically necessary for the specific patient
• Mastectomy without nipple-areola preservation/reconstruction as
determined medically necessary for the specific patient
Liposuction
Breast reconstruction (augmentation) • Implant and/or tissue expander
• Autologous (includes flap-based and lipofilling)
GENITAL SURGERY
Phalloplasty (with/without scrotoplasty) • With/without urethral lengthening
• With/without prosthesis (penile and/or testicular)
• With/without colpectomy/colpocleisis
Metoidioplasty (with/without scrotoplasty) • With/without urethral lengthening
• With/without prosthesis (penile and/or testicular)
• With/without colpectomy/colpocleisis
Vaginoplasty (inversion, peritoneal, intestinal) • May include retention of penis and/or testicle
Vulvoplasty • May include procedures described as “flat front”
GONADECTOMY
Orchiectomy
Hysterectomy and/or salpingo-oophorectomy
BODY CONTOURING
Liposuction
Lipofilling
Implants • Pectoral, hip, gluteal, calf
Monsplasty/mons reduction
ADDITIONAL PROCEDURES
Hair removal: Hair removal from the face, body, and genital areas
for gender affirmation or as part of a preoperative preparation
process. (see Statement 15.14 regarding hair removal)
• Electrolysis
• Laser epilation
Tattoo (i.e., nipple-areola)
Uterine transplantation
Penile transplantation
