# Voice and Communication

Human beings engage in communication practices not only to exchange ideas about the outside
world, but also to present themselves as sociocultural beings and to negotiate forms of address,
referral and treatment by others that allow them
to feel safe and respected (Azul et  al., 2022). The
human voice is widely regarded as one of the
key modalities that contributes to the communication of gender as one of the dimensions of
human diversity. However, other aspects and ways
of communicating (e.g., articulation, word choice,
gesture, listener perceptions and attributions)
need to be considered as well (Azul, 2015; Azul
& Hancock, 2020). Throughout this chapter
“voice and communication” is used as a phrase
encompassing the meaning-making practices in
which each of the participants of a social encounter engage according to their own needs, wishes,
identifications, and capacities.

While a binary understanding of gender has
dominated the research literature in this area, the
approach recommended in this chapter implies
a broadly inclusive view of gender identification
(e.g., trans feminine, trans masculine, gender
fluid, nonbinary, genderqueer, agender) and the
understanding that gender does not exist in isolation, but intersects with other aspects of human
diversity (e.g., First Nation status, ethnicity/race,
sexuality, dis/ability, faith/religion/spirituality).
The recommendations in this chapter apply to
all transgender and gender diverse (TGD) people
who are seeking professional voice and communication support, including children, adolescents,
younger and older adults, and people who wish
to transition or detransition, irrespective of their
intervention choices.

Not every TGD person experiences challenges
with or wants professional support for their voice
and communication, but those who do often
encounter barriers in accessing care. Although
the percentages vary by country and TGD subpopulation, the statistics support the concern
TGD people are not able to access voice and
communication services when and how they
desire (Eyssel et  al., 2017; James et  al., 2016;
Oğuz et  al., 2021; Södersten et  al., 2015; Veale
et  al., 2019). In these studies, the percentage of
TGD people wishing to receive voice and
communication training or voice surgery is generally higher than the percentage of people who
have undergone these interventions. With few
exceptions, access to voice training is usually
greater than access to voice surgery. Groups of
TGD people who are further marginalized in
their societies, such as TGD people of marginalized race/ethnicity, experience discrimination
and limited access to care at even greater rates
(James et  al., 2016; Xavier et  al., 2005).

Cost, not knowing where to access services,
and services not being available are amongst the
most common barriers cited by research participants. According to studies in the US (Hancock
& Downs, 2021; Kennedy & Thibeault, 2020),
Turkey (Oğuz et  al., 2021), and Aotearoa/New
Zealand (Veale et  al., 2019), lack of accurate
information about options for voice and communication services among TGD people is a significant and ubiquitous barrier to care. Notably, in
Sweden, all TGD people are offered support for
their voice and communication when a diagnosis
of gender incongruence is made (Södersten et  al.,
2015). Additionally, cultural responsiveness of
providers is only slowly improving (Hancock &
Haskin, 2015; Jakomin et  al., 2020; Matthews
et  al., 2020; Sawyer et  al., 2014). Hancock and
Downs (2021) have conducted preliminary work
to identify specific barriers to voice and communication services and develop effective means for
eliminating them.

This chapter is intended to provide guidance
for health care professionals (HCPs) to support
and foster well-being in all TGD people who are
experiencing challenges or distress regarding their
own voice and communication practices and/or
regarding responses and attributions they receive
from others (Azul et  al., 2022).

A number of different approaches TGD people
can use to modify their voice and communication, either individually or in combination include
self-initiated change, which may be supported by
resources TGD people use to guide their voice
use and communication practice; behavioral
change supported by voice and communication
specialists (hereafter referred to as “voice and
communication training”); and change as a result
of androgen hormonal treatment and/or laryngeal
surgery. The currently existing research evidence 
does not include self-initiated change, but is
focused on the latter three approaches.

A “voice and communication specialist” is
someone who has knowledge regarding the ongoing and dynamic agency of speaker and listener
practices, relevant professional interventions
including behavioral, hormonal, and surgical, and
relevant processes related to biophysiology, sociocultural meaning-making, and external material
forces (Azul & Hancock, 2020). This specialist is
capable of conducting appropriate assessments to
inform the TGD person’s choice and support the
exploration of goals and intervention options by
providing guidance in a culturally responsive,
person-centered approach. This specialist has
knowledge and skills in behavioral voice and
communication intervention approaches.

Practices amenable to behavioral change
include: speaking and singing voice, mindfulness,
relaxation, respiration, pitch and pitch range,
voice quality, resonance/timbre, loudness, projection, facial expression, gesture, posture, movement, introducing self to others, describing
identifications and requesting culturally responsive treatment and forms of address by others,
assertive and resilient responses to misattributions, practicing implementation of voice use and
communication practices with different people
and in different everyday settings (e.g., Hancock
& Siegfriedt, 2020; Mills & Stoneham, 2017).

Voice and communication services are offered
as part of a complete and coordinated approach
to health, including support for medical, psychological, and social needs (Södersten et  al., 2015);
however, there are no prerequisites (e.g., hormone
use, pursuit of surgeries, or duration living in a
gender role). The overall purposes of voice and
communication support for TGD people are:

- To educate clients about the factors that influence functional voice and communication practices and the communication of the speaker’s identity (speaker, listener, professional practices, external material, biophysiological, and sociocultural factors);
- To enable clients to communicate their sense of sociocultural belonging (e.g., in terms of gender) in everyday encounters in a manner that matches the client’s desired self-presentation and to develop, maintain and habituate voices, vocal qualities, and communication practices that support the clients’ goals in a manner that does not harm the voice production mechanism;
- To provide training in functional voice production for clients who present with restrictions of voice function (e.g., as a result of overextending their voice production mechanism);
- To support clients with developing the capacity to assertively negotiate desired forms of address and referral from others (e.g., names, pronouns, titles) and to respond to misattributions in a skillful manner that contributes to increasing and maintaining the client’s well-being;
- To support clients to develop the problem-solving skills needed to manage anxiety, stress, and dysphoria in collaboration with mental health providers; and to navigate barriers to practice or real-life use of one’s preferred voice and communication.
- To provide, or refer clients to, supportive resources that facilitate developing voice and communication skills, vocal awareness, and well-being.
- To refer clients to, or collaborate with, other specialists such as mental health practitioners, laryngeal surgeons, and endocrinologists, who may be more equipped to meet the specific needs of that client. This may be especially relevant in cases where clients face unique challenges due to multiple barriers to their health and well-being or when the client wishes to pursue laryngeal surgery or hormone therapy.

Two types of laryngeal surgeries are relevant for
TGD populations: those for raising voice pitch
(e.g., glottoplasty with retro-displacement of the
anterior commissure, cricothyroid approximation
(CTA), feminization laryngoplasty, laser-assisted
voice adjustment (LAVA)) (Anderson, 2007;
Anderson, 2014; Brown, 2000; Casado, 2017;
Geneid, 2015; Gross, 1999; Kelly et  al., 2018;
Kanagalingam, 2005; Kim, 2017; Kim, 2020; Kocak,
2010; Kunachak, 2000; Mastronikolis, 2013;
Mastronikolis et  al., 2013; Matai, 2003; Meister, 
2017; Mora, 2018; Neumann, 2004; Nuyen et  al.,
2022; Orloff, 2006; Pickuth, 2000; Remacle, 2011;
Thomas & MacMillan, 2013; Tschan, 2016; Van
Borsel, 2008; Wagner, 2003; Wendler, 1990; Yang,
2002) and for lowering voice pitch (e.g., thyroplasty type III, vocal fold injection augmentation)
(Bultynck et al, 2020; Isshiki et  al., 1983; Kojima,
et  al. 2008; Webb et  al., 2021). Reported acoustic
benefits of pitch-raising surgery include increased
voice pitch (average frequency (fo)) and increased
Min fo(the lowest frequency in physiological voice
range). TGD people’s self-rating ratings show general satisfaction with voice postsurgery, although
individuals who are interested in more comprehensive changes to vocal self-presentation may
need to engage in behavioral interventions with a
voice and communication specialist in addition to
laryngeal surgery (Brown, Chang et al. 2021; Kelly
et  al., 2018; Nuyen et  al., 2022). Potential harms
of pitch-raising surgery can be assessed and
addressed in voice training by a voice and communication specialist. Reported harms of
pitch-raising surgery include voice problems such
as dysphonia, weak voice, restricted speaking voice
range especially upper range (lowered Max fo, in
the physiological voice range), hoarseness, vocal
instability, and lowering of frequency values over
time (Kelly et  al., 2018; Song & Jiang, 2017),
although the rate of these outcomes is inconsistent.

Research on pitch-lowering surgeries is limited. However, studies including eight TGD people who elected to undergo thyroplasty type III
after continued dissatisfaction with hormonal
treatment (Bultynck et  al., 2020) and one person
who received injection augmentation after testosterone therapy and voice training (Webb
et  al., 2020), reported statistically significant
lowering of fundamental frequency, perceived
as pitch.

Estrogen treatment in TGD people has not
been associated with measurable voice changes
(Mészáros et  al., 2005), while testosterone treatment in TGD people has been found to result
in both desired and undesired changes in genderand function-related aspects of voice production
(Azul, 2015; Azul et  al., 2017, 2018, 2020; Azul
& Neuschaefer-Rube, 2019; Cosyns et  al., 2014;
Damrose, 2008; Deuster, Di Vicenzo et  al., 2016;
Deuster, Matulat et  al. 2016; Hancock et  al., 2017;
Irwig et  al., 2017; Nygren et  al., 2016; Van Borsel
et  al., 2000; Yanagi et  al., 2015; Ziegler et  al.,
2018). Desired changes associated with testosterone treatment include lowered voice pitch,
increased male attributions to voice, and increased
satisfaction with voice. Reported dissatisfaction
with testosterone treatment include lack of or
insufficient lowering of voice pitch, dysphonia,
weak voice, restricted singing pitch range, and
vocal instability. These areas can be assessed and
addressed in voice training by a voice and communication specialist.

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable.

## Statement 14.1: We recommend voice and communication specialists assess current and desired vocal and communication function of transgender and gender diverse people and develop appropriate intervention plans for those dissatisfied with their voice and communication. {-}

Voice and communication specialists may
assess satisfaction with the presentation of sociocultural positionings in communicative encounters, including gender and other intersecting
identifications, taking into consideration that
these may or may not be static over time; attributions received from others, and how these
relate to the individual’s identifications, wishes,
and well-being; ratings of voice and speech naturalness; and voice and communication function
in relation to vocal demands. Assessments may
vary in nature (e.g., client-reported outcome measures, perceptual, acoustic, aerodynamic, endoscopic) according to their purpose (Davies et  al.,
2015; Leyns et  al., 2021; Oates & Dacakis, 1983).
For example, laryngeal visualization is used when
individuals present with a concomitant voice
problem, (e.g., muscle tension dysphonia) (Palmer
et al., 2011) or experience voice difficulties, which
may or may not be secondary to medical
gender-affirming interventions of androgen therapy or laryngeal surgery (Azul et  al., 2017).

Voice and communication specialists inform
intervention-seeking TGD people who are dissatisfied with their voice and communication about
available interventions that support TGD people
with their voice, communication, and well-being.
The nature of each option, including potential
outcomes and permanence, is presented objectively to provide the TGD person respect and
autonomy in decision-making. Appropriate intervention plans are individualized and feasible and
should be inclusive of any professional services
available. Goals may evolve over the course of
the support period as the TGD person explores
modifications to voice and communication,
assesses their satisfaction with achieved change
and refines their goals.

## Statement 14.2: We recommend voice and communication specialists working with transgender and gender diverse people receive specific education to develop expertise in supporting vocal functioning, communication, and well-being in this population. {-}

Academic and licensing credentials of voice and
communication specialists (e.g., speech-language
pathologists, speech therapists, singing voice teachers, voice coaches) vary by location but typically
do not specify criteria for working with specific
populations. Standard curricula in formal education for these professions often do not include
specific or adequate training for working with
TGD populations (Jakomin et  al., 2020; Matthews
et  al., 2020). General knowledge and skills related
to the vocal mechanism and interpersonal communication are foundational but insufficient for
conducting culturally responsive, person-centered
care for TGD people that is effective, efficient,
inclusive, and accessible (Hancock, 2017; Russell
& Abrams, 2019).

Professionals in this area should receive comprehensive education that invites them to develop
self-awareness, cultural humility, and cultural
responsiveness in order to be respectful of and
attentive to gender diversity and other aspects
of a client’s identifications that can take a variety
of forms and imply a range of different support
needs (Azul, 2015; Azul et  al., 2022). Client
preferences for use of names, formal forms of
address, gender entry, and pronouns need to be
respected in all communication with and about
the client (including medical records, reports,
emails). Education also needs to inform the setting up of a training space or clinic and administrative practices that are designed to be
welcoming to TGD people and allow TGD people to feel safe and respected when raising concerns or issues with the voice and communication
support team.

Voice and communication specialists working
with TGD people will need working knowledge
of applicable intervention principles, mechanisms,
and effectiveness, competence in teaching and
modeling voice and communication modification
skills, and a basic understanding of transgender
health, including hormonal and surgical treatments and trans-specific psychosocial issues.
Education needs to include methodologies and
practices that have been developed within TGD
communities and shown to be effective and
should ideally be presented by or in collaboration
with TGD people with lived experience of voice
and communication support.

## Statement 14.3: We recommend health care professionals in transgender health working with transgender and gender diverse people who are dissatisfied with their voice or communication consider offering a referral to voice and communication specialists for voice-related support, assessment, and training. {-}

A voice and communication specialist is well
positioned to provide information and guidance
to the TGD person expressing dissatisfaction
with their voice or communication when available. There is evidence voice and communication specialists provide support in such a way
that a client’s satisfaction with voice and communication can be achieved, thereby reducing
gender dysphoria and improving
communication-related quality of life (Azul,
2016; Block, 2017; Deuster, Di Vincenzo et  al.,
2016; Hancock, 2017; Hancock et  al., 2011;
Hardy et al., 2013; Kelly et al., 2018; McNamara,
2007; McNeill et  al., 2008; Owen & Hancock,
2010; Pasricha et  al., 2008; Söderpalm et  al.,
2004; Watt et  al., 2018).

There is empirical evidence that behavioral
voice support for TGD AMAB people is effective
with regard to achieving the targeted voice
changes (Oates, 2019). Seven studies prior to
2020 provide empirical evidence for the effectiveness of voice training, although it is somewhat
weak (Carew et  al., 2007; Dacakis, 2000; Gelfer
& Tice, 2013; Hancock et  al., 2011;Hancock &
Garabedian, 2013; McNeill et  al., 2008; Mészáros
et  al., 2005). Voice training methods across these
seven studies were similar and indicated voice
training can be effective at increasing average
fundamental frequency (average pitch), fundamental frequency range (pitch range), satisfaction
with voice, self-perception and listener perception
of vocal femininity, voice-related quality of life,
and social and vocational participation.
Weaknesses of the identified studies include lack
of randomized controlled trials evaluating voice
training, small sample sizes, inadequate long-term
follow-up, and lack of control of confounding
variables. In 2021, another systematic review of
the effects of behavioral speech training for
AMAB people reached similar conclusions (Leyns
et  al., 2021).

Until recently, there was almost no research
exploring the effectiveness of voice training with
TGD AFAB people. There is, however, some
promising, although weak evidence of effectiveness from a case study (Buckley et  al., 2020) and
one uncontrolled prospective study of group voice
training (Mills et  al., 2019).

## Statement 14.4: We recommend health care professionals working with transgender and gender diverse people who are considering undergoing voice surgery consider offering a referral to a voice and communication specialist who can provide pre- and/ or postoperative support. {-}

This statement does not intend to require TGD
people receive presurgical voice training. Rather,
it is recommended that every available support
be offered to provide individualized informational
counseling critical to person-centered care. The
recommendation is for the TGD person’s consideration to be informed as necessary by individualized informational counseling based on voice
assessment, trial voice training, and discussion
of expected voice outcomes and risks of surgery
with a voice and communication specialist.

For most types of laryngeal surgery, voice
training is recommended both prior to surgery
to ensure preparation of the vocal mechanism
for the surgical intervention and postsurgery to
ensure a return to functional voice production
(Branski et  al., 2006; Park et  al., 2021). For
pitch-raising surgery in particular, another reason
a trial of voice training is recommended is
because there are indications certain measures
improve with training but not with pitch-raising
surgery (e.g., factors relevant to intonation and
naturalness, such as maximum f0 pitch in speech
range; Kelly et  al., 2018).

The number and quality of research studies
evaluating pitch-lowering surgeries are currently
insufficient, particularly with regard to comparing
outcomes with and without other interventions
(i.e., testosterone) (Bultynck et  al., 2020). There
are more techniques and studies of pitch-raising
surgeries, but the quality of the evidence is still
low. Outcomes from pitch-raising surgeries have
been compared to outcomes from having no surgery (Anderson, 2007, 2014; Brown et  al., 2000; 
Geneid et  al., 2015; Gross, 1999; Kim, 2017;
Kocak et  al., 2010; Kunachak et  al., 2000; Matai
et  al., 2003; Meister et  al., 2017; Neumann &
Welzel, 2004; Orloff et  al., 2006; Pickuth et  al.,
2000; Remacle et  al., 2011; Thomas & Macmillan,
2013; Tschan et  al., 2016; Van Borsel et  al., 2008;
Yang et  al., 2002), another type of surgical technique (Mora, 2018), voice training alone
(Kanagalingam, 2005; Mastronikolis, 2013;
Wagner, 2003) and surgery in conjunction with
voice training (Casado, 2017; Kelly et  al., 2018).

In the 11 studies reporting whether participants had voice training prior to pitch-raising
surgery, most participants had prior voice training, but remained dissatisfied with voice and
sought surgical intervention. Thus, most studies
of surgical outcomes reflect the combined effects
of voice training and surgical intervention.
Attributes predicting which clients will pursue
surgery after training are unknown.

## Statement 14.5: We recommend health care professionals in transgender health inform transgender and gender diverse people commencing testosterone therapy of the potential and variable effects of this treatment on voice and communication. {-}

The research on the effects of androgen treatment on voice and communication of TGD people points to diverse and unpredictable effects
on individual clients. While a number of studies
have revealed effects on voice that matched TGD
people’s expectations and wishes, there is high
quality evidence demonstrating TGD people are
not always satisfied with the vocal outcomes of
testosterone therapy, and many experience difficulties such as inadequate pitch lowering, compromised voice quality, vocal loudness, vocal
endurance, pitch range, and flexibility (Azul,
2015, 2016, 2017, 2018; Cosyns et  al., 2014;
Nygren et  al., 2016; Ziegler et  al., 2018). A
recent meta-analysis of 19 studies examining the
effects of at least 1 year of testosterone therapy
estimated 21% of participants did not achieve
cisgender male normative frequencies, 21% of
participants reported incomplete voice-gender
congruence and voice problems, and 16% were
not completely satisfied with their voice
(Ziegler, 2018).

For people who wish to be treated with androgens, accurate informational counseling prior to
commencing treatment should enable the development of realistic expectations to avoid disappointment regarding the permanent impact of
hormone treatment on voice and communication. In addition, TGD people who do not have
access to or do not wish to be treated with testosterone, but want to change their voice and
those who are dissatisfied with the outcomes of
testosterone treatment can be advised by a voice
and communication specialist of alternative and
additional support options (e.g., behavioral voice
and communication training; pitch-lowering
surgery).

