# Reproductive Health

All humans, including transgender individuals,
have the reproductive right to decide whether
or not to have children (United Nations
Population Fund, 2014). Medically necessary
gender-affirming hormonal treatments (GAHTs)
and surgical interventions (see medically necessary statement in Chapter 2—Global Applicability,
Statement 2.1) that alter reproductive anatomy
or function may limit future reproductive options
to varying degrees (Hembree et  al., 2017; Nahata
et  al., 2019). It is thus critical to discuss infertility risk and fertility preservation (FP) options
with transgender individuals and their families
prior to initiating any of these treatments and
to continue these conversations on an ongoing
basis thereafter (Hembree et al., 2017). Established
FP options, such as embryo, oocyte, and sperm
cryopreservation, may be available for postpubertal transgender individuals (Nahata et  al.,
2019). Research protocols for ovarian and testicular tissue cryopreservation have also been
developed and studied (Borgström et  al., 2020;
Nahata et  al., 2019; Rodriguez-Wallberg, et  al.,
2019). Whereas the use of embryos, mature
oocytes, and sperm have all proven to be efficacious when employed within clinical treatments, cryopreserved gonadal tissues would
require either future retransplantation aimed at
obtaining fully functional gametes or the application of laboratory methods for culture, which
are still under development in basic science
research settings. Of note, recent American
Society for Reproductive Medicine guidelines
have lifted the experimental label on ovarian
tissue cryopreservation, but evidence remains
limited in prepubertal children (Practice
Committee of the American Society for
Reproductive Medicine, 2019).

Individualized care should be provided in the
context of each person’s parenthood goals. Some
research suggests transgender and gender diverse
(TGD) people may be less likely to desire genetically related children or children at all when
compared with cisgender peers (Defreyne, van
Schuvlenbergh et  al., 2020; Russell et  al., 2016;
von Doussa et al., 2015). Yet, several other studies
have shown many TGD individuals 1) desire
genetically related children; 2) regret missed
opportunities for FP; and 3) are willing to delay
or interrupt hormone therapy to preserve fertility
and/or conceive (Armuand, Dhejne et  al., 2017;
Auer et  al., 2018; De Sutter et  al., 2002; Defreyne,
van Schuylenbergh et  al., 2020; Tornello &
Bos, 2017).

Many barriers to FP have been reported, such
as cost (which is exacerbated when insurance
coverage is lacking), urgency to start treatment,
inability to make future-oriented decisions, inadequate provider knowledge/provider biases that
affect offering FP, and difficulties accessing FP
(Baram et  al., 2019; Defreyne, van Schuylenbergh
et  al., 2020). Additionally, transgender individuals may have worsening dysphoria due to various
steps in the FP process that are inseparably connected with the gender assigned at birth
(Armuand, Dhejne, et  al., 2017; Baram et  al.,
2019). When available, a multidisciplinary team
approach, where both medical and mental health
providers collaborate with gender-affirming fertility specialists, can help overcome some of
these barriers (Tishelman et  al., 2019). TGD
individuals should be educated about the distinction between fertility (utilizing one’s own
gametes/reproductive tissues) and pregnancy. In
addition to fertility considerations, efforts to
ensure equitable high-quality care for all forms
of family planning and building throughout the
full reproductive continuum must be maintained.
This includes procreative options such as perinatal care, pregnancy, delivery, and postpartum
care, as well as family planning and contraceptive
options to prevent unplanned pregnancies, and
pregnancy termination if sanctioned (Bonnington
et  al., 2020; Cipres et  al., 2017; Krempasky et  al.,
2020; Light et  al., 2018; Moseson, Fix et  al.,
2020). TGD people who wish to carry a pregnancy should undergo standard of care preconception care and prenatal counseling and
should receive counseling about breast/chest
feeding in environments supportive of people
with diverse gender identities and experiences
(MacDonald et  al., 2016; Obedin-Maliver &
Makadon, 2016).

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and 
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable.

## Statement 16.1: We recommend health care professionals who are treating transgender and gender diverse people and prescribing or referring patients for hormone therapies/surgeries advise their patients about: {-}

**a. Known effects of hormone therapies/surgeries on future fertility;
b. Potential effects of therapies that are not well studied and are of unknown reversibility;
c. Fertility preservation (FP) options (both established and experimental;
d. Psychosocial implications of infertility.**

### TGD individuals assigned female at birth {-}

GAHT may negatively impact future reproductive capacity (Hembree et  al., 2017). Based on
current evidence in transgender men and gender
diverse people assigned female at birth, these
risks are as follows:

Gonadotropin-releasing hormone agonists
(GnRHas) may be used for pubertal suppression
to prevent further pubertal progression until
adolescents are ready for masculinizing treatment. GnRHas may also be used for menstrual
suppression. GnRHas impact the maturation of
gametes but do not cause permanent damage to
gonadal function. Thus, if GnRHas are discontinued, oocyte maturation would be expected
to resume.

There are few studies detailing the effects of
testosterone therapy on reproductive function in
transgender men (Moravek et  al., 2020).
Restoration of normal ovarian function with
oocyte maturation after testosterone interruption
has been demonstrated in transgender men who
have achieved natural conception. A retrospective
study on oocyte cryopreservation showed no differences in the total number of oocytes retrieved
or in the number of mature oocytes between
transgender men and age- and BMI-matched cisgender women (Adeleye et  al., 2018, 2019). The
first results have recently been published evaluating live birth rates after controlled ovarian stimulation in transgender men compared with
cisgender women (Leung et al., 2019). Testosterone
was discontinued prior to ovarian stimulation.
Overall, the results concerning the influence of
testosterone on reproductive organs and their
function appear to be reassuring. However, there
have been no prospective studies to date evaluating the effect of long-term hormone therapy
on fertility (i.e., started in adolescence) or in
those treated with GnRHas in early puberty followed by testosterone therapy. It is important to
take into consideration that required medications
and procedures for cryopreserving oocytes (a
pelvic examination, vaginal ultrasound monitoring, and oocyte retrievals) may lead to increasing
gender dysphoria in transgender men (Armuand,
Dhejne et  al., 2017).

Surgical interventions among transgender men
will have obvious implications for reproductive
capacity. If patients desire a hysterectomy, the
option should be offered of preserving the ovaries
to retain the possibility of having a genetically
related child. Alternatively, if the ovaries are
removed either separately or concurrently with
the hysterectomy, egg freezing should be offered
prior to surgery and/or ovarian tissue cryopreservation can be done at the time of oophorectomy. Although this procedure is no longer
considered experimental, many transgender men
may desire in vitro maturation of primordial follicles, which is still investigational. Studies evaluating oocyte function have shown oocytes
isolated from transgender men with testosterone
exposure at the time of oophorectomy can be
matured in vitro to develop normal metaphase II
meiotic spindle structure (De Roo et  al., 2017;
Lierman et  al., 2017).

### TGD individuals assigned male at birth {-}

Based on current evidence in transgender
women and gender diverse people assigned male
at birth (AMAB), the influence of medical treatment is as follows:

GnRHas inhibit spermatogenesis. Data suggest
discontinuation of treatment results in a
re-initiation of spermatogenesis, although this
may take at least 3 months and most likely longer
(Bertelloni et  al., 2000). Furthermore, the psychological burden of re-exposure to testosterone
should be considered.

Anti-androgens and estrogens result in an
impaired sperm production (de Nie et  al., 2020;
Jindarak et  al., 2018; Kent et  al., 2018).
Spermatogenesis might resume after discontinuation of prolonged treatment with anti-androgens
and estrogens, but data are limited (Adeleye
et  al., 2019; Alford et  al., 2020; Schneider et  al.,
2017). Testicular volumes diminish under the
influence of gender-affirming hormone treatment
(Matoso et  al., 2018). Semen quality in transgender women may also be negatively affected by
specific life-style factors, such as a low frequency
of masturbation, wearing the genitals tight against
the body (e.g., with use of tight undergarments
for tucking) (Jung & Schuppe, 2007; Mieusset
et  al., 1985, 1987; Rodriguez-Wallberg, Häljestig
et  al., 2021).

## Statement 16.2: We recommend health care professionals refer transgender and gender diverse people interested in fertility preservation to providers with expertise in fertility preservation for further discussion. {-}

Research shows many transgender adults desire
biological children (De Sutter et  al., 2002;
Defreyne, van Schuylenbergh et  al., 2020;
Wierckx, Van Caenegem et  al., 2012), yet FP
rates remain widely variable, particularly in youth
(< 5%–40%) (Brik et  al., 2019; Chen et  al., 2017;
Chiniara et  al., 2019; Nahata et  al., 2017;
Segev-Becker et  al., 2020). In a recent survey,
many youth acknowledged their feelings about
having a biological child might change in the
future (Strang, Jarin et  al., 2018). Non-elective
sterilization is a violation of human rights (Ethics
Committee of the American Society for
Reproductive Medicine, 2015; Equality and
Human Rights Commission, 2021; Meyer III
et  al., 2001) and due to advances in social attitudes, fertility medicine, and affirmative transgender health care, opportunities for biological
parenthood during transition should be supported for transgender people. Due to the influence clinical opinion may have on transgender
or nonbinary people’s FP and on parenting decisions, FP options should be explored by health
care providers alongside options such as fostering, adoption, coparenting, and other parenting
alternatives (Bartholomaeus & Riggs, 2019).
Transgender patients who have been offered this
type of discussion and have been given the
choice to undergo procedures for FP have
reported the experience to be an overall positive
one (Armuand, Dhejne et  al., 2017; De Sutter
et  al., 2002; James-Abra et  al., 2015).

In other patient populations, fertility referrals
and formal fertility programs have been shown
to increase FP rates and improve patient satisfaction (Kelvin et  al., 2016; Klosky, Anderson
et  al., 2017; Klosky, Wang et  al., 2017; 
Shnorhavorian et  al., 2012) Physician attitudes
have been investigated, and recent studies indicate both an awareness and a desire to provide
fertility-related information to children and their
families (Armuand et  al., 2020). However, barriers have also been identified, including lack
of knowledge, comfort, and resources (Armuand,
Nilsson et  al., 2017; Frederick et  al., 2018).
Thus, the need for appropriate training of health
care providers has been highlighted, with
emphasis placed on fertility counseling and
offering FP options to all at-risk individuals in
an unbiased way (Armuand, Nilsson et  al.,
2017). Parents’ recommendations have also been
shown to significantly influence FP rates in adolescent and young adult males with cancer
(Klosky, Flynn et  al., 2017). While there are
clear clinical differences in these populations,
these findings can help inform best practices
for fertility counseling and FP referrals for
transgender individuals.

## Statement 16.3: We recommend transgender care teams partner with local reproductive specialists and facilities to provide specific and timely information and fertility preservation services prior to offering medical and surgical interventions that may impact fertility. {-}

Cryopreservation of sperm and oocytes are
established FP techniques and can be offered to
pubertal, late pubertal, and adult birth assigned
males and birth assigned females, respectively,
preferably prior to the initiation of GAHT
(Hembree et  al., 2017; Practice Committee of the
American Society for Reproductive Medicine,
2019). Cryopreservation of embryos can be
offered to adult (post-pubertal) TGD people who
wish to have a child and have an available partner. The future use of cryopreserved gametes is
also dependent on the gametes and reproductive
organs of the future partner (Fischer, 2021;
Maxwell et  al., 2017)

Although semen parameters have been shown
to be compromised when FP is performed after
initiation of GAH medication (Adeleye et  al.,
2019), one small study showed when the treatment was discontinued, semen parameters were
comparable to those in TGD patients who had
never undergone GAH treatment. With regard to
ovarian stimulation, oocyte vitrification yield and
subsequent use of the oocytes in in-vitro fertilization (IVF), there is no reason to anticipate a
different outcome in assisted reproductive technology (ART) treatments for TGD patients than
that obtained in cisgender patients undergoing
ART—other than individual confounding factors
related to (in)fertility—when gametes are banked
prior to any medical treatment (Adeleye et  al.,
2019). The use of oocytes in ART treatment
resulted in similarly successful outcomes in TGD
compared with controlled, matched cisgender
patients (Adeleye et  al., 2019; Leung et  al., 2019;
Maxwell et  al., 2017).

Although these are established options, few
pubertal, late pubertal or adult TGD people
undergo FP (Nahata et al., 2017), and many experience challenges while undergoing FP interventions. Not only is access and cost of these
methods a barrier (particularly in regions without
insurance coverage), but these procedures are
often physically and emotionally uncomfortable,
and many express concerns about postponing the
transitioning process (Chen et  al., 2017; De Sutter
et  al., 2002; Nahata et  al., 2017; Wierckx, Stuyver
et  al., 2012). Especially for the birth assigned
females, the invasiveness of endovaginal ultrasound follow-up of the ovarian stimulation and
oocyte retrieval procedures (and associated psychological distress) have been cited as a barrier
(Armuand, Dhejne et al., 2017; Chen et al., 2017).
There is also the concern young adults going
through transitioning may not have a clear vision
of parenting and are therefore likely to decline
the opportunity to use FP at that time—while as
adults, they may have different opinions about
parenthood (Cauffman & Steinberg, 2000). The
reduction of gender dysphoria during transitioning could also influence the decision-making
process surrounding FP (Nahata et  al., 2017).
Based on research showing TGD youths’ fertility
perspectives may change over time (Nahata et  al.,
2019; Strang, Jarin et al., 2018), FP options should
be discussed on an ongoing basis.

## Statement 16.4: We recommend health care professionals counsel pre- or early-pubertal transgender and gender diverse youth seeking gender-affirming therapy and their families that currently evidence-based/established fertility preservation options are limited. {-}

For prepubertal and early-pubertal children,
FP options are limited to the storage of gonadal
tissue. Although this option is available for TGD
children in the same way that it is available for
cisgender prepubertal and early-pubertal oncological patients, there is no literature describing
the utilization of this approach in the transgender
population. Ovarian tissue autotransplantation has
resulted in over 130 live births in cisgender
women. Most of these patients conceived naturally without ART (Donnez & Dolmans, 2015;
Jadoul et  al., 2017), and the majority stored their
ovarian tissue either as adults or during puberty.
Although the recent American Society for
Reproductive Medicine guideline has lifted the
experimental label from ovarian tissue cryopreservation (Practice Committee of the American
Society for Reproductive Medicine, 2019), there
are very few case reports describing a successful
pregnancy in a woman following the transplantation of ovarian tissue cryopreserved before
puberty. Demeestere et  al. (2015) and
Rodriguez-Wallberg, Milenkovic et  al. (2021)
described cases of successful pregnancies following transplantation of tissue procured at the age
of 14, and recently Matthews et  al. (2018)
described the case of a girl diagnosed with thalassemia who had ovarian tissue stored at the age
of 9 and transplantation 14 years late. She subsequently conceived through IVF and delivered
a healthy baby.

Currently, the only future clinical application
for storing ovarian tissue is autotransplantation,
which might be undesirable in a transgender man
(due to the potentially undesirable effects of estrogen). A laboratory procedure that would make it
possible to mature oocytes in vitro starting with
ovarian tissue would be the ideal future application
of stored ovarian tissue for transgender people,
but this technique is currently only being investigated and optimized in basic science research settings (Ladanyi et  al., 2017; Oktay et  al., 2010).

Prepubertal procurement of testicular tissue
has been documented as a low-risk procedure
(Borgström et  al., 2020; Ming et  al., 2018). Some
authors have also described this approach as a
theoretical option in transgender people (De Roo
et  al., 2016; Martinez et  al., 2017; Nahata, Curci
et  al., 2018). However, there are no reports in
the literature describing the clinical or investigational utilization of this FP option for TGD
patients. Moreover, the viability of the clinical
application of autotransplantation of testicular
tissue remains unknown in humans, and in vitro
maturation techniques are still in the realm of
basic science research. Thus, specialists currently
consider this technique experimental (Picton
et  al., 2015). The possibility of storing gonadal
tissue should be discussed prior to any genital
surgery that would result in sterilization, although
the probability of being able to use this tissue
must be clearly addressed.

## Statement 16.5: We recommend transgender and gender diverse people with a uterus who wish to carry a pregnancy undergo preconception care and prenatal counseling regarding the use and cessation of gender-affirming hormones, pregnancy care, labor and delivery, chest/breast feeding supportive services, and postpartum support according to local standards of care in a genderaffirming way. {-}

Most transgender men and gender diverse people (AFAB) retain their uterus and ovaries and
thus can conceive and carry a pregnancy even
after long-term testosterone use (Light et al., 2014).
Many transgender men desire children (Light
et  al., 2018; Wierckx, van Caenegem et  al., 2012)
and are willing to carry a pregnancy (Moseson,
Fix, Hastings et  al., 2021; Moseson, Fix, Ragosta
et  al., 2021). ART has expanded the opportunity
for many transgender men to conceive and fulfill
their family planning wishes (De Roo et  al., 2017;
Ellis et al., 2015; Maxwell et al., 2017). Some transgender men report psychological isolation, dysphoria related to the gravid uterus and chest
changes, and depression (Charter, 2018; Ellis et al.,
2015; Hoffkling et  al., 2017; Obedin-Maliver &
Makadon, 2016). Conversely, other studies have
reported some positive experiences during pregnancy as well (Fischer, 2021; Light et  al., 2014).
Mental health providers should be involved to
provide support, and counseling should be 
provided addressing when to stop and when to
resume gender-affirming hormones, what options
are available for the mode of delivery and for
chest/breast feeding (Hoffkling et al., 2017). Finally,
system-level and interpersonal-level interventions
should be implemented to ensure person-centered
reproductive health care for all people (Hahn
et  al., 2019; Hoffkling et  al., 2017; Moseson,
Zazanis et  al., 2020; Snowden et  al., 2018).

Given the potential harmful effects of testosterone on the developing embryo, discontinuing
testosterone or masculinizing hormone therapy
prior to conception and during the entire pregnancy is recommended. However, the optimal
time for both the discontinuation of testosterone
prior to pregnancy and its resumption after pregnancy is unknown. Since stopping gender-affirming
hormones may cause distress and exacerbate dysphoria in transgender men, when and how to
stop this therapy should be discussed during prenatal counseling (Hahn et  al., 2019). Because
information about the duration of testosterone
exposure and the risk of teratogenicity is lacking,
testosterone use should be discontinued prior to
attempting pregnancy and before stopping contraception. Moreover, there is limited information
regarding health outcomes of infants born to
transgender men. Small case series attempting to
evaluate this question have revealed no adverse
physical or psychosocial differences between
infants born to transgender men and infants in
the general population (Chiland et  al., 2013).

### Chest/Breast feeding {-}

In the limited studies evaluating lactation and
chest/breast feeding, the majority of transgender
men and TGD individuals AFAB who chose to
chest/breast feed postpartum were successful,
with research suggesting induction of lactation
is in part dependent on preconception counseling
and experienced lactation nursing support
(MacDonald et  al., 2016; Wolfe-Roubatis & Spatz,
2015). Specifically, transgender men and TGD
people who use testosterone should be informed
1) although quantities are small, testosterone
does pass through chest/breast milk; and 2) the
impact on the developing neonate/child is
unknown, and therefore gender-affirming testosterone use is not recommended during lactation
but may be resumed after discontinuation of
chest/breast feeding (Glaser et  al., 2009).
Transgender men and other TGD individuals
AFAB should be made aware some patients who
carry a pregnancy may experience undesired
chest growth and/or lactation even after chest
reconstruction and should therefore be supported
if they desire to suppress lactation (MacDonald
et  al., 2016).

There is limited information concerning lactation in transgender women as well as other TGD
AMAB but many also express the desire to chest/
breast feed. While there is a case report of a
transgender woman successfully lactating and
chest/breast feeding her infant after hormonal
support using a combination of estrogen, progesterone, domperidone, and breast pumping
(Reisman & Goldstein, 2018), the nutritional and
immunological profile of chest/breast milk under
these conditions has not been studied. Therefore,
patients need to be informed about the risks and
benefits of this approach to child feeding
(Reisman & Goldstein, 2018).

## Statement 16.6: We recommend medical providers discuss contraception methods with transgender and gender diverse people who engage in sexual activity that can result in pregnancy. {-}

Many TGD individuals may retain reproductive
capacity, and they (if they retain a uterus, ovaries,
and tubes) or their sexual partners (for sperm
producing individuals) may experience unplanned
pregnancies (James et  al., 2016; Light et  al., 2014;
Moseson, Fix et  al., 2020). Therefore, intentional
family planning counseling, including contraception and abortion conducted in gender-expansive
ways is needed (Klein, Berry-Bibee et  al., 2018;
Obedin-Maliver, 2015; Stroumsa & Wu, 2018).
TGD people AFAB may not use contraception due
to an erroneous assumption that testosterone is a
reliable form of contraception (Abern & Maguire,
2018; Ingraham et  al., 2018; Jones, Wood et  al.,
2017; Potter et  al., 2015). However, based on current understanding, testosterone should not be
considered a reliable form of contraception because
of its incomplete suppression of the
hypothalamic-pituitary-adrenal axis (Krempasky
et  al., 2020). Furthermore, pregnancies have
occurred while individuals are amenorrheic due 
to testosterone use, which may outlast active periods of administration (Light et al., 2014). Pregnancy
can also occur in TGD people after long-term
testosterone use (at least up to 10 years), although
the effect on oocytes and baseline fertility is still
unknown (Light et  al., 2014).

TGD people AFAB may use a variety of contraceptive methods (Abern & Maguire, 2018;
Bentsianov et  al., 2018; Bonnington et  al., 2020;
Chrisler et  al., 2016; Cipres et  al., 2017; Jones,
Wood et  al., 2017; Krempasky et  al., 2020; Light
et al., 2018).These methods may be used explicitly
for pregnancy prevention, menstrual suppression,
abnormal bleeding, or other gynecological needs
(Bonnington et  al., 2020; Chrisler et  al., 2016;
Krempasky et  al., 2020; Schwartz et  al., 2019).
Contraceptive research gaps within this population
are profound. No studies have examined how the
use of exogenous androgens (e.g., testosterone)
may modify the efficacy or safety profile of hormonal contraceptive methods (e.g., combined
estrogen and progestin hormonal contraceptives,
progestin-only based contraceptives) or
non-hormonal and barrier contraceptive methods
(e.g., internal and external condoms, non-hormonal
intrauterine devices, diaphragms, sponges, etc.).

Gender diverse individuals who currently have
a penis and testicles may engage in sexual activity
with individuals who have a uterus, ovaries, and
tubes of any gender. Gender diverse people who
have a penis and testicles can produce sperm
even while on gender-affirming hormones (i.e.,
estrogen), and although semen parameters are
diminished among those who are currently using
or who have previously used gender-affirming
hormones, azoospermia is not complete and
sperm activity is not totally suppressed (Adeleye
et  al., 2019; Jindarak et  al., 2018; Kent et  al.,
2018). Therefore, contraception needs to be considered if pregnancy is to be avoided in penis-invagina sexual activity between a person with a
uterus, ovaries, and tubes and one with a penis
and testicles, irrespective of the use of
gender-affirming hormones by either partner.
Currently, contraceptive methods available for use
by the sperm-producing partner are primarily
mechanical barriers (i.e., external condoms, internal condoms), permanent sterilization (i.e., vasectomy), and gender-affirming surgery (e.g.,
orchiectomy, which also results in sterilization).
Contraceptive counseling that considers sperm
producing, egg producing, and gestating partners
(as relevant) is recommended.

## Statement 16.7: We recommend providers who offer pregnancy termination services ensure procedural approaches are gender-affirming and serve transgender people and those of diverse genders. {-}

Unplanned pregnancies and abortions have
been reported among TGD individuals with a
uterus (Abern & Maguire, 2018; Light et al., 2014;
Light et  al., 2018; Moseson, Fix et  al., 2020) and
documented through surveys of abortion-providing
facilities (Jones et  al., 2020). However, the
population-based epidemiology of abortion provision and the experiences and preferences of
TGD individuals AFAB undergoing abortion still
represents a critical gap in research (Fix et  al.,
2020; Moseson, Fix et  al., 2020; Moseson, Lunn
et  al., 2020). Nonetheless, given that pregnancy
capacity exists among many TGD people and
pregnancies may not always be planned or
desired, access to safe, legal, and gender-affirming
pregnancy medical and surgical termination services is necessary.

