# Sexual Health

Sexual health has a profound impact on physical
and psychological well-being, regardless of one’s
sex, gender, or sexual orientation. However,
stigma about sex, gender and sexual orientation
influences individual's opportunities to live out
their sexuality and to receive appropriate sexual
health care. Specifically, in most societies, cisnormativity and heteronormativity lead to the
assumption that all people are cisgender and heterosexual (Bauer et  al., 2009), and that this combination is superior to all other genders and
sexual orientations (Nieder, Güldenring et  al.,
2020; Rider, Vencill et  al., 2019). Hetero-cisnormativity negates the complexity of gender,
sexual orientation, and sexuality and disregards
diversity and fluidity. This is all the more important since sexual identities, orientations, and practices of transgender and gender diverse (TGD)
people are characterized by an enormous diversity
(Galupo et  al., 2016; Jessen et  al., 2021; Thurston
& Allan, 2018; T'Sjoen et  al., 2020). Likewise, a
strong cross-cultural tendency toward allonormativity—the assumption that all people experience
sexual attraction or interest in sexual activity—
negates the diverse experiences of TGD people,
especially those who locate themselves on the
asexual spectrum (McInroy et  al., 2021; Mollet,
2021; Rothblum et  al., 2020).

The World Health Organization (WHO, 2010)
emphasizes sexual health depends on respect for
the sexual rights of all people, including the right
to express diverse sexualities and to be treated
respectfully, safely, and with freedom from discrimination and violence. Sexual health discourses
have focused on agency and body autonomy,
which include consent, sexual pleasure, sexual
satisfaction, partnerships, and family life (Cornwall
& Jolly, 2006; Lindley et  al., 2021). In light of
this, the WHO defines sexual health as “a state
of physical, emotional, mental, and social
well-being in relation to sexuality and not merely
the absence of disease, dysfunction, or infirmity.
Sexual health requires a positive and respectful
approach to sexuality and sexual relationships as
well as the possibility of having pleasurable and
safe sexual experiences, free of coercion, discrimination, and violence. For sexual health to be
attained and maintained, the sexual rights of all
persons must be respected, protected, and fulfilled” (WHO, 2006, p. 5). This includes individuals on the asexual spectrum, who may not
experience sexual attraction to others but may
still choose to be sexual at times (e.g., via
self-stimulation) and/or experience interest in
forming and building romantic relationships (de
Oliveira et  al., 2021).

Scientific attention to the sexual experiences
and behaviors of TGD people has grown in recent
years (Gieles et  al., 2022; Holmberg et  al., 2019;
Klein & Gorzalka, 2009; Kloer et  al., 2021;
Mattawanon et  al., 2021; Stephenson et  al., 2017;
Tirapegui et  al., 2020; Thurston & Allan, 2018).
This expansion within the literature reflects a
sex-positive framework (Harden, 2014), a framework that recognizes both the positive aspects
such as sexual pleasure (Laan et  al., 2021) and
potential risks associated with sexuality
(Goldhammer et  al., 2022; Mujugira et  al., 2021).
Studies of TGD people's sexuality, however, often
lack validated measures, an appropriate control
group, or a prospective design (Holmberg et  al.,
2019). Additionally, most focus exclusively on
sexual functioning (Kennis et  al., 2022), and thus
neglecting sexual satisfaction and broader operationalizations of sexual pleasure beyond functioning. The effects of current TGD-related
medical treatments on sexuality are heterogeneous
(Özer et  al., 2022; T'Sjoen et  al., 2020), and there
has been little research on the sexuality of TGD
adolescents (Bungener et  al., 2017; Maheux et  al.,
2021; Ristori et  al., 2021; Stübler & Becker-Hebly,
2019; Warwick et  al., 2022). While sex-positive
approaches to counseling and treatment for sexual
difficulties experienced by TGD individuals have
been proposed (Fielding, 2021; Jacobson et  al.,
2019; Richards, 2021), to date there is insufficient
research on the effectiveness of such interventions. Focusing on the promotion of sexual
health, the World Association for Sexual Health
(WAS) asserts the importance of sexual pleasure
and considers self-determination, consent, safety,
privacy, confidence, and the ability to communicate and negotiate sexual relations as major facilitators (Kismödi et  al., 2017). WAS asserts sexual
pleasure is integral to sexual rights and human
rights (Kismödi et  al., 2017). To contribute to 
the sexual health of TGD people, health care
professionals (HCPs) need both transgender-related
expertise and sensitivity (Nieder, Güldenring
et  al., 2020). With the goal of improving sexual
health care for TGD people to an ethically-sound,
evidence-based and high-quality level, HCPs must
provide their health services with the same care
(i.e., with transgender-related expertise), respect
(i.e., with transgender-related sensitivity), and
investment in sexual pleasure and sexual satisfaction as they provide for cisgender people
(Holmberg et  al., 2019).

In many societies, nonconforming gender
expressions can elicit strong (emotional) reactions, including in HCPs. Thus, when initiating
a health-related contact or establishing a therapeutic relationship, a nonjudgmental, open and
welcoming manner is most likely ensured when
HCPs reflect on their emotional, cognitive, and
interactional reactions to the person (Nieder,
Güldenring et  al., 2020). In addition,
transgender-related expertise refers to identifying
the impact the TGD person’s intersectional identities and experiences of marginalization and
stigma may have had on their whole self (Rider,
Vencill et  al., 2019). To adequately address the
specific physical, psychological, and social conditions of TGD people, HCPs must be aware
these conditions are generally overlooked due to
hetero-cis-normativity, lack of knowledge, and
lack of skills (Rees et  al., 2021). It is also important to consider cultural norms in relation to sexuality. For example, in some African cultures, the
idea of sex as taboo restricts the number of
acceptable terms to be used when taking a sexual
history (Netshandama et  al., 2017). Culturally
respectful language can facilitate talking openly
about one's sexual history and reduce ambiguity
or shame (Duby et  al., 2016). In addition, HCPs
must be sensitive to the history of (mis)use of
sexual identity and orientation as a gatekeeping
function to exclude transgender people from
gender-affirming health care (Nieder &
Richter-Appelt, 2011; Richards et  al., 2014). The
following recommendations aim to improve sexual health care for TGD people.

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable.

## Statement 17.1: We recommend health care professionals who provide care to transgender and gender diverse people acquire the knowledge and skills to address sexual health issues (relevant to their care provision). {-}

It is important HCPs addressing the sexual
health of TGD people be familiar with commonly
used terminology (see Chapter 1—Terminology)
and invite those seeking care to explain terms
with which the provider may not be familiar. In
this context, it is also important HCPs (are
prepared to) take a sexual history and offer treatment (according to their competencies) in a
gender-affirming way with a sex-positive approach
(Centers for Disease Control, 2020; Tomson et al.,
2021). However, HCP’s should apply greater
importance to the terminology that the TGD
person uses for their own body over more traditionally accepted or used medical terminology
(Wesp, 2016). When talking about sexual practices, it is advisable to focus on body parts (e.g.,
“Do you have sex with people with a penis, people with a vagina, or both?”; ACON, 2022) and
what role they play in their sexuality (e.g.,
“During Sex, do any parts of your body enter
your partners body, such as their genitals, anus,
or mouth?”; ACON, 2022).

## Statement 17.2: We recommend health care professionals who provide care to transgender and gender diverse people discuss the impact of gender-affirming treatments on sexual function, pleasure, and satisfaction. {-}

To achieve gender-affirming care, it is crucial
HCPs providing transition-related medical interventions be sufficiently informed about the possible effects on sexual function, pleasure, and
satisfaction (T'Sjoen et  al., 2020). Since clinical
data indicate that TGD people score significantly
lower in sexual pleasure compared to cisgender
individuals, this is even more important (Gieles
et  al., 2022). If the HCP cannot provide information about the effects of their treatment on
sexual function, pleasure, and satisfaction, they
are at least expected to refer the individual to
someone qualified to do so. If the sexuality-related
effects of their treatment are unknown, HCPs
should inform their patients accordingly. As
introduced above, the sexuality of TGD people
often challenges heteronormative views.
Nevertheless, there is a large amount of literature
(e.g., Bauer, 2018; Laube et  al., 2020; Hamm &
Nieder, 2021; Stephenson et  al., 2017) highlighting the spectrum character of sexuality that does
not fit into expectations of what male and female
sexuality entails (neither cis- nor transgender),
let alone that of gender diverse people (e.g., nonbinary, agender, genderqueer). Thus, these aspects
should be carefully considered by HCPs as
cisnormativity, heteronormativity, and
transition-related medical interventions, all have
a strong impact on sexual health.

Sexual pleasure has been well documented as
a factor in improving sexual, mental, and physical
health outcomes (Anderson, 2013). Next to sexual
function, HCPs providing sexual health care must
address sexual pleasure and satisfaction as a key
factor within sexual health. Historically sexual
health care has been disease focused, and this is
particularly true for research and clinical practice
in working with TGD patients. Although competent sexual health care regarding HIV and STIs
is necessary, integration of valuing sexual pleasure
of TGD patients is also necessary. Calls for integrating sexual pleasure as a focal point in STI
prevention education and interventions rest on
the understanding that pleasure is a motivator of
behavior (Philpott et  al., 2006). TGD people are
concerned about their sexual pleasure and need
HCPs who are knowledgeable about the diversity
of sexual practices and anatomical functioning
particular to TGD health care.

## Statement 17.3: We recommend health care professionals who provide care to transgender and gender diverse people offer the possibility of including the partner(s) in sexuality-related care, if appropriate. {-}

When appropriate and relevant to clinical concerns, inclusion of a sexual and/or romantic partner(s) in sexual health care decision-making can
increase TGD patients’ sexual well-being and
satisfaction outcomes (Kleinplatz, 2012). TGD
people may choose a range of transition-related
medical interventions, and these interventions
may have mixed results in shifting experiences
of anatomical dysphoria (Bauer & Hammond,
2015). When discussing the impact of medical
interventions on sexual functioning, pleasure, and
satisfaction, inclusion of partner(s) can increase
knowledge of potential changes and encourage
communication between partners (Dierckx et  al.,
2019). Because the process of transitioning is
often not a completely solitary endeavor, the
inclusion of sexual and/or romantic partners in
transition-related health care can facilitate the
process of “co-transitioning” (Lindley et  al., 2020; 
Siboni et  al., 2022; Theron & Collier, 2013) and
can also support sexual growth and adjustment
both in the individual as well as in the relationship. Social and psychological barriers to sexual
functioning and pleasure, including experiences
of gender dysphoria, stigmatization, lack of sexual
and relationship role models, and limited skills,
can have negative impacts on overall sexual
health (Kerckhof et  al., 2019). Supportive,
gender-affirming sexual communication between
partners improves sexual satisfaction outcomes
for TGD people (Stephenson et al., 2017; Wierckx,
Elaut et  al., 2011).

Inclusion of sexual and/or romantic partners
offers an additional opportunity to set realistic
expectations, disseminate helpful and accurate
information, and facilitate gender-affirming positive
communication related to sexual health. Ultimately,
however, it is important to recognize individual
choices related to gender health and transition are
the patients to make, not a partner’s decision. It
is important the inclusion of partners in sexual
health-related care occur only when appropriate
and as desired by patients. Contraindications might
include interpersonal dynamics that are abusive or
violent, in which case patient safety overrides partner involvement. Finally, it is critical HCPs treat
all people in an affirming and inclusive manner,
including sexual and romantic partners. This
means, for example, monitoring and addressing
assumptions and potential biases about the gender
or sexual orientation of a patient’s partner(s) or a
patient’s relationship structure.

## Statement 17.4: We recommend health care professionals counsel transgender and gender diverse people about the potential impact of stigma and trauma on sexual risk behavior, sexual avoidance, and sexual functioning. {-}

The TGD community is disproportionately
impacted by stigma, discrimination, and violence
(de Vries et  al., 2020; European Union Agency
for Fundamental Rights, 2020; McLachlan, 2019).
These experiences are often traumatic in nature
(Burnes et  al., 2016; Mizock & Lewis, 2008) and
can create barriers to sexual health, functioning,
and pleasure (Bauer & Hammond, 2015). For
example, stigmatizing narratives about
transgender sexualities can increase dysphoria
and sexual shame, increasing potential avoidance
of the sexual communication needed for safety
and optimizing pleasure (Stephenson et  al.,
2017). Research demonstrates stigma, a history
of sexual violence, and body image concerns can
negatively impact sexual self-esteem and agency,
for example the ability to assert what is pleasurable or to negotiate condom use (Clements-Nolle
et  al., 2008; Dharma et  al., 2019). Additionally,
gender dysphoria can be exacerbated by past
trauma experiences and ongoing trauma-related
symptoms (Giovanardi et  al., 2018). It may be
difficult for some TGD individuals to engage
sexually using the genitals with which they were
born, and they may choose to avoid such stimulation altogether, disrupting arousal and/or
orgasmic processes (Anzani et  al., 2021; Bauer
& Hammond, 2015; Iantaffi & Bockting, 2011)
or result in complex feelings about orgasm
(Chadwick et  al., 2019). HCPs providing
gender-affirming counseling and interventions
must be knowledgeable about the spectrum of
sexual orientations and identities (including asexual identities and practices) to avoid assumptions
based in heteronormative, cisnormative, allonormative modes of behavior or satisfaction while
also affirming the potential impacts of stigma
and trauma on sexual health and pleasure
(Nieder, Güldenring et  al., 2020). Some level of
disconnect or dissociation may at times be present, particularly in the case of acute trauma
symptoms (Colizzi et  al., 2015). It is important
HCPs be aware of these potential impacts on
sexual health, functioning, pleasure, and satisfaction, so they may refer patients as needed to
trauma-informed sexual counselors, mental
health providers, or both, who may be of further
assistance and may also normalize and validate
TGD patients exploring multiple diverse pathways of healing and accessing sexual pleasure.

## Statement 17.5: We recommend any health care professional who offers care that may impact sexual health provide information, ask about the expectation of the transgender and gender diverse individual, and assess their level of understanding of possible changes. {-}

Transition-related care can affect sexual function, pleasure, and satisfaction, both in positive
and negative ways (Holmberg et  al., 2018;
Kerckhof et  al., 2019; Thurston & Allan, 2018;
Tirapegui et  al., 2020). On the positive side,
gender-affirming care can help TGD people
improve their sexual functioning and increase
their sexual pleasure and satisfaction (Kloer et  al.,
2021; Özer et  al., 2022; T'Sjoen et  al., 2020). On
the negative side, however, data indicate problematic sexual health outcomes due to hormonal
and surgical treatments (Holmberg et  al., 2018;
Kerckhof et  al., 2019, Stephenson et  al., 2017;
Weyers et  al., 2009). Transition-related hormones
may affect mood, sexual desire, the ability to
have an erection and ejaculation, and genital tissue health, which in turn can impact sexual function, pleasure and sexual self-expression
(Defreyne, Elaut et  al., 2020; Garcia & Zaliznyak,
2020; Kerckhof et  al., 2019; Klein & Gorzalka,
2009; Wierckx, Elaut et  al., 2014). TGD people
who wish to use their original genital anatomy
for penetrative sex may benefit from medications
that address sexual health side effects of hormone
therapy, such as erectile dysfunction, medications
for TGD persons taking estrogen or antiandrogens, and topical estrogen and/or moisturizers
for TGD persons experiencing vaginal atrophy or
dryness due to testosterone therapy.

Sexual desire, arousal, and function may also
be affected by the use of psychotropic drugs
(Montejo et  al., 2015). As some TGD people are
prescribed medication to treat depression
(Heylens, Elaut et  al., 2014), anxiety (Millet et  al.,
2017) or other mental health concerns (Dhejne
et  al., 2016), their potential side effects on sexual
health should be considered.

Many gender-affirming surgeries can have significant effects on erogenous sensation, sexual
desire and arousal as well as sexual function and
pleasure. The impact of these changes for patients
may be mixed (Holmberg et  al., 2018). Chest
surgeries (breast reduction, mastectomy, and
breast augmentation) and body contouring surgeries, for example, may offer desired changes in
form and appearance thereby reducing psychological distress that can disrupt sexual functioning but may adversely affect erogenous sensation
(Bekeny et  al., 2020; Claes et  al., 2018; Rochlin
et  al., 2020). Genital surgeries in particular can
potentially affect sexual function and pleasure in
adverse ways, although they are likely to be experienced positively as the patient’s body becomes
more aligned with their gender, potentially opening new avenues for sexual pleasure and satisfaction (Hess et  al., 2018; Holmberg et  al., 2018;
Kerckhof et  al., 2019).

There are numerous examples of this in the extant literature:

- Surgery may result in a decrease, a total loss, or a possible increase in erogenous stimulation and/or experienced sensation compared with the patient’s presurgery anatomy (Garcia, 2018; Sigurjónsson et  al., 2017).
- A particular surgical option may be associated with specific limitations to sexual function that may manifest immediately, in the future, or at both timepoints, and which patients should consider before finalizing their choice when considering different surgical options (Frey et  al., 2016; Garcia, 2018; Isaacson et  al., 2017).
- Postsurgical complications can adversely affect sexual function by either decreasing the quality of sexual function (e.g., discomfort or pain with sexual activity) or by precluding satisfactory intercourse (Kerckhof et  al., 2019; Schardein et  al., 2019).

In general, satisfaction with any medical treatment is heavily influenced by the patient’s
expectations (Padilla et  al., 2019). Furthermore,
when patients have unrealistic expectations
before treatment, they are much more likely to
be dissatisfied with the outcome, their care, and
with their HCP (Padilla et  al., 2019). Therefore,
it is important to both provide patients with
adequate information about their treatment
options and to understand and consider what
is important to the patient with regard to outcomes (Garcia, 2021). Finally, it is important
the HCP ensure patients understand the potential adverse effects of a treatment on their sexual
function and pleasure so that a well-informed
decision can be made. This is relevant for both
meeting the standard of informed consent (i.e., 
discussion and understanding) and for providing
an opportunity to offer further clarification to
patients and, if desired, to their partners (Glaser
et  al., 2020).

## Statement 17.6: We recommend health care professionals who provide care to transgender and gender diverse people counsel adolescents and adults regarding prevention of sexually transmitted infections. {-}

The WHO (2015) recommends HCPs implement brief sexuality-related communication in
primary care for all adolescents and adults.
Therefore, TGD persons who are sexually active
or considering sexual activity may benefit from
sexuality-related communication or counseling
for the purpose of HIV/STI prevention. These
conversations are particularly important as TGD
persons are disproportionately impacted by
human immunodeficiency virus (HIV) and other
sexually transmitted infections (STIs) relative to
cisgender persons (Baral et  al., 2013; Becasen
et  al., 2018; Poteat et  al., 2016). However, few
data are available for non-HIV STIs, such as chlamydia, gonorrhea, syphilis, viral hepatitis, and
herpes simplex virus (Tomson et  al., 2021). The
United Nations Joint Programme on HIV/AIDS
estimates transgender women are 12 times more
likely than other adults to be living with HIV
(UNAIDS, 2019). A meta-analysis estimated a
pooled global HIV prevalence of 19% among
transgender women who have sex with men
(Baral et  al., 2013). HIV/STI risk is concentrated
among TGD subgroups at the confluence of multiple biological, psychological, interpersonal, and
structural vulnerabilities. In particular, transfeminine persons who have sex with cisgender men,
belong to minoritized racial/ethnic groups, live
in poverty, and engage in survival sex work are
at elevated HIV/STI risk (Becasen et  al., 2018;
Poteat et  al., 2015; Poteat et  al., 2016). Less is
known about HIV/STI risk among transgender
men or gender diverse persons AFAB. Small studies in high-income countries indicate a
laboratory-confirmed HIV prevalence of 0-4%
among transmasculine people (Becasen et  al.,
2018; Reisner & Murchison, 2016). Almost no
research has been conducted with transmasculine
people who have sex with cisgender men in
high-HIV-prevalence countries. Despite limited
epidemiologic data, transmasculine persons who
have sex with cisgender men frequently report
HIV/STI risk related to receptive vaginal and/or
anal sex (Golub et  al., 2019; Reisner et  al., 2019;
Scheim et  al., 2017) and may be more susceptible
to HIV acquisition from vaginal intercourse than
(pre-menopausal) cisgender women due to
hormone-related vaginal atrophy.

HCPs will need to supplement general guidelines by developing the knowledge and skills
needed for discussing sexual health issues with
TGD people, such as the use of gender-affirming
language (see Statement 17.1 in this chapter). It
is critical HCPs avoid assumptions about HIV/
STI risk based solely on a patient’s gender identity or anatomy. For example, many transgender
people are not sexually active, and TGD persons
may use prosthetics or toys for sex. To provide
appropriate prevention counseling, HCPs should
inquire about the specific sexual activities TGD
people engage in, and the body parts (or prosthetics) involved in those activities (ACON,
2022). Well-prepared HCPs (including, but not
limited to mental health providers) may also
engage in in-depth counseling with their patients
to address the underlying drivers of HIV/STI risk
(see Statement 17.3 in this chapter).

In all cases, HCPs should be sensitive to the
collective and individual histories of TGD people
(e.g., stereotypes and stigma about trans sexualities and gender dysphoria) and should explain to
patients the reasons for sexuality-related inquiries
and the voluntary nature of such inquiries. In
discussing HIV/STI prevention, HCPs should refer
to the full range of prevention options including
barrier methods, post-exposure prophylaxis,
pre-exposure prophylaxis, and HIV treatment to
prevent onwards transmission (WHO, 2021).
Trans-specific considerations for pre-exposure prophylaxis are addressed in Statement 17.8.

## Statement 17.7: We recommend health care professionals who provide care to transgender and gender diverse people follow local and World Health Organization guidelines for human immunodeficiency virus/sexual transmitted infections (HIV/ STIs) screening, prevention, and treatment. {-}

Like cisgender patients, TGD adolescents and
adults should be offered screening for HIV/STIs
in accordance with existing guidelines and based
on their individual risk of HIV/STI acquisition,
considering anatomy and behavior rather than
gender identity alone. Where local or national
guidelines are unavailable, WHO (2019a) offers
global recommendations; more frequent screening
is recommended for transgender people who have
sex with cisgender men as a key population
affected by HIV.

Gender-affirming genital surgeries and surgical
techniques have implications for STI risks and
screening needs, as outlined in recent guidelines
from the US Centers for Disease Control
(Workowski et  al., 2021). For instance, transfeminine persons who have had penile inversion
vaginoplasty using only penile and scrotal skin
to line the vaginal canal are likely at lower risk
of urogenital Chlamydia trachomatis (C. trachomatis) and Neisseria gonorrhoeae (N. gonorrhoeae), but newer surgical techniques that
employ buccal or urethral mucosa or peritoneum
flaps could in theory increase susceptibility to
bacterial STIs relative to the use of penile/scrotal
skin alone (Van Gerwen et  al., 2021). Routine
STI screening of the neovagina (if exposed) is
recommended for all transfeminine persons who
have had vaginoplasty (Workowski et  al., 2021).
For transmasculine persons who have had metoidioplasty with urethral lengthening, but not vaginectomy, testing for bacterial urogenital STIs
should include a cervical swab because infections
may not be detected in urine (Workowski
et  al., 2021).

Further, it is important for HCPs to offer testing at multiple anatomical sites as STIs in transgender patients are often extragenital
(Hiransuthikul et  al., 2019; Pitasi et  al., 2019).
Consistent with WHO (2020) recommendations,
self-collection of samples for STI testing should
be offered as an option, particularly if patients
are uncomfortable or unwilling to undergo
provider-collected sampling due to gender dysphoria, trauma histories, or both. Where relevant,
integration of HIV/STI testing with regular serology used to monitor hormone therapy may better
facilitate access to care (Reisner, Radix et  al.,
2016; Scheim & Travers, 2017).

## Statement 17.8: We recommend health care professionals who provide care to transgender and gender diverse people address concerns about potential interactions between antiretroviral medications and hormones. {-}

For TGD adolescents and adults at substantial
risk of HIV infection (generally defined as an
ongoing serodiscordant relationship or condomless sex outside of a mutually monogamous relationship with a known HIV-negative partner;
WHO, 2017), pre-exposure prophylaxis (PrEP) is
an important HIV prevention option (Golub
et  al., 2019; Sevelius et  al., 2016; WHO, 2021).
To encourage uptake of PrEP, in 2021 the US
Centers for Disease Control recommended all
sexually active adolescents and adults be informed
about PrEP and offered it if requested (CDC,
2021). For treatment among people living with
HIV, transgender-specific guidelines are available
in some settings (e.g., Panel on Antiretroviral
Guidelines for Adults and Adolescents, 2019).

For both HIV prevention and treatment, there
are antiretroviral dosing and administration considerations specific to TGD persons. For oral PrEP,
only daily dosing is currently recommended for
TGD persons as studies demonstrating the effectiveness of event-driven PrEP with emtricitabine/
tenofovir disoproxil fumarate (TDF) have been
limited to cisgender men (WHO, 2019c). In addition, while emtricitabine/tenofovir alafenamide
(TAF) is a new oral PrEP option, as of early 2022
it is not recommended for people at risk of HIV
acquisition through receptive vaginal sex due to a
lack of evidence (CDC, 2021). Finally, long-acting
injectable formulations of both PrEP and HIV
treatment are increasingly available (e.g., cabotegravir for PrEP), and while they are recommended
for all patients who might benefit from injectable
options, indicated injection sites (i.e., the gluteal
muscle) may be unsuitable for individuals who
have used soft tissue fillers (Rael et  al., 2020).

There is little evidence supporting the occurrence of drug-drug interactions between
gender-affirming hormones and PrEP medications. A few small studies, primarily relying on
self-reported PrEP use, have shown reduced
PrEP drug concentrations in transgender women
undergoing hormone therapy, although 
concentrations remained in the protective range
(Yager & Anderson, 2020). A subsequent
drug-drug interaction study using directly
observed PrEP therapy failed to detect an impact
of hormone therapy on PrEP drug concentrations in transgender women and found transgender women and men taking hormone therapy
achieved high levels of protection against HIV
infection (Grant et  al., 2020). Most importantly,
for many TGD people, no impact of PrEP on
hormone concentrations has been detected. With
regard to HIV treatment, specific antiretroviral
medications may impact hormone concentrations; however, these can be managed by selecting alternative agents, monitoring and adjusting
hormone dosing, or both (Cirrincione et  al.,
2020) as detailed in guidelines from the US
Department of Health and Human Services
(Panel on Antiretroviral Guidelines for Adults
and Adolescents, 2019). Nevertheless, concerns
about drug-drug interactions, particularly interactions that may limit hormone concentrations,
represent a barrier to the implementation and
adherence to antiretroviral therapy for HIV prevention or treatment (Radix et  al., 2020; Sevelius
et  al., 2016). Therefore, it is advisable for HCPs
to proactively address such concerns with those
who are candidates for PrEP or HIV treatment.
Integration of PrEP or HIV treatment with hormone therapy may further reduce barriers to
implementation and adherence (Reisner, Radix
et  al., 2016). Integration may be achieved
through colocation or through coordination
with an HIV specialist if the primary care provider does not have the necessary expertise.
Some TGD persons may benefit from standalone
PrEP or sexual health services that provide
greater privacy and flexibility, and thus differentiated service delivery models are needed
(Wilson et  al., 2021).

