# Mental Health

This chapter is intended to provide guidance to
health care professionals (HCPs) and mental health
professionals (MHPs) who offer mental health care
to transgender and gender diverse (TGD) adults. It
is not meant to be a substitute for chapters on the
assessment or evaluation of people for hormonal or
surgical interventions. Many TGD people will not
require therapy or other forms of mental health care
as part of their transition, while others may benefit
from the support of mental health providers and
systems (Dhejne et  al., 2016).

Some studies have shown a higher prevalence of
depression (Witcomb et al., 2018), anxiety (Bouman
et  al., 2017), and suicidality (Arcelus et  al., 2016;
Bränström & Pachankis, 2022; Davey et  al., 2016;
Dhejne, 2011; Herman et  al., 2019) among TGD
people (Jones et  al., 2019; Thorne, Witcomb et  al.,
2019) than in the general population, particularly
in those requiring medically necessary
gender-affirming medical treatment (see medically
necessary statement in Chapter 2—Global
Applicability, Statement 2.1). However, transgender
identity is not a mental illness, and these elevated
rates have been linked to complex trauma, societal
stigma, violence, and discrimination (Nuttbrock
et al., 2014; Peterson et al., 2021). In addition, psychiatric symptoms lessen with appropriate
gender-affirming medical and surgical care (Aldridge
et al., 2020; Almazan and Keuroghlian; 2021; Bauer
et  al., 2015; Grannis et  al., 2021) and with interventions that lessen discrimination and minority
stress (Bauer et  al., 2015; Heylens, Verroken et  al.,
2014; McDowell et  al., 2020).

Mental health treatment needs to be provided by
staff and implemented through the use of systems
that respect patient autonomy and recognize gender
diversity. MHPs working with transgender people
should use active listening as a method to encourage
exploration in individuals who are uncertain about
their gender identity. Rather than impose their own
narratives or preconceptions, MHPs should assist
their clients in determining their own paths. While
many transgender people require medical or surgical
interventions or seek mental health care, others do
not (Margulies et al., 2021). Therefore, findings from
research involving clinical populations should not
be extrapolated to the entire transgender population.

Addressing mental illness and substance use
disorders is important but should not be a barrier
to transition-related care. Rather, these interventions to address mental health and substance use
disorders can facilitate successful outcomes from
transition-related care, which can improve quality
of life (Nobili et  al., 2018).

All the statements in this chapter have been
recommended based on a thorough review of
evidence, an assessment of the benefits and
harms, values and preferences of providers and
patients, and resource use and feasibility. In some
cases, we recognize evidence is limited and/or
services may not be accessible or desirable.

## Statement 18.1: We recommend mental health professionals address mental health symptoms that interfere with a person’s capacity to consent to genderaffirming treatment before gender-affirming treatment is initiated. {-}

Because patients generally are assumed to be
capable of providing consent for care, whether
the presence of cognitive impairment, psychosis,
or other mental illness impairs the ability to give
informed consent is subject to individual examination (Applebaum, 2007). Informed consent is
central to the provision of health care. The health
care provider must educate the patient about the
risks, benefits, and alternatives to any care that
is offered so the patient can make an informed,
voluntary choice (Berg et  al., 2001). Both the
primary care provider or endocrinologist prescribing hormones and the surgeon performing
surgery must obtain informed consent. Similarly,
MHPs obtain informed consent for mental health
treatment and may consult on a patient’s capacity
to give informed consent when this is in question. Psychiatric illness and substance use disorders, in particular cognitive impairment and
psychosis, may impair an individual’s ability to
understand the risks and benefits of the treatment
(Hostiuc et  al., 2018). Conversely, a patient may
also have significant mental illness, yet still be
able to understand the risks and benefits of a
particular treatment (Carpenter et  al., 2000).
Multidisciplinary communication is important in
challenging cases, and expert consultation should
be utilized as needed (Karasic & Fraser, 2018).
For many patients, difficulty understanding the
risks and benefits of a particular treatment can
be overcome with time and careful explanation.
For some patients, treatment of the underlying
condition that is interfering with the capacity to
give informed consent—for example treating an
underlying psychosis—will allow the patient to
gain the capacity to consent to the required treatment. However, mental health symptoms such as
anxiety or depressive symptoms that do not affect
the capacity to give consent should not be a barrier for gender-affirming medical treatment, particularly as this treatment has been found to
reduce mental health symptomatology (Aldridge
et  al., 2020).

## Statement 18.2: We recommend mental health professionals offer care and support to transgender and gender diverse people to address mental health symptoms that interfere with a person’s capacity to participate in essential perioperative care before gender-affirmation surgery. {-}

The inability to adequately participate in
perioperative care due to mental illness or substance use should not be viewed as an obstacle
to needed transition care, but should be seen as
an indication mental health care and social support be provided (Karasic, 2020). Mental illness
and substance use disorders may impair the ability of the patient to participate in perioperative
care (Barnhill, 2014). Visits to health care providers, wound care, and other aftercare procedures (e.g., dilation after vaginoplasty) may be
necessary for a good outcome. A patient with a
substance use disorder might have difficulty
keeping necessary appointments to the primary
care provider and the surgeon. A patient with
psychosis or severe depression might neglect
their wound or not be attentive to infection or
signs of dehiscence (Lee, Marsh et al., 2016).
Active mental illness is associated with a greater
need for further acute medical and surgical care
after the initial surgery (Wimalawansa
et  al., 2014).

In these cases, treatment of the mental illness
or substance use disorder may assist in achieving
successful outcomes. Arranging more support for
the patient from family and friends or a home
health care worker may help the patient participate sufficiently in perioperative care for surgery
to proceed. The benefits of mental health treatments that may delay surgery should be weighed
against the risks of delaying surgery and should 
include an assessment of the impact on the
patients’ mental health delays may cause in
addressing gender dysphoria (Byne et  al., 2018).

## Statement 18.3: We recommend when significant mental health symptoms or substance abuse exists, mental health professionals assess the potential negative impact mental health symptoms may have on outcomes based on the nature of the specific gender-affirming surgical procedure. {-}

Gender-affirming surgical procedures vary in
terms of their impact on the patient. Some procedures require a greater ability to follow preoperative planning as well as engage in peri- and
postoperative care to achieve the best outcomes
(Tollinche et  al., 2018). Mental health symptoms
can influence a patient’s ability to participate in
the planning and perioperative care necessary for
any surgical procedure (Paredes et  al., 2020). The
mental health assessment can provide an opportunity to develop strategies to address the potential negative impact mental health symptoms may
have on outcomes and to plan support for the
patient’s ability to participate in the planning and
care. Gender-affirming surgical procedures have
been shown to relieve symptoms of gender dysphoria and improve mental health (Owen-Smith
et  al., 2018; van de Grift, Elaut et  al., 2017).
These benefits are weighed against the risks of
each procedure when the patient and provider
are deciding whether to proceed with the treatment. HCPs can assist TGD people in reviewing
preplanning and perioperative care instructions
for each surgical procedure (Karasic, 2020).
Provider and patient can collaboratively determine the necessary support or resources needed
to assist with keeping appointments for perioperative care, obtaining necessary supplies, addressing financial issues, and handling other
preoperative coordination and planning. In addition, issues surrounding appearance-related and
functional expectations, including the impact of
these various factors on gender dysphoria, can
be explored.

## Statement 18.4: We recommend health care professionals assess the need for psychosocial and practical support of transgender and gender diverse people in the perioperative period surrounding gender-affirmation surgery. {-}

Regardless of specialty, all HCPs have a responsibility to support patients in accessing medically
necessary care. When HCPs are working with
TGD people as they prepare for gender-affirming
surgical procedures, they should assess the levels
of psychosocial and practical support required
(Deutsch, 2016b). Assessment is the first step in
recognizing where additional support may be
needed and enhancing the ability to work collaboratively with the individual to successfully
navigate the pre-, peri-, and postsurgical periods
(Tollinche et al., 2018). In the perioperative
period, it is important to help patients optimize
functioning, secure stable housing, when possible,
build social and family supports by assessing their
unique situation, plan ways of responding to
medical complications, navigate the potential
impact on work/income, and overcome additional
hurdles some patients may encounter, such as
coping with electrolysis and tobacco cessation
(Berli et  al., 2017). In a complex medical system,
not all patients will be able to independently
navigate the procedures required to obtain care,
and HCPs and peer navigators can support
patients through this process (Deutsch, 2016a).

## Statement 18.5: We recommend health care professionals counsel and assist transgender and gender diverse people in becoming abstinent from tobacco/ nicotine prior to gender-affirmation surgery.{-}

Transgender populations have higher rates of
tobacco and nicotine use (Kidd et  al., 2018).
However, many are unaware of the
well-documented smoking-associated health risks
(Bryant et  al., 2014). Tobacco consumption
increases the risk of developing health problems
(e.g., thrombosis) in individuals receiving
gender-affirming hormone treatment, particularly
estrogens (Chipkin & Kim, 2017).

Tobacco use has been associated with worse outcomes in plastic surgery, including overall complications, tissue necrosis, and the need for surgical
revision (Coon et al., 2013). Smoking also increases
the risk for postoperative infection (Kaoutzanis
et al., 2019). Tobacco use has been shown to affect 
the healing process following any surgery, including
gender-related surgeries (e.g., chest reconstructive
surgery, genital surgery) (Pluvy, Garrido et  al.,
2015). Tobacco users have a higher risk of cutaneous necrosis, delayed wound healing, and scarring disorders due to hypoxia and tissue ischemia
(Pluvy, Panouilleres et  al., 2015). In view of this,
surgeons recommend stopping the use of tobacco/
nicotine prior to gender-affirmation surgery and
abstaining from smoking up to several weeks postoperatively until the wound has completely healed
(Matei & Danino, 2015). Despite the risks, cessation may be difficult. Tobacco smoking and nicotine use is addictive and is also used as a coping
mechanism (Matei et  al., 2015). HCPs who see
patients longitudinally before surgery, including
mental health and primary care providers, should
address the use of tobacco/nicotine with individuals
in their care, and either assist TGD people in
accessing smoking cessation programs or provide
treatment directly (e.g., varenicline or bupropion).

## Statement 18.6: We recommend health care professionals maintain existing hormone treatment if a transgender and gender diverse individual requires admission to a psychiatric or medical inpatient unit, unless contraindicated. {-}

TGD people entering inpatient psychiatric, substance use treatment, or medical units should be
maintained on their current hormone regimens.
There is an absence of evidence supporting routine cessation of hormones prior to medical or
psychiatric admissions. Rarely, a newly admitted
patient may be diagnosed with a medical complication necessitating suspension of hormone
treatment, for example an acute venous thromboembolism (Deutsch, 2016a). There is no strong
evidence for routinely stopping hormone treatment prior to surgery, and the risks and benefits
for each individual patient should be assessed
before doing so (Boskey et  al., 2018).

Hormone treatment has been shown to improve
quality of life and to decrease depression and
anxiety (Aldridge et al., 2020; Nguyen et al., 2018;
Nobili et  al., 2018; Owen-Smith et  al., 2018,
Rowniak et  al., 2019). Access to gender-affirming
medical treatment is associated with a substantial
reduction in the risk of suicide attempt (Bauer
et  al., 2015). Halting a patient’s regularly prescribed hormones denies the patient of these
salutary effects, and therefore may be counter to
the goals of hospitalization.

Some providers may be unaware of the low risk
of harm and the high potential benefit of continuing transition-related treatment in the inpatient
setting. A study of US and Canadian medical
schools revealed that students received an average
of 5 hours of LGBT-related course content over
their entire four years of education (Obedin-Maliver
et  al., 2011). According to a survey of Emergency
Medicine physicians, who are often responsible for
making quick decisions about medications as
patients are being admitted, while 88% reported
caring for transgender patients, only 17.5% had
received any formal training about this population
(Chisolm-Straker et al., 2018). As education about
transgender topics increases, more providers will
become aware of the importance of maintaining
transgender patients on their hormone regimens
during hospitalization.

## Statement 18.7: We recommend health care professionals ensure if transgender and gender diverse people need inpatient or residential mental health, substance abuse, or medical care, all staff use the correct name and pronouns (as provided by the patient), as well as provide access to bathroom and sleeping arrangements that are aligned with the person's gender identity. {-}

Many TGD patients encounter discrimination
in a wide range of health settings, including hospitals, mental health treatment settings, and drug
treatment programs (Grant et  al., 2011). When
health systems fail to accommodate TGD individuals, they reinforce the longstanding societal
exclusion many have experienced (Karasic, 2016).
Experiences of discrimination in health settings
lead to avoidance of needed health care due to
anticipated discrimination (Kcomt et  al., 2020).

The experience of discrimination experienced
by TGD individuals is predictive of suicidal ideation (Rood et  al., 2015; Williams et  al., 2021).
Gender minority stress associated with rejection
and nonaffirmation has also been associated with
suicidality (Testa et  al., 2017). Denial of access
to gender appropriate bathrooms has been 
associated with increased suicidality (Seelman,
2016). However, the use of chosen names for
TGD people has been associated with lower
depression and suicidality (Russell et  al., 2018).
Structural as well as internalized transphobia
must be addressed to reduce the incidence of
suicide attempts in TGD people (Brumer et  al.,
2015). To successfully provide care, health settings must minimize the harm done to patients
because of transphobia by respecting and accommodating TGD identities.

## Statement 18.8: We recommend mental health professionals encourage, support, and empower transgender and gender diverse people to develop and maintain social support systems, including peers, friends, and families. {-}

While minority stress and the direct effects of
discriminatory societal discrimination can be
harmful to the mental health of TGD people,
strong social support can help lessen this harm
(Trujillo et  al., 2017). TGD children often internalize rejection from family and peers as well as
the transphobia that surrounds them (Amodeo
et al., 2015). Furthermore, exposure to transphobic
abuse may be impactful across a person’s lifespan
and may be particularly acute during the adolescent years (Nuttbrock et  al., 2010).

The development of affirming social support
is protective of mental health. Social support can
act as a buffer against the adverse mental health
consequences of violence, stigma, and discrimination (Bockting et  al., 2013), can assist in navigating health systems (Jackson Levin et  al.,
2020), and can contribute to psychological resilience in TGD people (Bariola et  al., 2015; Başar
and Öz, 2016). Diverse sources of social support,
especially LGBTQ + peers and family, have been
found to be associated with better mental health
outcomes, well-being, and quality of life (Bariola
et  al., 2015; Başar et  al., 2016; Kuper, Adams
et  al., 2018; Puckett et  al., 2019). Social support
has been proposed to facilitate the development
of coping mechanisms and lead to positive emotional experiences throughout the transition process (Budge et  al., 2013).

HCPs can support patients in developing social
support systems that allow them to be recognized
and accepted as their authentic identity and help
them cope with symptoms of gender dysphoria.
Interpersonal problems and lack of social support
have been associated with a greater incidence of
mental health difficulties in TGD people (Bouman,
Davey et  al., 2016; Davey et  al., 2015) and have
been shown to be an outcome predictor of
gender-affirming medical treatment (Aldridge
et  al., 2020). Therefore, HCPs should encourage,
support, and empower TGD people to develop
and maintain social support systems. These experiences can foster the development of interpersonal skills and help with coping with societal
discrimination, potentially reducing suicidality
and improving mental health (Pflum et  al., 2015).

## Statement 18.9: We recommend health care professionals should not make it mandatory for transgender and gender diverse people to undergo psychotherapy prior to the initiation of gender-affirming treatment, while acknowledging psychotherapy may be helpful for some transgender and gender diverse people. {-}

Psychotherapy has a long history of being used
in clinical work with TGD people (Fraser, 2009b).
The aims, requirements, methods and principles
of psychotherapy have been an evolving component of the Standards of Care from the initial
versions (Fraser, 2009a). At present, psychotherapeutic assistance and counseling with adult TGD
people may be sought to address common psychological concerns related to coping with gender
dysphoria and may also help some individuals with
the coming-out process (Hunt, 2014). Psychological
interventions, including psychotherapy, offer effective tools and provide context for the individual,
such as exploring gender identity and its expression, enhancing self-acceptance and hope, and
improving resilience in hostile and disabling environments (Matsuno and Israel, 2018). Psychotherapy
is an established alternative therapeutic approach
for addressing mental health symptoms that may
be revealed during the initial assessment or later
during the follow-up for gender-affirming medical
interventions. Recent research shows, although
mental health symptoms are reduced following
gender-affirming medical treatment, levels of anxiety remain high (Aldridge et al., 2020) suggesting
psychological therapy can play a role in helping 
individuals suffering from anxiety symptoms following gender-affirming treatment.

In recent years, the uses and potential benefits
of specific psychotherapeutic modalities have
been reported (Austin et  al., 2017; Budge, 2013;
Budge et  al., 2021; Embaye, 2006; Fraser, 2009b;
Heck et  al., 2015). Specific models of psychotherapy have been proposed for adult transgender
and nonbinary individuals (Matsuno & Israel,
2018). However, more empiric data is needed on
the comparative benefits of different psychotherapeutic models (Catelan et  al., 2017).
Psychotherapy can be experienced by transgender
persons as a fearful as well as a beneficial experience (Applegarth & Nuttall, 2016) and presents
challenges to the therapist and to alliance formation when it is associated with gatekeeping for
medical interventions (Budge, 2015).

Experience suggests many transgender and nonbinary individuals decide to undergo genderaffirming medical treatment with little or no use
of psychotherapy (Spanos et  al., 2021). Although
various modalities of psychotherapy may be beneficial for different reasons before, during, and after
gender-affirming medical treatments and varying
rates of desire for psychotherapy have been reported
during different stages of transition (Mayer et  al.,
2019), a requirement for psychotherapy for initiating gender-affirming medical procedures has not
been shown to be beneficial and may be a harmful
barrier to care for those who do not need this type
of treatment or who lack access to it.

## Statement 18.10: We recommend “reparative” and “conversion” therapy aimed at trying to change a person’s gender identity and lived gender expression to become more congruent with the sex assigned at birth should not be offered. {-}

The use of “reparative” or “conversion” therapy
or gender identity “change” efforts is opposed
by many major medical and mental health organizations across the world, including the World
Psychiatric Association, Pan American Health
Organization, American Psychiatric and American
Psychological Associations, Royal College of
Psychiatrists, and British Psychological Society.
Many states in the US have instituted bans on
practicing conversion therapy with minors.
Gender identity change efforts refers to interventions by MHPs or others that attempt to
change gender identity or expression to be more
in line with those typically associated with the
person’s sex assigned at birth (American
Psychological Association, 2021).

Advocates of “conversion therapy” have suggested it could potentially allow a person to fit
better into their social world. They also point
out some clients specifically ask for help changing
their gender identities or expressions and therapists should be allowed to help clients achieve
their goals. However, “conversion therapy” has
not been shown to be effective (APA, 2009;
Przeworski et  al., 2020). In addition, there are
numerous potential harms. In retrospective studies, a history of having undergone conversion
therapy is linked to increased levels of depression,
substance abuse, suicidal thoughts, and suicide
attempts, as well as lower educational attainment
and less weekly income (Ryan et  al., 2020; Salway
et  al., 2020; Turban, Beckwith et  al., 2020). In
2021, the American Psychological Association
resolutions states that “scientific evidence and
clinical experience indicate that GICEs [gender
identity change efforts] put individuals at significant risk of harm” (APA, 2021).

While there are barriers to ending gender identity “change” efforts, education about the lack of
benefit and the potential harm of these practices
may lead to fewer providers offering “conversion
therapy” and fewer individuals and families
choosing this option.

