--- 
title: "WPATH's Standards Of Care Version 8"
author: "E. Coleman, et al."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a book on WPATH's Standards of Care Version 8."
---

# Abstract {-}

**Background:** Transgender healthcare is a rapidly evolving interdisciplinary field. In the last
decade, there has been an unprecedented increase in the number and visibility of transgender
and gender diverse (TGD) people seeking support and gender-affirming medical treatment
in parallel with a significant rise in the scientific literature in this area. The World Professional
Association for Transgender Health (WPATH) is an international, multidisciplinary, professional
association whose mission is to promote evidence-based care, education, research, public
policy, and respect in transgender health. One of the main functions of WPATH is to promote
the highest standards of health care for TGD people through the Standards of Care (SOC).
The SOC was initially developed in 1979 and the last version (SOC-7) was published in 2012.
In view of the increasing scientific evidence, WPATH commissioned a new version of the
Standards of Care, the SOC-8.

**Aim:** The overall goal of SOC-8 is to provide health care professionals (HCPs) with clinical
guidance to assist TGD people in accessing safe and effective pathways to achieving lasting
personal comfort with their gendered selves with the aim of optimizing their overall physical
health, psychological well-being, and self-fulfillment.

**Methods:** The SOC-8 is based on the best available science and expert professional consensus
in transgender health. International professionals and stakeholders were selected to serve
on the SOC-8 committee. Recommendation statements were developed based on data
derived from independent systematic literature reviews, where available, background reviews
and expert opinions. Grading of recommendations was based on the available evidence
supporting interventions, a discussion of risks and harms, as well as the feasibility and
acceptability within different contexts and country settings.

**Results:** A total of 18 chapters were developed as part of the SOC-8. They contain
recommendations for health care professionals who provide care and treatment for TGD
people. Each of the recommendations is followed by explanatory text with relevant references.
General areas related to transgender health are covered in the chapters Terminology, Global
Applicability, Population Estimates, and Education. The chapters developed for the diverse
population of TGD people include Assessment of Adults, Adolescents, Children, Nonbinary,
Eunuchs, and Intersex Individuals, and people living in Institutional Environments. Finally,
the chapters related to gender-affirming treatment are Hormone Therapy, Surgery and
Postoperative Care, Voice and Communication, Primary Care, Reproductive Health, Sexual
Health, and Mental Health.

**Conclusions:** The SOC-8 guidelines are intended to be flexible to meet the diverse health
care needs of TGD people globally. While adaptable, they offer standards for promoting
optimal health care and guidance for the treatment of people experiencing gender
incongruence. As in all previous versions of the SOC, the criteria set forth in this document
for gender-affirming medical interventions are clinical guidelines; individual health care
professionals and programs may modify these in consultation with the TGD person.

## Citation {-}

To cite this article: E. Coleman, A. E. Radix, W. P. Bouman, G. R. Brown, A. L. C. de Vries, M. B.
Deutsch, R. Ettner, L. Fraser, M. Goodman, J. Green, A. B. Hancock, T. W. Johnson, D. H. Karasic,
G. A. Knudson, S. F. Leibowitz, H. F. L. Meyer-Bahlburg, S. J. Monstrey, J. Motmans, L. Nahata,
T. O. Nieder, S. L. Reisner, C. Richards, L. S. Schechter, V. Tangpricha, A. C. Tishelman, M. A.
A. Van Trotsenburg, S. Winter, K. Ducheny, N. J. Adams, T. M. Adrián, L. R. Allen, D. Azul, H.
Bagga, K. Başar, D. S. Bathory, J. J. Belinky, D. R. Berg, J. U. Berli, R. O. Bluebond-Langner, M.-
B. Bouman, M. L. Bowers, P. J. Brassard, J. Byrne, L. Capitán, C. J. Cargill, J. M. Carswell, S. C.
Chang, G. Chelvakumar, T. Corneil, K. B. Dalke, G. De Cuypere, E. de Vries, M. Den Heijer, A.
H. Devor, C. Dhejne, A. D’Marco, E. K. Edmiston, L. Edwards-Leeper, R. Ehrbar, D. Ehrensaft,
J. Eisfeld, E. Elaut, L. Erickson-Schroth, J. L. Feldman, A. D. Fisher, M. M. Garcia, L. Gijs, S. E.
Green, B. P. Hall, T. L. D. Hardy, M. S. Irwig, L. A. Jacobs, A. C. Janssen, K. Johnson, D. T. Klink,
B. P. C. Kreukels, L. E. Kuper, E. J. Kvach, M. A. Malouf, R. Massey, T. Mazur, C. McLachlan, S.
D. Morrison, S. W. Mosser, P. M. Neira, U. Nygren, J. M. Oates, J. Obedin-Maliver, G. Pagkalos,
J. Patton, N. Phanuphak, K. Rachlin, T. Reed, G. N. Rider, J. Ristori, S. Robbins-Cherry, S. A.
Roberts, K. A. Rodriguez-Wallberg, S. M. Rosenthal, K. Sabir, J. D. Safer, A. I. Scheim, L. J. Seal,
T. J. Sehoole, K. Spencer, C. St. Amand, T. D. Steensma, J. F. Strang, G. B. Taylor, K. Tilleman,
G. G. T’Sjoen, L. N. Vala, N. M. Van Mello, J. F. Veale, J. A. Vencill, B. Vincent, L. M. Wesp, M.
A. West & J. Arcelus (2022) Standards of Care for the Health of Transgender and Gender
Diverse People, Version 8, International Journal of Transgender Health, 23:sup1, S1-S259, DOI:
10.1080/26895269.2022.2100644

## Original article {-}

To find original article, visit this link: https://www.tandfonline.com/doi/pdf/10.1080/26895269.2022.2100644

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
